ethereum/execution-spec-tests

src/ethereum_test/blockchain_test.py
src/ethereum_test/fill.py
src/ethereum_test/fork.py
src/ethereum_test/state_test.py
src/ethereum_test/types.py
src/evm_transition_tool/__init__.py
tests/ethereum_test/test_filler.py
tests/evm_transition_tool/test_evaluate.py
whitelist.txt

- Consolidates block requirements per fork to a single place (except for usages in `evm_transition_tool`)
- Add `Merged` fork to all generated tests

Consolidate Fork Requirements + Add Post-Merge Tests

---

src/ethereum_test_tools/vm/fork.py
src/evm_transition_tool/__init__.py

Fix fork name to allow tests with fork names <Shanghai to run.

Update 'Merged' fork name to match geth 'Merge' fork name.

---

fillers/withdrawals/withdrawals.py

Adds a withdrawals test that checks uint64 values which, when multiplied by 1e9, would overflow uint64 but not uint256.

fillers/withdrawals: Add another withdrawals test with large amounts

---

README.md

- Direct people to the most up to date EVM.
- Explain how to upgrade

readme: Updates

---

fillers/withdrawals/withdrawals.py

fillers/withdrawals: Remove Overflow Test

---

fillers/withdrawals/withdrawals.py
src/ethereum_test_tools/spec/blockchain_test.py

Fixture Format: Add default pre-state to withdrawals/use_value_in_tx so pre/post in fixture is not empty.

---

fillers/example/acl_example.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/common/__init__.py
src/ethereum_test_tools/common/types.py

Add `AccessList` type and provide an example of a case with access list transactions.

add access list txn

---

.gitignore
fillers/eips/eip4844/excess_data_gas.py

Test case for underflow blobs is uncommented as https://github.com/mdehoog/go-ethereum/pull/122 has been merged.

fillers/eip4844: Uncomment blob underflow testcase

---

.gitignore
fillers/eips/eip4844/excess_data_gas.py
fillers/security/__init__.py
fillers/security/selfdestruct_balance_bug.py
whitelist.txt

Adds a test for an older bug:  https://github.com/ethereum/go-ethereum/security/advisories/GHSA-xw37-57qp-9mm4

fillers/security: Add test for tx selfdestuct balance security bug

---

docs/index.md
docs/tutorials/blockchain.md
docs/tutorials/state_transition.md
mkdocs.yml

This wasn't the fix: https://github.com/ethereum/execution-spec-tests/pull/116
Its working in my forked repo: https://execution-spec-tests-build-testing.readthedocs.io/en/latest/test_case_descriptions/eip4844/

docs: Fix more rtdio errors.

---

src/pytest_plugins/forks/forks.py
tests/eips/eip4844/test_blobhash_opcode_contexts.py
tests/eips/test_eip3855.py

- Fix transition forks in the forks plug-in
- Remove unnecessary YUL from tests/eips/test_eip3855.py
- Remove invalid test from tests/eips/eip4844/test_blobhash_opcode_contexts.py

plugins/forks: Fix transition forks

---

README.md
docs/gen_test_case_reference.py
docs/getting_started/executing_tests_command_line.md
docs/getting_started/quick_start.md
docs/writing_tests/adding_a_new_test.md

docs: fix paths due to directory structure, forgotten in #156

docs: fix paths due to directory structure

---

setup.cfg

Updates the version in the `setup.cfg` file in preparation for release.

Update version (v1.0.0)

---

.wordlist.txt
.wordlist_opcodes.txt
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/vm/__init__.py
src/ethereum_test_tools/vm/opcode.py
tests/cancun/eip5656_mcopy/__init__.py
tests/cancun/eip5656_mcopy/common.py
tests/cancun/eip5656_mcopy/test_mcopy.py
tests/cancun/eip5656_mcopy/test_mcopy_contexts.py
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py

Adds tests for the MCOPY opcode.

tests: Add EIP-5656, MCOPY, Tests

---

docs/getting_started/quick_start.md
docs/getting_started/repository_overview.md
docs/tutorials/blockchain.md
docs/tutorials/state_transition.md
docs/tutorials/state_transition_bad_opcode.md

fix: typos

---

tests/merge/security/test_selfdestruct_balance_bug.py

Fixes the self-destruct balance bug test to be Cancun compatible, i.e. the self-destructing account is created and self-destructed in the same transaction.

tests/merge/security: Fix self-destruct balance bug for Cancun

---

tests/cancun/eip6780_selfdestruct/test_selfdestruct.py

Workaround for https://github.com/ethereum/execution-spec-tests/issues/234

tests/eip6780: Fix block gas limit

---

README.md
docs/index.md
src/evm_transition_tool/evmone.py

Adds tracing for `evmone-t8n` which was recently implemented in https://github.com/ethereum/evmone/pull/616.

Tools: Add tracing to evmone t8n

---

tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py

Tagging: https://github.com/ethereum/execution-spec-tests/issues/259

tests/cancun/eip4844_blobs: Update error naming

---

tests/cancun/eip1153_tstore/test_tstorage.py
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py
whitelist.txt

Adds to the coverage from #230. 
Closes #291.

tests: add more transient storage/eip-1153 tests

---

docs/CHANGELOG.md

Update the changelog for v1.0.5.

docs: update changelog for release v1.0.5

---

docs/CHANGELOG.md

Updates the changelog to match the previous latest release edit and appends the changelog template to the top to help aid with the next release.

chore(docs): update changelog to match latest release

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CHANGELOG.md

Adds a PR template which should populate the PR's description field with a few reminders.

chore: add a pull request template with a few reminders

---

README.md
docs/CHANGELOG.md
whitelist.txt

Updates the README.md with the most recent t8n tool.

chore(README.md): update readme with most recent t8n branch

---

tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py

first case from
https://github.com/ethereum/execution-spec-tests/issues/381

feat(tests): dynamic create2 selfdestruct collision 

---

docs/CHANGELOG.md

Updates the changelog after releasing v2.1.1.
N/A

docs: update changelog for post release v2.1.1

---

docs/writing_tests/code_standards.md
docs/writing_tests/exception_tests.md

chore: remove repetitive words

---

tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py

chore: fix tyoo in comment

---

.github/workflows/test.yaml

fix github workflow

---

README.md
docs/getting_started/installation_troubleshooting.md
docs/getting_started/quick_start.md
docs/navigation.md
whitelist.txt

Adds a small troubleshooting section to the docs, and the appropriate link from the `README.md`.
None

feat(docs:) Add installation troubleshooting

---

.github/actions/build-besu-evm/action.yaml
.github/actions/build-evm/action.yaml

Add github actions to build the Besu EVM

feat(github): Build support for Besu EVM

---

src/ethereum_test_tools/spec/eof/eof_test.py

For invalid EOF containers we also generate EIP-7698 create transaction but with the expectation to fail.

feat(fw): support invalid containers in EOFStateTest

---

docs/CHANGELOG.md

Changelog changes in preparation for v3.0.0
None

chore(docs): v3.0.0 changelog

---

src/cli/gen_index.py

Fixes the UI for gen index when running consume with blockchain engine fixtures.
N/A

chore(pytest): fix gen index plugin UI for engine tests

---

src/cli/pytest_commands.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/hive_simulators/conftest.py

Adds a flag to enable timing data.

feat(consume): add timing data flag

---

src/ethereum_test_types/types.py

fix: mypy tox issue.

---

.github/workflows/coverage.yaml

Pr coverage

---

tests/verkle/eip4762_verkle_gas_witness/test_calls.py

This PR fixes the parameters of an existed skipped test so it works as expected.

eip4762: enable calls with insufficient gas tests again

---

tests/verkle/eip4762_verkle_gas_witness/test_selfdestruct.py

This PR adds tests which generate partial witnesses due to insufficient gas for SELFDESTRUCT.

new(tests): eip-4762 SELFDESTRUCT with insufficient gas

---

tests/verkle/eip4762_verkle_gas_witness/test_codecopy_generic.py
tests/verkle/eip4762_verkle_gas_witness/test_creates.py

This PR has some fixes that make all tests fill correctly.

Filling fixes

---

.github/workflows/coverage.yaml

fix coverage log on errors

---

tests/verkle/eip6800_genesis_verkle_tree/test_contract_creation.py

Add a test that simulates a bug that Besu had while syncing Devnet 7.
Waiting for Besu confirmation that this test fails and succeeds in the unpatched and patched versions.

verkle: add contract creation failure scenario

---

src/ethereum_test_forks/base_fork.py

refactor(forks): suggestions for fork transition marker changes

---

src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py

The commit messages can be read commit-by-commit for a description.
#1118

refactor,test(fill): suggestions for `x-dist-mode-fixture-collector` #1118

---

.github/configs/evm.yaml
.github/configs/feature.yaml
tests/cancun/eip4844_blobs/spec.py

Update evm features in CI config for release candidate `v4.0.0`.
https://github.com/ethereum/execution-spec-tests/actions/runs/13293233212

chore(ci): update evm configs

---

src/ethereum_test_types/types.py

I need this for my unit tests for my structured data library.

fix(types): implement `__eq__` for Removable

---

.github/workflows/docs_deploy.yaml

This the error introduced in #1317
- #1317

fix(ci,docs): fix docs deployment

---

.vscode/extensions.json

Pylance (not the buggy pytest-fixtures) extension supports F12 / Go to definition with pytest fixtures. It even supports Rename Symbol for fixture names, check the video here:
https://code.visualstudio.com/updates/v1_76#_improved-intellisense-support-for-pytest
None

chore(tooling): add pylance to recommended vs code extensions

---

docs/CHANGELOG.md
docs/dev/deps_and_packaging.md
docs/dev/index.md
whitelist.txt

It's never immediately obvious to me how to update optional package deps, this short document describes that.
For example
- #1387

docs(deps): document how to manage eest dependencies

---

README.md

Points the Readme release badge to the latest release.
N/A

chore(docs): added a link to the badge release

---

src/ethereum_test_types/helpers.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_gas.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_memory.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_returncode.py

eof-devnet-1 spec change according to https://github.com/ethereum/EIPs/pull/9298

fix(tests): Change EOFCREATE new address and related gas calculations

---

.github/workflows/check-links.yml
.lycheeignore

Adds a github action to check all links in *.md and *.py files that runs daily.
- #1374

chore(ci,docs): add a github action to check links in .md, .py

---

pyrightconfig.json

Adds include and exclude lists to `pyrightconfig.json`.
These are the list that have been working for me locally and make the usage of vscode manageable.
None

chore(pyright): Add include/exclude

---

src/ethereum_test_tools/utility/versioning.py

Optimize the versioning module with several small but valuable efficiency improvements:
1. Simplify get_current_commit_hash_or_tag:
- Replace the next() generator with a simple for loop for better readability
- Access commit hash directly from current_commit.hexsha instead of storing in a variable
- Early return when a tag is found
2. Clean up generate_github_url:
- Use conditional expression for line_number fragment
- Remove unnecessary multi-line string concatenation
- Improve code spacing for better readability
- Use a more concise string formatting approach

refactor(tools): optimize git tag lookup and URL generation

---

src/ethereum_test_tools/code/generators.py
tests/prague/eip7702_set_code_tx/test_gas.py

Added comments, simplified the logic, and fixed the issue with the failing test in the parent PR, #1441.

7702 add increased nonce with invalid nonce test

---

src/ethereum_test_specs/eof.py

Fixes EOF exception mapping to use the new refactored exception mapping framework.
Fixes filling invalid EOF tests with evmone.
None

fix(specs/eof): Exception mapping fix

---

tests/frontier/precompiles/test_precompiles.py

Took the liberty to implement the fixes in the review for #1495 since Dan is OOO.
The IDs are kinda ugly right now:
```
tests/frontier/precompiles/test_precompiles.py::test_precompile_warming[fork_ParisToShanghaiAtTime15k-address_0x0000000000000000000000000000000000000001-precompile_in_successor_True-precompile_in_predecessor_True-blockchain_test]
```
And we could reduce it to only print the address perhaps, but let me know what you think.

fix: review comments for #1495

---

docs/CHANGELOG.md

Bump changelog for new release.
#1501

chore(docs): bump changelog for v4.4.0 release.

---

docs/CHANGELOG.md
src/cli/eest/cli.py
src/cli/eest/commands/__init__.py
src/cli/eest/commands/info.py
src/config/app.py

We'll have to ensure we update the config version when we release:
https://github.com/ethereum/execution-spec-tests/blob/7966338fd626395b9144d60b180ef326b95872e7/src/config/app.py#L16
Let me know if anything else needs to be added.
closes #1619

✨ feat(cli): `eest` info

---

tests/zkevm/test_worst_compute.py

This adds the benchmarks for EVM execution focused on unary
instructions (takes one value, produces one).
The benchmark has simple structure: the contract code is the infinite
loop filled up to the code size limit with the parametrized opcode.
https://github.com/ethereum/execution-spec-tests/issues/1571

feat(tests): add benchmarks with mass unop opcodes

---

tests/zkevm/test_worst_compute.py

Add a worst-case test running a block with many `ADDMOD` or `MULMOD` instructions with arguments of the parametrized range.
https://github.com/ethereum/execution-spec-tests/issues/1571

feat(tests/zkevm): add worst-case benchmarks for `ADDMOD` and `MULMOD`

---

src/pytest_plugins/filler/eip_checklist.py

Fixes CI error for new spellcheck.
N/A

chore: fix spellcheck in filler eip checklist

---

src/cli/gentest/test_context_providers.py
src/ethereum_test_rpc/types.py

This PR updates the fields in `TransactionHashReponse` to match that of the `Transaction` model. This ensures that RPC data is parsed correctly into the framework.
closes  #1753

✨ feat: Align TransactionHashByResponse to Transaction

---

.gitignore

Exclude cache folders and other temporary files
N/A.
```console
```

toolings(fix): improved gitignore

---

tests/benchmark/test_worst_memory.py

I performed a pre-filling of current tests in `main` for 1M and 5M, and I noticed that some cases failed.
The reason for failure is that the intrinsic cost is higher than the gas limit; thus the transaction execution failed.
Since these 1M and 5M cases are primarily toy-like cases for zkVM CIs and quick experiments, I addressed this by calculating the intrinsic cost and skipping the case if the gas limit is too low.
This is something that would have surfaced whenever we tagged the next release (see linked PR below).
https://github.com/ethereum/execution-spec-tests/pull/1876

fix(benchmark): Fix CALLDATACOPY filling for low gas limits

---

src/ethereum_clis/clis/besu.py

blob count max exception mapper

fix(clis/besu): blob count max exception mapper

---

src/pytest_plugins/execute/execute.py
src/pytest_plugins/filler/filler.py

Minor optimization during test collection to skip copying the entire list of tests to modify it.
Required to fill benchmark tests.
N/A.
```console
```

fix(plugins): Don't copy test list during collection

---

src/ethereum_clis/clis/geth.py

Fix https://hive.ethpandaops.io/fusaka-devnet-3/suite.html?suiteid=1753629530-267028c65c705f5abb158cb41a9fa3ad.json#test-3468

chore(clis): update geth exception mapper for `TYPE_3_TX_BLOB_COUNT_EXCEEDED`

---

tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

Small addition to satify CLZ meta issue cases.
#1795 
```console
```

feat(tests): extra clz param for scenarios test case

---

src/ethereum_clis/clis/erigon.py

See https://github.com/erigontech/erigon/pull/16391

chore(clis): add erigon exception mapper for TYPE_3_TX_BLOB_COUNT_EXCEEDED

---

src/pytest_plugins/shared/benchmarking.py

Update the max env gas for benchmark tests. Lets us fill for 150M gas.
N/A.
```console
```

chore(benchmark): update max env gas

---

tests/osaka/eip7594_peerdas/test_max_blob_per_tx.py

Update transaction tests with max blobs per tx > max blobs per block.
#1997 
```console
```

chore(tests): exception hotfix

---

tests/benchmark/test_worst_blocks.py

Case 1: Create N distinct empty authority accounts, each delegating to the same target contract T.
Case 2: Create N delegated accounts that re-delegate to a new target contract T.
Case 3: Create N distinct empty authority accounts that delegate to the zero address (empty code).
Case 4: Create N delegated accounts that explicitly cancel their delegation.
Case 5: Execute EXTCODESIZE against accounts that delegate to contracts with maximum code size.
Case 6: Execute EXTCODECOPY against accounts that delegate to contracts with maximum code size.
Case 7: Execute STATICCALL against accounts that delegate to contracts with maximum code size.
Goal: These scenarios are designed to complement the stress cases highlighted by @MariusVanDerWijden:
- 7702 contract code loads
- 7702 signature bombs
- …

feat(benchmark): add eip7702 case
