ethereum/execution-spec-tests

.github/workflows/test.yaml

Geth bumped the minimum golang version to 1.18 [a few days ago](https://github.com/ethereum/go-ethereum/pull/26160). Since we're building directly from master we need to do the same.

Bump golang to 1.18

---

src/ethereum_test_filling_tool/main.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/code.py
src/ethereum_test_tools/common/__init__.py
src/ethereum_test_tools/common/helpers.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/filling/decorators.py
src/ethereum_test_tools/filling/fill.py
src/ethereum_test_tools/spec/base_test.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/debugging.py
src/ethereum_test_tools/spec/state_test.py
src/evm_transition_tool/__init__.py
src/evm_transition_tool/tests/test_evaluate.py
whitelist.txt

- Adds EIPs support for a test to specify extra EIPs used to call the transition tool
- When a test fails during the filling phase, now the full traces are printed
- Include a gas measuring helper, to easily create tests that expect a certain amount of gas usage on a code excerpt
- Add custom exception types, to better catch specific types of errors

Transition Tool EIPs Support, Print Traces, Helper Methods

---

fillers/eips/eip3651.py
fillers/eips/eip3855.py
fillers/eips/eip3860.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/code.py
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/__init__.py
src/ethereum_test_tools/vm/opcode.py
whitelist.txt

- Adds the `Opcode` class which describes a single EVM opcode, and adds metadata useful for testing purposes. The proposed metadata included is:
- Stack items popped/pushed: Number of items popped/pushed from/to the stack. Useful for, e.g., EOF testing where the code validation will include stack validation.
- Minimum stack height: In order to not produce a stack underflow. Differs from popped items in the case of, e.g., DUP* opcodes.
- Data portion length: Number of bytes the opcode consumes as data. Used to automatically format the data the opcode needs when converting to bytecode.
- Changes EIP tests to use the opcode definitions, in order to exemplify usage.
Fixes #14 
ToDos:
- Add a comprehensive README entry if this idea gets a thumbs up.

Add EVM Opcodes

---

src/evm_transition_tool/__init__.py

Small fix to return the empty withdrawals root immediately without calling the transition tool, and also avoid errors on go-ethereum branches that don't have withdrawals implemented.

Fix Empty Withdrawals Root

---

README.md

This small PR is doc only. It expands the "Getting Started" section to help developers/users more quickly orientate themselves in the repo and its setup. It also fixes a couple of typos.

Docs: Expand "Quick Start" Section in Readme

---

src/ethereum_test_tools/__init__.py

It looks like `test_from_until` was forgotten in the `ethereum-test-tools` init file.

Fix: Expose `test_from_until` filling decorator in ethereum-test-tools package

---

src/ethereum_test_tools/tests/test_helpers.py

This PR add tests for the helper functions `compute_create_address` and `compute_create2_address` in `src/ethereum_test_tools/common/helpers.py`.
These were originally implemented for #24 which did not get merged.

framework tests: add tests for compute create address helper functions

---

fillers/eips/eip3860.py

Adds a non-zero salt to all create2 creations as per https://github.com/ethereum/tests/pull/1125/files

fillers/eips: add salt to create2 contract creation

---

fillers/eips/eip3651.py
fillers/eips/eip3855.py
fillers/eips/eip3860.py

Small change: update '(eip3651, eip3855, eip3860).py' to use the Shanghai fork name solely as opposed to using EIP numbers. 'withdrawals.py' already adheres to the latter.
eip3651 - is updated from 'merged' to 'shanghai' fork? @marioevz

Update Shanghai tests to use solely fork name instead of EIP numbers.

---

fillers/eips/eip3860.py

Currently if there is an initcode length violation for 'CREATE'/'CREATE2' the gas for the initcode execution is not deducted but stored. In the new spec change here -> https://github.com/ethereum/EIPs/pull/6249 the evm exceptionally aborts as if it runs out of gas. A small fix is added to achieve the latter.

fillers/eips/eip3860: Update EIP-3860 Due to Spec Change

---

fillers/withdrawals/withdrawals.py
setup.cfg
whitelist.txt

fillers/withdrawals/withdrawals: Update to use Gwei instead of Wei.

---

fillers/withdrawals/withdrawals.py

This splits the test `test_withdrawals_use_value_in_tx` into two. One is the invalid case when a withdrawal is used in the same block and the other is the invalid case when a withdrawal is used in the next block.
This makes the test comply with the requirement proposed in #41.

Split withdrawals test

---

src/ethereum_test_tools/spec/blockchain_test.py

Regarding https://github.com/ethereum/execution-spec-tests/issues/36
It looks like before RLP serialization for blocks:
the `Block` class (block) doesn't set withdrawals to the empty list `[ ]` for Shanghai, and instead this remains as a None type. This 
This PR contains one solution to the latter. As withdrawals are within the Environment class, and it is updated according to the fork type before RLP serialization:
we can use it instead, as the withdrawals None type here is set to the empty list `[ ]` within `set_fork_requirements`.

Fix rlp for blocks with no withdrawals.

---

README.md

Without those prompts users can just cut and paste all the commands, instead of doing it one by one.

feat(README.md): Remove prompts from commands

---

.github/workflows/test.yaml
README.md
docs/getting_started/01_quick_start.md
docs/getting_started/03_writing_tests.md
src/ethereum_test_filling_tool/main.py

Currently when adding a new test file, we are limited to having the tests within one sub-directory from `fillers` e.g `fillers/vm`. Tests within sub-directories deeper than that will not be found by the test filler `tf`.
This PR updates `tf` to search recursively when running from a top level directory i.e:
```console
tf --output="fixtures" --test-categories vm
```
hence tests within sub-directories of `vm` will be found, e.g `vm/vm_tests`.
Similarly it adds the extra option to only fill tests from a specific sub-directory i.e:
```console
tf --output="fixtures" --test-categories vm/vm_tests/vm_chain
```

Feature: Update `tf` to fill tests within subdirectories with depth > 1, change path defaults, add --no-structure option.

---

setup.cfg
src/evm_block_builder/__init__.py
tox.ini

Some small additions to the tox pipeline to check that files are in accordance with [PEP8](https://peps.python.org/pep-0008/).
1) To make sure file names are correctly named I have added a custom name checking package `fname8`: this checks that python file names are of the type `[a-z0-9_]`, for example `test_python.py` or `eip1897.py` would pass but `testPython.py` or `eip-1897.py` would fail.
2) As `flake8` doesn't report mixed-case function names, I have added `pep8-naming` which integrates directly with `flake8` as an extension. This also asserts that class/variable names are in accordance with PEP8.

Additional Tox Checks: pep8-naming and fname8 for correct python naming conventions

---

README.md
docs/getting_started/01_quick_start.md
src/ethereum_test_filling_tool/__init__.py
src/ethereum_test_filling_tool/filler.py
src/ethereum_test_filling_tool/main.py
src/ethereum_test_filling_tool/modules.py
whitelist.txt

This PR improves our run time of `tf` from ~15s to ~5s.
So far I've added an additional function called `parallel_fill` that is equivalent to `fill` but with concurrency, as well as a `--benchmark` CLI argument that logs the run time of `tf`.
To test for yourself you will need to edit `filler.fill()` in main and switch between `filler.parallel_fill()`. Using `tf --benchmark` to log the times.
`fill()`:
`parallel_fill()`:

Feature & Refactor: Add Concurrency and Filler Skips to Improve `tf` Effienciency. Additional CLI arguments.`

---

README.md
docs/getting_started/01_quick_start.md

To avoid confusion and errors when new users are getting started.

Update readme/docs for python versioning.

---

src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
src/evm_block_builder/__init__.py

This PR addresses the following issues: https://github.com/ethereum/execution-spec-tests/issues/76 and https://github.com/ethereum/execution-spec-tests/issues/64, where it certain fixture test cases were found to be missing withdrawals in their `genesisRLP`. The withdrawals list will now be appended to the end of the `genesisRLP` for all test cases `>= Shanghai`. 
```python
#Before: `many_withdrawals.json`
"genesisRLP": "0xf9021...363b421c0c0",
#Now:
"genesisRLP": "0xf9021...363b421c0c0c0",
```
A small refactor of specific functions within `state_test` and `blockchain_test` are added to help spot similar issues more quickly in the future.

Fixture Format: Append withdrawals list to the end of genesisRLP for >= Shanghai

---

src/ethereum_test_tools/common/types.py
src/evm_transition_tool/__init__.py

Zero padding shouldn't be in data field for fixture format -> https://github.com/ethereum/execution-spec-tests/issues/86

Fixture Format: Remove zero padding for data field in txs fixture format.

---

src/ethereum_test_tools/common/types.py

Adds the `excess_data_gas` to the environment requirements.

tools/common/types: fix fork requirements for 4844

---

src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/opcode.py

Makes `Op` opcodes callable and the resulting bytecode automatically sets the stack up.
If the opcode has data portion, the first argument is required and it becomes the data that is appended after the opcode.
The rest of the arguments are considered the stack, and they are appended before opcode byte, in LIFO order (the last argument is pushed first to the stack, and the first argument is pushed last).
E.g.
```python
Op.SSTORE(
-1,
Op.CALL(
Op.GAS,
Op.ADDRESS,
Op.PUSH1(0x20),
0,
0,
0x20,
0x1234,
),
),
```
In this example, the `Op.SSTORE` saves the result of the `Op.CALL` into the `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff` key of the storage, and the parameters of `Op.CALL` are pushed into the stack before its execution (`0x1234` is pushed first to the stack …

tools/vm: Enhance Callable Opcodes

---

src/ethereum_test_tools/common/types.py

Fixes some tests where there was a modification to the transactions/withdrawals after yield, by immediately converting to JSON on fixture initialization.

tools/types: Convert to JSON on fixture init

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py

Allow negative values in the storage, which are automatically converted to the EVM's two's complement of 32-byte.
Also add a check for an ambiguous storage check, i.e., the tester defined the equivalent EVM value as negative and positive numbers, and throw an exception.

tools/types: Correctly handle negative numbers in storage

---

fillers/eips/eip3651.py
fillers/eips/eip3855.py
fillers/eips/eip3860.py
fillers/vm/chain_id.py
fillers/withdrawals/withdrawals.py

A small refactor of some filler modules, using the new callable opcodes provided in https://github.com/ethereum/execution-spec-tests/pull/102.

fillers: Replace simple Yul with Callable Opcodes

---

fillers/withdrawals/withdrawals.py

Adds a simple check to verify behavior on untouched accounts when a zero-amount withdraw happens.
This behavior is not specified on https://eips.ethereum.org/EIPS/eip-4895

fillers/withdrawals: Add untouched accounts on zero-amount withdrawals

---

src/ethereum_test_tools/common/types.py

Previous PR merged changes the fixture format of transactions in the `newly_created_contract` withdrawals test case. The `tx["to"]` field should be present in fixture even set to `None`. The PR makes sure that `tx["to"] = ""` if its set to 'None' in a test case.

tools/types: Assert tx[to] always within fixtures.

---

fillers/eips/eip3651.py

fillers: update gas usage for subcalls in warm coinbase tests fixes #118

---

README.md
docs/getting_started/quick_start.md

Address incorrect docs/readme command line arguments. Add new CLI arguments to docs/readme. https://github.com/ethereum/execution-spec-tests/issues/120

docs/readme: Update with new flags.

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/opcode.py
whitelist.txt

- The dict type needed as input to instantiate a the Storage class is now properly defined and can be used in tests
- Forks and opcodes display proper names when printed, which will be useful when using pytest parametrize

tools: Types fixes

---

src/ethereum_test_tools/common/types.py

Adds a tiny change that addresses the inconsistency between the block RLP and tx field data field.
Flagged by retesteth: http://retesteth.ethdevops.io/results/log//2023-04-27-1682591043-dretesteth.txt

src/eth_test_tools/common/types: Remove even padding on tx data field

---

src/ethereum_test_tools/common/types.py

fix typo `parentTimstamp` -> `parentTimestamp`

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_fixtures/blockchain_london_invalid_filled.json
src/ethereum_test_tools/tests/test_fixtures/blockchain_london_valid_filled.json
src/ethereum_test_tools/tests/test_fixtures/chainid_istanbul_filled.json
src/ethereum_test_tools/tests/test_fixtures/chainid_london_filled.json

Keep the `protected` field in the transactions. This field might be important for signing transactions with the right signing hash.

keep `protected` field in transactions

---

src/evm_block_builder/__init__.py
src/evm_transition_tool/__init__.py
src/evm_transition_tool/tests/test_evaluate.py

As of 82533148769e566af0a58b1b66be2ccccc4e28a9, if the `--evm-bin` flag is used (`fill --evm-bin=/usr/bin/evm`), the `fill` command gave the following error:
```python
self = <evm_block_builder.EvmBlockBuilder object at 0x7fcaa9f9b3a0>, binary = '/usr/bin/evm'
def __init__(self, binary: Optional[Path] = None):
if binary is None:
which_path = which("evm")
if which_path is not None:
binary = Path(which_path)
>       if binary is None or not binary.exists():
E       AttributeError: 'str' object has no attribute 'exists'
```
As the command-line option is saved as type str.
This PR addresses the issue by allowing the constructor argument to be one of [None, str, Path] and adds a test for it.

fix: evm bin command line option

---

.github/workflows/test.yaml
README.md
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/yul.py
src/ethereum_test_tools/tests/test_code.py
src/ethereum_test_tools/tests/test_filler.py
src/pytest_plugins/test_filler/test_filler.py
tests/eips/eip4844/test_blobhash_opcode_contexts.py
tests/eips/eip4844/util_blobhash.py
tests/eips/test_eip3855.py
tests/example/test_yul_example.py
tests/security/test_selfdestruct_balance_bug.py
tests/withdrawals/test_withdrawals.py

This PR:
Note, after changing the behavior so that Yul gets compiled with the test's current fork parameter value: `tests/security/test_selfdestruct_balance_bug.py` fails if compiled with Constantinople or Shanghai. Shanghai can be explained: This is just because `solc` refuses to compile contracts with SELFDESTRUCT. I didn't understand why the code doesn't compile for Constantinople yet. We don't need to fix this in the scope of this PR, imo, but we should make a ticket to not forget. This is currently avoided by applying `@pytest.mark.compile_yul_with("Merge")`.

feature: specify the target evm version to solc for yul compilation

---

mkdocs.yml
setup.cfg

This PR cherry picks 2 useful commits from #143 that I'd like to fast track. In particular, the docstring commit would be useful to start experimenting with better generated doc.
1. Updates pytest and pytest plugins in order to fix this issue with pytest-cov plugin:
```
========================================================================== warnings summary ==========================================================================
src/pytest_plugins/forks/tests/test_forks.py::test_from_london_option_no_validity_marker[London]
src/pytest_plugins/forks/tests/test_forks.py::test_no_options_no_validity_marker
src/pytest_plugins/forks/tests/test_forks.py::test_from_london_option_no_validity_marker[Merge]
src/pytest_plugins/forks/tests/test_forks.py::test_from_london_until_shanghai_option_no_ …
```

chore: fix pytest warnings and specify docstring style

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
tests/eips/eip4844/README.md
tests/eips/eip4844/test_blob_txs.py
tests/eips/eip4844/test_blobhash_opcode.py
tests/eips/eip4844/test_blobhash_opcode_contexts.py
tests/eips/eip4844/test_excess_data_gas.py
tests/eips/eip4844/test_excess_data_gas_fork_transition.py
tests/eips/eip4844/test_point_evaluation_precompile.py
tests/eips/eip4844/test_point_evaluation_precompile_gas.py
tests/eips/eip4844/utils.py
whitelist.txt

Addresses the following spec changes:

tests/4844: `excessDataGas` and `dataGasUsed` spec update

---

src/ethereum_test_tools/code/yul.py
tests/example/test_yul_example.py

We have to additionally map the `ConstantinopleFix` fork to "constantinople" when setting the target evm version for solc (`solc --evm-version FORK`.
Additionally, update the yul example to run from Homestead. Frontier is not supported by solc.

tools: fix solc compilation for the ConstantinopleFix fork

---

pytest.ini
src/ethereum_test_tools/reference_spec/git_reference_spec.py
src/ethereum_test_tools/reference_spec/reference_spec.py
src/pytest_plugins/spec_version_checker/spec_version_checker.py
src/pytest_plugins/test_filler/test_filler.py
whitelist.txt

This PR:
- Gets the `spec_version_checker` plugin ready for the test folder restructure.
- Implements the version checks as tests instead of issuing warnings. A new test is dynamically added by the plugin for each test module whose path matches `eip\d{1,4}` that checks that the reference spec defined in the module is up-to-date with ethereum/EIPs.
These tests as-is are currently always ran. We might have to be careful that our (especially our CI/CD) Github API access doesn't get rate limited :slightly_smiling_face: 
Only run the EIP version check tests:
```console
pytest -m eip_version_check
```
Run all tests except the version check tests:
```console
pytest -m "not eip_version_check"
```

Pytest plugins: Implement EIP reference version checking as dynamic tests

---

pytest.ini
tox.ini

This PR:
1. Renames the tox environment "py3" to "framework".
2. Adds an environment "py3" which is an alias for "framework".
3. Adds a new environment docs. The duplicated doc checks have been moved from the framework and test environments to the docs environment.
4. Adds `--dist loadscope` to pytest.ini - this fixes #159.
Running `tox` is now essentially equivalent to running `tox -e framework; tox -e tests; tox -e docs`.
Assuming the tox venvs have already been created, these changes speed-up execution of `tox` on my 16 core laptop from 60s to 33s. More targeted checks (e.g. docs only via `tox -e docs`) can also now be manually executed. The main speed-up comes from using xdist when executing pytest on the "tests" directory.

chore: speed up tox execution

---

setup.cfg
tox.ini

This PR proposes to move `xdist` to the main requires list in the setup.
Reasoning being that the `--dist` option is now included by default in the `pystest.ini` and usually users (in my opinion) would like to do:
```bash
pip install -e .
```
and then run `fill` command, which is no longer possible.
Granted that the `README.md` correctly states that the correct install command is `pip install -e .[docs,lint,test]`, but even so, I think all the tools necessary to fill the tests should be installed with `pip install .`.

chore: move xdist to the main install requires

---

src/pytest_plugins/test_filler/test_filler.py

:heavy_plus_sign: This PR simply adds the `--no-output-structure` flag to the `fill` (`pytest`) command
It has the equivalent function to the deprecated `tf --no-ouput-structure` previously added here -> https://github.com/ethereum/execution-spec-tests/pull/66

Add --no-output-structure flag to pytest :snake: 

---

.github/workflows/docs_main.yaml
.github/workflows/docs_tags.yaml

Previously 3.11 was specified.

chore: use python 3.10 in doc deploy workflows

---

.github/workflows/docs_main.yaml
.github/workflows/docs_tags.yaml

This PR makes 2 changes to our docs continuous deployment:
1. Use a github secret to get the a "deploy key" for repo checkout, so that we can later push to the protected `gh-pages` branch **See "additional required repo config" below**.
2. Don't run these actions on forks of execution-spec-tests.
**Additional required repo config** (taken from [stackoverflow](https://stackoverflow.com/a/76135647)):
1. Generate SSH key pair: No need for passphrases etc:
```
ssh-keygen -t ed25519 -C github-actions-deploy-key@ethereum-$(date -I) -f id_ed25519_github_actions_deploy_key
```
3. Add public key (.pub one) as a deploy key at Your repo -> Settings -> Security -> Deploy keys, check "Allow write access".
4. Add private key as a secret (name: `GH_ACTIONS_DEPLOY_KEY`) at Your repo -> Settings -> …

chore: use a deploy key for gh actions to push to protected branch & don't run on forks

---

tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Removes an unnecessary Yul snippet from one of the withdrawals tests.

tests/withdrawals: Remove Unnecessary Yul

---

tests/cancun/eip4844_blobs/common.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py

Adds tests where one or more blobs in one or more transactions contained in the serialized version of the block is in its full blob (network) version.
Adds three tests:
- A block with a single transaction with a single blob in full blob form
- A block with multiple transactions with the first transaction having full blob form
- A block with multiple transactions with the last transaction having full blob form

tests/4844: Add blob network type in block test

---

.pre-commit-config.yaml
docs/dev/index.md
docs/dev/precommit.md

Adds a [pre-commit](https://pre-commit.com/) config file in the repository root (`.pre-commit-config.yaml`) that can be used to enable automatic checks upon commit - the commit will not go through if the checks don't pass.
To enable pre-commit, the following must be ran once:
```console
pip install pre-commit
pre-commit install
```
Enabling of pre-commit checks is not mandatory (it cannot be enforced) and even if it is enabled, it can always be bypassed with:
```console
git commit --no-verify
```
I'm sure we can tweak the hooks quite a bit as we get more experience and ideas, but we can leave it as this for now.

chore: add a pre-commit config

---

tests/cancun/eip4844_blobs/test_blobhash_opcode.py
tests/cancun/eip4844_blobs/test_blobhash_opcode_contexts.py

There are a number of tests that vary across transaction types.  Besu's t8n tool is sensitive to unsupported fields in some tx types and requires a value for other fields in those types.
This PR makes sure all required and no unsupported fields are in each TX type for cancun blob tx tests.

Add correct fields to tx types

---

src/pytest_plugins/forks/forks.py

1. Fixes #201.
2. Improves reporting for the case when the intersection between a test's validity range and the specified fork range (on the command-line or default) is empty:
1. If `-vv` is specified (`config.getoption("verbose") >= 2`) then report each test with the reason why it was skipped in the pytest execution output.
2. If `config.getoption("verbose") >= 2`, use the previous behaviour, report that tests were skipped in the collection summary at the beginning of the test run, but don't report each test explicitly in the execution output.

pytest: remove excessively restrictive unsupported fork check

---

src/evm_transition_tool/__init__.py
src/evm_transition_tool/evmone.py
src/evm_transition_tool/execution_specs.py
src/evm_transition_tool/geth.py

Brings back support of using `ethereum-spec-evm` transition tool to fill tests.

evm_transition_tool: Add execution-specs, `ethereum-spec-evm`

---

src/ethereum_test_tools/code/code.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/opcode.py

- Add `len` to the `Code` class
- Allow `Opcode`'s data portion or stack elements to be hex strings
- Adds a counter to the storage type, which allows to automatically store a value to the next slot in an internal counter, and return the slot number.
Tests can now use the following pattern:
```
bytecode = Op.SSTORE(storage.store_next(expected_value), Op.CALLDATALOAD(0))
bytecode += Op.SSTORE(storage.store_next(expected_value_2), Op.CALLDATALOAD(1))
```
And `storage` will keep track of the next storage slot to use, keeping code clean, and preventing overwriting a verification value in a loop for example.

tools: Fixes, Improvements to Opcodes/Code/Types

---

src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/spec/__init__.py
src/ethereum_test_tools/spec/base_test.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
src/pytest_plugins/test_filler/test_filler.py

Adds a flag that removes all hive related properties from the output fixtures.
At the moment it only removes the Engine API directive instructions.
~Requires #207, hence draft.~ Rebased and removed dependency.

Add `disable-hive` flag

---

README.md
docs/getting_started/quick_start.md

zsh does not like the `[` character so wrap it with `''`.

readme: fix pip install command

---

tests/cancun/eip4844_blobs/test_blobhash_opcode.py

The `test_blobhash_opcode.py::test_blobhash_gas_cost` should not set `max_fee_per_gas` for transaction type 0 and 1.
Fixes https://github.com/ethereum/execution-spec-tests/issues/220.

tests/cancun/eip4844_blobs: fix tx max_fee_per_gas

---

docs/getting_started/executing_tests_command_line.md
src/pytest_plugins/test_filler/test_filler.py
src/pytest_plugins/test_help/test_help.py

Whilst reviewing #210 I noticed that the output of `fill --test-help` was misleading for `--disable-hive` (and all other `store_true`/`store_false` arguments) as it suggested that it took an argument:
This PR fixes that:

Chore: Fix `fill --test-help` formatting for store true/false arguments

---

.vscode/launch.recommended.json

Add configs to `.vscode/launch.recommended.json` that assist debugging test cases with an interactive choice of an evm binary and test path.

chore: add helpful vscode launch configs

---

src/ethereum_test_tools/spec/base_test.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
src/evm_transition_tool/evmone.py
src/evm_transition_tool/geth.py
src/evm_transition_tool/tests/test_evaluate.py
src/evm_transition_tool/transition_tool.py
src/pytest_plugins/test_filler/test_filler.py

Adds flag `--transition-tool-debug-dump-path` which can be used to specify a path where debugging information for all transition tool invocations will be dumped.
For example:
```
fill ./tests/frontier/opcodes/test_dup.py  --transition-tool-debug-dump-path=./tmp/
```
Will result in the following folders:
```
test_dup_fork_Berlin             test_dup_fork_Frontier   test_dup_fork_Merge
test_dup_fork_Byzantium          test_dup_fork_Homestead  test_dup_fork_Shanghai
...
```
inside `./tmp/`, and inside each folder there will be several numbered subfolders with all the information about each call to the transition tool.
@shemnon @chfast let me know if this is helpful and whether you have any suggestions!

feature: Add flag to dump debug t8n information

---

docs/getting_started/executing_tests_command_line.md
src/evm_transition_tool/besu.py
src/pytest_plugins/test_help/test_help.py

Adds support for besu to support `--t8n-dump-dir` to dump debug information, cf #219.

evm_transition_tool: Fix besu debug dump

---

src/ethereum_test_tools/common/json.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py

- Replaces the fragile dictionary mixing method to collect the header fields with a method based on field metadata, and now each header field contains metadata with the following information:
- Method used to determine requirement based on block number, timestamp and fork configuration
- Field source from: Current test environment, or transition tool (t8n) result dictionary
- Default value if field is required but no value was provided by either the test environment or the transition tool result
Open questions:
Should we throw an exception if the t8n tool did not provide us the sufficient information to create the block?
At the moment we provide defaults for the 4844 fields, but for 4788 the beacon block root contained in the header will actually modify the state root, and therefore we …

feature: Add block header field metadata

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py

Updates `class FixtureEngineNewPayload` to match names in https://github.com/ethereum/execution-apis/blob/main/src/engine/cancun.md, ~so we can basically:~
1) ~Read the fixture json~
2) ~Remove `version` and `error_code` (while keeping its values to use it ourselves)~
3) ~Forward it to the Engine API using the appropriate `engine_newPayload` version~
~@spencer-tb this should simplify pyspec hive simulator further.~
We can't do any of that because `engine_newPayloadVN` contains positional parameters, it doesn't receive the parameters as a big dictionary as I was imagining.

types: fix `FixtureEngineNewPayload` json field names

---

src/ethereum_test_tools/common/types.py

Renames the JSON output field name of the beacon root to match https://github.com/ethereum/execution-apis/pull/450

types: Rename JSON output to `parentBeaconBlockRoot`

---

tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py
tests/cancun/eip4844_blobs/test_blobhash_opcode.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile_gas.py
tests/cancun/eip5656_mcopy/test_mcopy.py
tests/cancun/eip5656_mcopy/test_mcopy_contexts.py
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct.py

Removes the necessary pre-alloc balance at the EIP-4788 pre-compile address.
Tested using https://github.com/ethereum/go-ethereum/pull/27289/commits/2ce4c013b6c28b6ee9bee36e11de38e2a7b7536b and works perfectly.
This will remain a draft until the EIP PR is decided to be included the main branch: https://github.com/ethereum/EIPs/pull/7431

tests: Remove start alloc balance to beacon root precompile

---

tests/cancun/eip4844_blobs/test_blob_txs.py

Temporarily skip the `test_invalid_blob_tx_contract_creation` due to the following issue: #242 
We can re-add the test once the issue is resolved.

tests/eip4844: Skip invalid blob tx to address test case

---

src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/generators.py
src/ethereum_test_tools/tests/test_code.py

Implements a conditional code generator, to skip using Yul in these cases.
It uses a combination of the `PC`, `JUMP` and `JUMPI` opcodes, but in the future these could be replaced by `RJUMP` and `RJUMPI`.

tools/code: Add conditional bytecode generator

---

tests/cancun/eip4844_blobs/test_blob_txs_full.py

Fixes the expected error on the full blob block tests.
It was missing because none of the transactions actually fail when sent to the transition tool: they are all being sent in the correct format and only modified when put in the final block.
Thanks @jochem-brouwer for finding and raising this issue!

tests/4844: Fix Block Expected Error on Full Blob Tests

---

tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py

Adds the appropriate Engine API error codes for invalid tests during fixtures generation. 
Hive will parse this field and match the error code response during the pyspec simulation.

tests/cancun/eip4844_blobs: Add Engine API error codes to invalid tests.

---

src/pytest_plugins/test_filler/test_filler.py

Fixes an oversight that BlockchainTest did not dump the t8n output as StateTest do.

filler: Fix dump t8n on blockchain tests

---

src/entry_points/create_whitelist_for_flake8_spelling.py

Currently, the resulting flake8 wordlist contains the last word and the first word of the next file merged together because some of the files do not have a new line at the end.
This fix appends a new line at the end of each file.

entrypoints: Add new line at the end of each file when merging word lists

---

tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py

Further addition to the previous PR here -> https://github.com/ethereum/execution-spec-tests/pull/248
Fixes `test_blob_type_tx_pre_fork` test in hive.

tests/cancun/eip4844_blobs: Update Engine API error codes for invalid tests.

---

src/ethereum_test_forks/base_decorators.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_forks/transition_base_fork.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
src/ethereum_test_tools/tests/test_types.py
src/evm_transition_tool/transition_tool.py
tests/cancun/eip4788_beacon_root/common.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
tests/cancun/eip4788_beacon_root/test_blocks_beacon_root_contract.py

Updates EIP-4788 tests to use a pre-deployed bytecode instead of the regular pre-compile.
A new `pre_allocation` method is added to the base fork abstract class, which specifies a pre-allocation that must be performed for a given fork.
This method also has a new decorator `prefer_transition_to_method`, which marks the method so the `to-fork` implementation of the method takes priority when the method is evaluated.
This is necessary because the pre-allocation cannot be modified at fork transition, so it needs to be present in the genesis if we are transitioning to the given fork that requires this allocation. E.g. Shanghai->Cancun transition fork needs the Cancun pre-allocation of the beacon root bytecode pre-deploy.
- `DELEGATECALL` and `CODECALL` no longer work as previously because the …

tests/cancun/eip4788: Update to use pre-deployed contract

---

.wordlist_opcodes.txt
.wordlist_python_pytest.txt
src/ethereum_test_forks/__init__.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_forks/transition_base_fork.py
src/pytest_plugins/forks/forks.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Forks now have `tx_types` and `precompiles` methods, which must return all valid transaction types and enabled precompiles in the given fork.
Introduce covariant parameter markers, which allow to parametrize a test with all valid values for a given property on a given fork.
- `@pytest.mark.with_all_tx_types`
- `@pytest.mark.with_all_precompiles`
E.g. using `@pytest.mark.with_all_tx_types` the tester can now specify that the test must be parametrized on each fork with all the valid transaction type numbers as a parameter at that specific fork, (Shanghai: `[0, 1, 2]`, Cancun: `[0, 1, 2, 3]`), and eventually, on future forks, it should be parametrized using newer transaction types.

pytest: Parametrize fork covariant parameters

---

src/evm_transition_tool/transition_tool.py

Small fix to properly write the T8N dumps if the content is simply a `str` type.

evm_transition_tool: Fix t8n dump on `str` types

---

.wordlist_python_pytest.txt
src/evm_transition_tool/transition_tool.py

Requires https://github.com/ethereum/execution-spec-tests/pull/229.
Adds an executable script to each subdir in the `--t8n-dump-dir` in order to reasily rerun t8n tool executions performed during the test run in isolation.
E.g.
```
fill --fork=Shanghai --traces --t8n-dump-dir=/tmp/geth-t8n
```
results in:
and then:
```
/tmp/geth-t8n/test_yul_fork_Shanghai/2/t8n.sh
```
reruns the t8n command ran for the test and outputs:
```
INFO [08-18|15:52:41.232] Trie dumping started                     root=91d0a9..9fd44b
INFO [08-18|15:52:41.232] Trie dumping complete                    accounts=3 elapsed="162.897µs"
INFO [08-18|15:52:41.232] Wrote file                               file=/tmp/tmp32lqi24l/txs.rlp
{
"alloc": {
"0x1000000000000000000000000000000000000000": {
"code": …
```

Tools: add a t8n script to t8n dump dir to easily reproduce executed t8n tool commands

---

README.md
docs/getting_started/quick_start.md
whitelist.txt

Current work around for the following issue: #274 related to installing coincurve v17 on macOS with Python 3.11.

docs: add extra installation step for macOS when using Python >=3.11

---

.github/workflows/test.yaml
src/ethereum_test_tools/reference_spec/git_reference_spec.py
src/ethereum_test_tools/tests/test_reference_spec.py

Additionally run github actions on macos-latest. Previously, it was only ubuntu-latest.
To help detect issues such as #274.

chore: run github actions on macos

---

setup.cfg
src/ethereum_test_tools/code/yul.py
src/ethereum_test_tools/tests/conftest.py
src/ethereum_test_tools/tests/test_code.py
src/ethereum_test_tools/tests/test_filler.py
src/ethereum_test_tools/tests/test_fixtures/blockchain_london_invalid_filled.json
src/ethereum_test_tools/tests/test_fixtures/blockchain_london_valid_filled.json

Following this discord thread -> [here](https://discord.com/channels/595666850260713488/753271902520213625/1145736190356623466).
When using a development version of solidity we hard fail like the following:
```
Version: 0.8.20-develop.2023.5.1+commit.0cb27949.Darwin.appleclang
```
This commit allows the latter.

Update Solc Version Check To Use SemVer

---

src/evm_transition_tool/execution_specs.py

As execution-specs is installed as one of our dependencies, using its transition tool works out of the box (after installing execution-spec-tests):
```
fill --evm-bin=ethereum-spec-evm
```
Note: Not working out of the box until https://github.com/ethereum/execution-specs/pull/823 is merged :laughing: (use that branch if you want to test).

docs: update execution-specs t8n installation help

---

src/ethereum_test_tools/code/generators.py
src/ethereum_test_tools/tests/test_code.py

Add an optional executable bytecode prefix to the `Initcode` class, which will be prepended to the initcode and executed on contract creation.

tools: Add optional prefix to `Initcode`

---

tests/cancun/eip4788_beacon_root/common.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
tests/cancun/eip4788_beacon_root/test_blocks_beacon_root_contract.py

Updates all references to a beacon root precompile to a beacon root contract.

Change naming beacon root precompile to contract

---

tests/cancun/eip4788_beacon_root/test_blocks_beacon_root_contract.py

Adds a simple test where the expected beacon root contract is not present in the state before the Cancun fork, and verify that the storage for this address is not updated, nor that the calls performed to it return any value, nor that the client reaches an exception or error.
~~Requires #283~~ Merged.

tests/cancun: Add test scenario where the beacon root contract is missing

---

tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py

This adds two test cases based on a go-ethereum implementation mistake that was caught in [PR review](https://github.com/ethereum/go-ethereum/pull/27189#discussion_r1255491667):
given contract A which has methods to receive balance (a no-op) and selfdestruct, and was created in current tx.
Test the following call sequence in the same transaction:
Transfer value to A and call A.selfdestruct.  Recurse into a new call which transfers value to A, calls A.selfdestruct, and reverts.
I have add two variants of this scenario: one test where `A` is pre-existing and another where it is created in the same transaction that the test occurs in.

tests/cancun/eip6780: add test cases which use revert

---

src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/generators.py
src/ethereum_test_tools/tests/test_code.py
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py

Adds a `Switch` bytecode class that implements switch case behaviour. It should help make the transient storage reentrancy tests more readable; see the refactored test case in 0045bf80ec446ceaf14ff12f41edfbf9d91a8f56 which performs two reentrant calls. It might be clearer to use `Switch` instead of `Conditional` in the other reentrancy test cases, too.
Example from test code:
https://github.com/ethereum/execution-spec-tests/blob/253eb361ac786cadb85b0658bd880b6d6769babd/src/ethereum_test_tools/tests/test_code.py#L318-L331

framework: add switch-case construct for conditional bytecode evaluation

---

src/ethereum_test_tools/common/types.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4788_beacon_root/test_blocks_beacon_root_contract.py
tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Following the future improvement to deprecate empty accounts -> [here](https://notes.ethereum.org/@RG8j1GXNQ-iPkkFqXEouVA/By-ep0ry6), an assertion check has been added to detect empty accounts within the pre and post allocation within tests.
Note that an empty account is one which has zero nonce, code, balance and an empty storage:
``` 
"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
"nonce": "0x00",
"balance": "0x00",
"code": "0x",
"storage": {}
}
```
The beacon root tests have been updated to account for the latter (due to the inclusion of the system address), alongside a few withdrawals tests.

improvement: Deprecate empty accounts within framework.

---

src/ethereum_test_tools/vm/opcode.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip7516_blobgasfee/__init__.py
tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py
whitelist.txt

Simple addition to the 4844 tests to verify EIP-7516 alongside it.
~~Since this is not approved for Devnet-9 we should hold-off merging.~~
eip-7516 links:
- [eips.ethereum.org/EIPS/eip-7516](https://eips.ethereum.org/EIPS/eip-7516)
- [ethereum-magicians.org](https://ethereum-magicians.org/t/eip-7516-blobbasefee-opcode/15761) 
t8n tool version: https://github.com/marioevz/go-ethereum/commit/f4ea54d5bef1e9a0516bbcc64dfd3559d4e9139a

tests/4844: Add EIP-7516, BLOBBASEFEE, verification to excess blob gas tests

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/filling/fill.py
src/ethereum_test_tools/spec/base_test.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
whitelist.txt

Similar to the following PR: #183 but for engine API forkchoice updated payload attriubes & version.
This information can be extracted and utilized in hive. Tagging https://github.com/ethereum/hive/pull/830.

feature: Add engine API forkchoice updated information in fixtures

---

.github/actions/build-evm/action.yaml
.github/actions/build-geth-evm/action.yaml
.github/workflows/test.yaml
evm-config.yaml
tox.ini

Adds a `evm-config.yaml` file which contains a list of possible build configurations for geth's evm binary.
- Main: Runs stable forks using ethereum/go-ethereum@master
- Develop: Runs development forks using marioevz/go-ethereum@cancun-t8n

feature: Run development fork tests on github actions

---

docs/CHANGELOG.md
tests/cancun/eip4844_blobs/test_blob_txs.py

`engine_newPayloadV2` should return `INVALID` for the case where blob txs (type 3 txs) exist in the txs rlp.

tests/cancun/eip_4844: Fix invalid blob tx pre cancun tests.

---

evm-config.yaml

Rollback geth branch to `cancun-t8n` since now the change will be in Devnet-9

evm: Rollback geth branch to `cancun-t8n`

---

.github/workflows/test.yaml
README.md
docs/CHANGELOG.md
docs/getting_started/quick_start.md
setup.cfg
src/ethereum_test_tools/common/conversions.py
src/evm_transition_tool/besu.py
tests/cancun/eip4844_blobs/common.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py

- Adds Python 3.12 support.
- 3.12 tested (currently pre-release) in Github Actions.
- Upgrades flake8.
Tested with 3.12.0rc3 built via pyenv.
The same version of flake8 (6.0.0) produced more warnings on Python 3.12 vs 3.10/3.11 (so these are fixed). But, since our flake8 version requirement in setup.cfg didn't make any sense (`flake8>=5,<=6`, note the `<=6`), I bumped this version to ensure we use patches/improvements in v6. Practically as of now, it means we'll use 6.1.0 instead of 6.0.0.

chore: add python 3.12 support

---

README.md
docs/CHANGELOG.md
docs/index.md
src/evm_transition_tool/transition_tool.py

https://github.com/ethereum/execution-specs/pull/828 implements full tracing for `ethereum-spec-evm`. This PR simply removes the exception so that tracing with the execution-specs t8n tool can be enabled within execution-spec-tests.
We should hold off merging this PR until https://github.com/ethereum/execution-specs/pull/828 is merged.

feat(evm): enable tracing support for ethereum-spec-evm

---

src/evm_transition_tool/evmone.py
src/evm_transition_tool/transition_tool.py
whitelist.txt

- Moves the `evaluate()` method from the evmone interface (which receives its input and outputs from the filesytem instead of stdin/stdout) to the base class so that it can be re-used by other transition tools.
- Adds a new attribute `t8n_use_stream` to the base class with a default value of `False`, so that other `t8n` tools still use stdin/stdout.

move evmone evaluate into t8n base class (stdin and filesystem versions of t8n interaction)

---

docs/CHANGELOG.md
src/ethereum_test_forks/__init__.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/helpers.py
src/ethereum_test_forks/tests/test_forks.py
tests/berlin/eip2930_access_list/test_acl.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
tests/shanghai/eip3651_warm_coinbase/test_warm_coinbase.py
whitelist.txt

Implements the following operators for the fork objects:
- Greater than (>): Fork is newer than other fork
- Greater than or equal to (>=): Fork is at least as newer than other fork
- Less than (<): Fork is older than other fork
- Less than or equal to (<=): Fork is at least as old than other fork
`is_fork` is now removed.
None

forks: Implement fork operators, remove `is_fork`

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/forks/transition.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_forks/transition_base_fork.py
src/ethereum_test_tools/code/yul.py
src/ethereum_test_tools/spec/blockchain_test.py
src/ethereum_test_tools/spec/state_test.py
src/evm_transition_tool/besu.py
src/evm_transition_tool/geth.py
src/evm_transition_tool/nimbus.py
src/evm_transition_tool/tests/test_evaluate.py
src/evm_transition_tool/transition_tool.py

Introduces fork-specific variables that are not inherited by subclass forks, containing the following variables:
- `transition_tool_name`: The name that the transition tool (`evm t8n`) expects for this fork.
- `blockchain_test_network_name`: The `network` value that must be included in the `BlockchainTest` fixture format for this fork.
- `solc_name`: The name that the solidity compiler (`solc`) expects for this fork.
This is very useful to name forks differently than the transition tool actually expects (e.g. when we rename `Merge` to `Paris`, the transition tool will still expect `Merge` as the fork to execute the tests).
This was achieved by using the `__init_subclass__` special method in the `BaseFork` class, with the class variables as parameters, and then, when defining the fork …

forks: Add fork-specific, non-inherited class variables

---

docs/CHANGELOG.md
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py

Storage iterator was broken, so a for loop could not iterate over it (it returned a zero key even if it didn't have the zero key).
Fix was to return the iterator of the `data` field.
None

tools(fix): Storage iterator

---

docs/CHANGELOG.md
tests/cancun/eip6780_selfdestruct/test_reentrancy_selfdestruct_revert.py

Test requested by chfast about suicide reentrancy and revert.
Resolves this [issue](https://github.com/ethereum/tests/issues/1325).

feat(tests): add reentrancy suicide revert test

---

docs/CHANGELOG.md
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile_gas.py
tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py
tests/shanghai/eip3860_initcode/test_initcode.py
whitelist.txt

- Converts the following tests to StateTest:
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile_gas.py::test_point_evaluation_precompile_gas_usage
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_valid_precompile_calls
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_invalid_precompile_calls
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_point_evaluation_precompile_external_vectors
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_point_evaluation_precompile_calls
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_point_evaluation_precompile_gas_tx_to
- tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py::test_point_evaluation_precompile_before_fork
- …

feat/statetest: Convert most blockchain tests

---

docs/CHANGELOG.md
src/ethereum_test_tools/common/types.py
whitelist.txt

This PR makes the custom exception classes defined in  `ethereum_test_tools.common.types` as `kw_only` dataclasses.
The primary aim is to make it easier to test these exception classes; dataclasses automatically get a `__eq__()` method which can be used for comparison in tests. Applying `kw_only` also helps readability.
Should help improve PR #350 (respectively #380).

refactor(fw): make exception classes `kw_only` dataclasses to improve testability

---

docs/CHANGELOG.md
tests/frontier/opcodes/test_call_and_callcode_gas_calculation.py
whitelist.txt

Adds a new test to cover a bug that was discovered in the EthereumJS EVM implementation of the `CALLCODE` opcode where we were incorrectly applying the call stipend to the gas limit applied to the new call frame before evaluating the gas consumed by the call frame so would incorrectly continue execution of the CALLCODE call frame instead of going OOG.
Covers the scenario described in [this issue](https://github.com/ethereumjs/ethereumjs-monorepo/issues/3194).

feat(tests): callcode gas test when call stipend is applied to gas limit

---

src/ethereum_test_tools/tests/test_filling/test_expect.py

Remove the `run_post_state_mismatch_test` helper function and re-write using fixtures. Having an `if` to handle the exception/no-exception cases both in the helper function and the tests themselves made the tests harder to understand.
PR to #350.
Checklist handled in #350.

refactor: make post state verification tests more pytesty

---

src/ethereum_test_tools/spec/state/types.py
src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_state_test.json
src/ethereum_test_tools/tests/test_filling/fixtures/chainid_shanghai_state_test.json

do not print previousHash field in generated state tests
as it is a legacy field that has no meaning and we never use it

fix(tools): remove `previousHash` from state test `env`

---

docs/consuming_tests/blockchain_test.md

Updated the section on Blockchain Tests consumption with more details.

docs: update blockchain test consumption section

---

docs/CHANGELOG.md
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_forks/transition_base_fork.py
src/ethereum_test_tools/spec/state/state_test.py

Fix state test generated using transition forks, so the transition fork is not named in the output fixture, but the actual Fork that should be enabled according to the state test's block number and timestamp.
Fixes #405

fix(forks,fw): Fix transition forks on state tests

---

docs/CHANGELOG.md
tests/cancun/eip4844_blobs/test_blob_txs.py

Adds parameterized tests to ensure that the blob gas fee is subtracted from the sender's balance before a blob transaction is executed. Includes the case where the sender recieves funds before the blob tx is executed.
As requested by @marioevz: https://github.com/ethereum/execution-spec-tests/issues/385

feat(tests): Add blob gas subtraction order tests

---

.github/workflows/test.yaml
.pre-commit-config.yaml
docs/CHANGELOG.md
docs/writing_tests/verifying_changes.md
tox.ini

1. Run `tox` with `run-parallel` in Github Actions and pre-commit.
2. Configure `tox.ini` to use a shared wheel across testenvs instead of individually installing test-filler as a source distribution.
Tricks found in this article https://hynek.me/articles/turbo-charge-tox/.
The speed-up mainly comes from running the `docs` tox `env` in parallel to the `test` env (so you'll never save more time than `docs` takes) - not sure how much of a tangible impact this will have on Github Actions.
But adding `run-parallel` to tox is certainly worthwhile locally. This must be done manually (or via pre-commit).
| Change | Changes in `./src/` | No changes in ./src/ |
|--------| -------------------|----------------------|
| No changes | 1m 7s | 1m 10s |
| tox run-parallel | 40s | 42s |
| Re-use wheel …

ci (feature): use `run-parallel` and shared wheel packages for tox

---

docs/CHANGELOG.md
whitelist.txt

~~Updates the changelog for the bug fix release v2.0.1.~~
Updates the changelog for the bug fix release v2.1.0.

docs: Update changelog for v2.1.0 release

---

.vscode/extensions.json
.vscode/settings.recommended.json
docs/CHANGELOG.md

Removes deprecated settings from our recommended VS Code settings and adds the microsoft mypy extension. This change is necessary since (from the log):
```
Linting features have been moved to separate linter extensions.
```
More info: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
Fixes #344.

chore: fix deprecated vs code settings #344

---

docs/CHANGELOG.md
src/ethereum_test_forks/__init__.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/helpers.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_forks/transition_base_fork.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/yul.py
src/ethereum_test_tools/tests/conftest.py
src/ethereum_test_tools/tests/test_code.py
src/pytest_plugins/test_filler/test_filler.py

1. Fixes `fill -m yul_test` which failed to filter tests that were (dynamically) marked as a yul test.
2. Defines which forks our supported solc versions can use as an argument to `--evm-version`.
3. Uses the definition from 2. to better pick an argument to `--evm-version` if the current fork is not supported.
4. Exit `fill` early in case of raising an incompatible solc. Previously this would return an error for every collected test:
```
✦ ➜ fill tests --solc-bin ~/bin/solc-0.8.19
Exit: Unsupported solc version: 0.8.19+commit.7dd6d404.Linux.gpp. Minimum required version is 0.8.20
```
Opened as draft, remaining to do:
Won't add pytest framework tests for `pytest_plugins.test_filler`. Would be nice, but we currently don't currently manage available solc versions, so results are undefined. …

bug(pytest, forks): fix `yul_test` marker and improve `solc --evm-version` param handling

---

docs/CHANGELOG.md
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/tests/test_forks.py
tests/cancun/__init__.py
tests/prague/__init__.py
whitelist.txt

1. Adds the Prague fork and an empty tests folder.
Note, does not yet bump Cancun to deployed.
None.

feat(forks,tests): add prague fork and test folder

---

docs/CHANGELOG.md
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/blockchain/blockchain_test.py
src/ethereum_test_tools/spec/state/state_test.py

Fixes empty account check, and fixes account merging so that empty accounts are removed.
https://github.com/ethereum/execution-specs/pull/871

bug(fw): fix account empty code check

---

src/pytest_plugins/test_filler/test_filler.py

This PR fixes an error introduced in #418: `src/pytest_plugins/test_filler/test_filler.py` always issued a warning for an incorrect fork, regardless of whether `get_closest_fork_with_solc_support()` returned the requried fork, or not. For example,
```
fill tests/homestead/yul/test_yul_example.py --fork=Shanghai -v
```
with a solc that supports Shanghai incorrectly warns:
```
============================================= warnings summary ==============================================
tests/homestead/yul/test_yul_example.py::test_yul[fork_Shanghai-blockchain_test]
tests/homestead/yul/test_yul_example.py::test_yul[fork_Shanghai-blockchain_test_hive]
tests/homestead/yul/test_yul_example.py::test_yul[fork_Shanghai-state_test]
/home/dtopz/code/github/danceratopz/execution-spec-tests/src/pytest_p …
```

fix(pytest): actually check the fork before issuing a fork mismatch warning for yul compilation

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/transition_base_fork.py
src/ethereum_test_tools/tests/test_code.py
src/pytest_plugins/forks/forks.py

Fixes this [line](https://github.com/ethereum/execution-spec-tests/blob/ccf25a322bf37a1c0fd9d6498c5e9edfaeb0d098/src/pytest_plugins/forks/forks.py#L190) by implementing an `ignore` method that returns `True` for forks that need to be ignored during test generation, such as the glacier forks.
None

chore(forks,pytest): Add `BaseFork.ignore` method

---

src/ethereum_test_tools/exceptions/exceptions.py
src/ethereum_test_tools/spec/blockchain/blockchain_test.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py

Do not export rlp_decoded filled blockchain field if there is BlockException.RLP_STRUCTURES_ENCODING exception
https://github.com/ethereum/execution-spec-tests/issues/415
https://github.com/ethereum/execution-spec-tests/issues/417

feat(fixtures): do not export rlp_decoded if there is BlockException.RLP_STRUCTURES_ENCODING

---

docs/CHANGELOG.md
tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py

dynamic create2 collision from different transactions same block
https://github.com/ethereum/execution-spec-tests/issues/381

feat(tests): dynamic create2 collision from different transactions same block

---

tests/cancun/eip6780_selfdestruct/test_selfdestruct.py

Small parametrization change to make sure we don't always `SELFDESTRUCT(self)` on the last call to self-destruct.
Executed on all clients, no issues.
None

refactor(tests): EIP-6780 Self-Destruct Tests Parametrization Change

---

src/ethereum_test_tools/vm/opcode.py

pypy doesn't name this parameter for some reason.

fix(fw): pypy compatibility - replace bytes=self with just self.

---

mkdocs.yml
setup.cfg

Removes the `mdx-truly-sane-lists` package introduced in #403. This seemingly fixed nested lists, but actually double-nested lists are still broken, as are context tabs, see #459.
Fixes #459.

fix(docs): fix nested lists and content tabs formatting #459

---

docs/CHANGELOG.md
src/ethereum_test_tools/vm/opcode.py
whitelist.txt

Added docstrings to most of the opcodes in the Opcodes Enum.
Left `TSTORE`,`TLOAD`,`SENDALL`,`RJUMPI`,`RJUMPV` incomplete due to confusion
#383

chore(fw): add docstrings to all opcodes in opcodes enum

---

tests/cancun/eip1153_tstore/test_tstorage.py
tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py

Remove zeros from pre-alloc of some of the tests.
Assigning a zero in the `pre` of a test is unnecessary, and can produce a different behavior in some clients (should actually be defined and fixed).
Assigning a zero in `post` is necessary to verify empty keys in storage in some of the tests.
#447

fix(tests): Remove zero pre-alloc from tests

---

docs/CHANGELOG.md
src/pytest_plugins/test_filler/test_filler.py

There's some instances where a test function in a module ends up being skipped and the parametrized fork contains a `None` value which then triggers an exception in function `pytest_collection_modifyitems` of `test_filler.py`.
This PR modifies behavior so that the item is removed if it reaches the `pytest_collection_modifyitems` without a fork value.
Example fill command:
```bash
fill -vv --fork=Prague tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py
```
fails before this PR.
None

fix(pytest-filler): Remove collected items without parametrized fork

---

docs/consuming_tests/index.md

Fix:
```console
python -m src.entry_points.markdownlintcli2_soft_fail
markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
Finding: ./docs/**/*.md ./README.md
Linting: 43 file(s)
Summary: 1 error(s)
docs/consuming_tests/index.md:32:84 MD056/table-column-count Table column count [Expected: 3; Actual: 4; Too many cells, extra data will be missing]
```
None.

docs(chore): remove extra '|' in table to appease markdownlint-cli2 v0.12.1

---

docs/CHANGELOG.md
src/ethereum_test_tools/spec/blockchain/blockchain_test.py
src/ethereum_test_tools/spec/blockchain/types.py
whitelist.txt

Adds an optional `verify_sync` flag for hive (or blockchain Engine API tests) to pick up and test a second client syncing to the first client.
Syncing is tricky to some clients and we actually need to send a full header via `engine_newPayloadVN` for some of them to start the sync process.
So this change also appends an empty block on top of the latest head of the test to use as syncing head.
None.

feat(fw): add optional `verify_sync` flag to hive blockchain tests

---

docs/CHANGELOG.md
src/ethereum_test_tools/spec/blockchain/types.py

Sets the `gas_limit` block header value to that optionally specified in the `genesis_env` provided to the blockchain tests constructor, by taking it from the previous env.
Fixes #468.

bug(fw): fix block header `gasLimit` value in post genesis blocks for blockchain tests

---

src/entry_points/evm_bytes_to_python.py
src/entry_points/tests/test_evm_bytes_to_python.py
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/opcode.py

fix: Macro+Opcode integration

---

docs/CHANGELOG.md
src/ethereum_test_tools/common/base_types.py
src/ethereum_test_tools/tests/test_base_types.py

Before this PR, it was possible that both of these statements returned true:
```python
Address(0x100) == "0x100"
Address(0x100) != "0x100"
```
Reason was that, since `__ne__` was not implemented for `FixedSizeBytes` and the fallback was to use `str` compare.
None

fix(fw): Fix `FixedSizeBytes` `!=` comparison

---

README.md

🐞 fix(README): Incorrect command to verify fixtures

---

.github/actions/build-geth-evm/action.yaml
docs/CHANGELOG.md
whitelist.txt

Github Actions are currently failing to build geth; this PR bumps Github Action to build geth with Golang 1.21. 
None

fix: bump go version from 1.20.5 to 1.21.x

---

docs/CHANGELOG.md
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/spec/blockchain/blockchain_test.py
src/ethereum_test_tools/spec/blockchain/types.py
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/__init__.py
src/ethereum_test_tools/vm/opcode.py
whitelist.txt

I think it would be handy to have test purpose Op that will trigger OOG if called
This will simplify parametrisations and code in tests when paramtrising over subcall return types
Such as RETURN, REVERT
Op.OOG(x, y)  is replaced with Op..SHA3(0, 100000000000)
alowing to use
```
@pytest.mark.parametrize("call_return", [Op.RETURN, Op.REVERT, Op.OOG])
...
contract_code = Op.MSTORE(0, Op.TLOAD(0)) + call_return(0, 32)
```
Example: 
https://github.com/ethereum/execution-spec-tests/pull/440/
https://github.com/ethereum/execution-spec-tests/issues/455

feat(tests): extend Op with Op.OOG macro opcode

---

docs/CHANGELOG.md
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_blockchain_test_hive.json
src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_state_test.json

closes #469
#469 
Changelog NOT updated because of the trivial nature.

chore(forks): generate fixtures with the Paris network name

---

tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py

Use unused environment value for the block gas limit in the memory expansion tests of mcopy.
Test still worked because the default block gas limit is much higher than what the test accounted for, so this change is only useful so that the test does not break if we reduce the default value at some point.
https://github.com/ethereum/execution-spec-tests/issues/471

fix(tests): mcopy: block gas limit for memory expansion tests

---

.github/workflows/fixtures.yaml
.vscode/launch.recommended.json
.vscode/settings.recommended.json
docs/CHANGELOG.md
docs/consuming_tests/index.md
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/tests/test_forks.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/yul.py
src/ethereum_test_tools/tests/conftest.py
src/ethereum_test_tools/tests/test_code.py
src/pytest_plugins/test_filler/test_filler.py
tox.ini

- Updates:
- ethereum_test_forks
- ethereum_test_tools, including a yul compiler code cleanup
- ethereum_test_tools tests
- github workflows
- tox update to use Prague as development
- vscode recommended files
- minor changes to the docs
None

all: Mark Cancun fork as deployed

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py

Fixes empty accounts not being recognized as such because an explicit zero was set as the value to a key.
Edit(dan): The original intent of this PR was also fixed in #486 and this PR now only adds additional tests for empty accounts and one small refactor.
Fixes https://github.com/ethereum/execution-spec-tests/issues/475

test(fw): add empty account tests

---

docs/CHANGELOG.md
src/ethereum_test_tools/spec/base/base_test.py
src/ethereum_test_tools/spec/file/types.py
src/ethereum_test_tools/spec/fixture_collector.py

This is a gentle refactor to make use of `Fixtures` during fixture collection and writing:
- Moves `collect_info_file()` from the `BaseFixture` class to `Fixtures`. It now also takes a file instead of an fd for consistency with other `Fixtures` methods.
-  Use `Fixtures` model in the `FixtureCollector` class.
Makes use of #501.

refactor(fw): augment & use Fixtures model in fixture collection

---

docs/CHANGELOG.md
setup.cfg

This PR:
- Softens minor and patch package dependency version requirements to try to avoid dependency conflicts with other dependencies (as we're currently experiencing, this is described in more details below).
- Sharpens major package requirements to avoid potential incompatibilities if one of our dependencies releases a new major version. 
[ethereum/execution-specs](https://github.com/ethereum/execution-specs) just bumped their consensus-specs dependency which in turn now requires [py-trie](https://github.com/ethereum/py-trie) v2.0.2. We currently require trie v2.1.1:
https://github.com/ethereum/execution-spec-tests/blob/4e66cef8e51716c437376d344c65f88b11308174/setup.cfg#L25-L34
This leads to a version conflict and installing ethereum-execution-specs fails with:
```
INFO: pip is …
```

chore: soften package requirements for compatibility with other dependences

---

.github/workflows/fixtures.yaml
.github/workflows/test.yaml

Disables fixture filling for Prague from geth master (branch configured via evm-config.yaml) in Github Actions. This will likely cause many sporadic fails at this early stage of Prague developement.
To remind us to re-enable it in the future: #514.

chore(ci): disable tox -e tests-develop in github actions

---

.github/workflows/test.yaml

Hotfix for the current issue we have in Github Actions (requires a proper follow-up fix!)
```
docs: freeze> python -m pip freeze --all
2 files would be left unchanged.
ERROR   -  "cairosvg" Python module is installed, but it crashed with:
no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache), 'libcairo.so.2' (no such file), '/usr/local/lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache).  Additionally, ctypes.util.find_library() did not manage to locate a …
```

chore(ci): hotfix github actions by using macos-12

---

.github/workflows/test.yaml
tox.ini

Resolves the github actions CI issues that have occured over the past few days:
- Reverts OS versions back to `macos-latest` and `ubuntu-latest`.
- For macOS only -  sets a fallback environment required for the `cairosvg` package within the tox ini file:
- This allows tox to find `libcairo-2`, that is installed and linked within homebrew. 
- It seems to be the only viable solution for now and is highlighted within the `mkdocs-material` [documentation](https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/?h=cairo#cairo-library-was-not-found). 
- Note this has to be set within tox as it uses an isolated environment. The environment variable set is exclusive to macOS so won't cause issues for other OS's.
- Please see related issues below for more context.
Past …

chore(ci): Revert CI to use macOS and Ubuntu latest releases

---

setup.cfg
src/ethereum_test_tools/exceptions/__init__.py
src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/spec/eof/eof_test.py
whitelist.txt

A bit of refactoring of #519.
#519.

Call evmone eofparse during fill refactor

---

docs/CHANGELOG.md
setup.cfg
src/ethereum_test_tools/exceptions/__init__.py
src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
src/ethereum_test_tools/spec/eof/eof_test.py
src/pytest_plugins/test_filler/test_filler.py
tests/prague/eip3540_eof_v1/container.py
tests/prague/eip3540_eof_v1/test_eof_example.py
whitelist.txt

Adds EOF exception checking using evmone-eofparse tool. Prints a nice message now if expected exception does not match returned by evmone or if valid eof test fails on evmone and so on.

feat(fw): Call `evmone-eofparse` on EOF tests filling

---

README.md

Change Besu's tracing support from "no" to "yes" in README (due to #511).
#511

docs(fix): small fix to tracing support in readme cf #511

---

src/ethereum_test_tools/common/types.py

Fixes a bug where some exceptions were still using `Storage.key_value_to_string`, which doesn't exist anymore.
#523

fix(fw): Fix `MissingKey` and `KeyValueMismatch` exceptions `str`

---

docs/CHANGELOG.md
pytest.ini
whitelist.txt

Set `--tb=short` in fill's pytest.ini for more compact test reports.
Comparison of different failure reports can be found #541.

feat(pytest): use --tb=short as default for fill test reports

---

src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_code_validation.py

Recognize new error code of eofparse: `invalid_dataloadn_index`.

add EOFException.INVALID_DATALOADN_INDEX

---

docs/CHANGELOG.md
src/ethereum_test_tools/rpc/__init__.py
src/ethereum_test_tools/rpc/rpc.py
tests_consume/test_via_rlp.py

Adds the EthRPC class alongside the BaseRPC class. The latter are used within `tests_consume/test_via_rlp.py`, and will be extended for consume engine.
~~I added this within `src/pytest_plugins/consume/json_rpc.py` but open to moving this somewhere else.~~
Moved to: `src/ethereum_test_tools/rpc/rpc.py`
None

chore(fw): Utilize an EthRPC class within consume rlp

---

docs/CHANGELOG.md
pytest.ini
src/ethereum_test_forks/__init__.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/forks/transition.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/vm/__init__.py
tox.ini

Miscellaneous fixes required for Prague EIPs in devnet-0:
- Export Prague in `ethereum_test_forks`
- Export `Macros` from `ethereum_test_tools`
- Fix types.TransactionReceipt and add types.TransactionLog
- Create `CancunToPragueAtTime15k`
- Add `engine_newPayloadV4` to Prague
None

fix(fw,forks,tox): Misc Prague fixes

---

.github/workflows/fixtures.yaml
.github/workflows/test.yaml
evm-config.yaml
tox.ini

- Reverts ethereum/execution-spec-tests#515
- Use develop only for devnet-0 EIPs, EOF should be filled separately

Revert "chore(ci): disable tox -e tests-develop in github actions"

---

src/cli/pytest_commands.py

Small bugfix in consume cli.
None

fix: fix extending pytest args when adding hive parallelism

---

src/cli/pytest_commands.py

fix(fw): warnings.warn in get_hive_flags_from_env()

---

tests/prague/eip7692_eof_v1/tracker.md

docs: EOF: Update test tracker

---

src/pytest_plugins/pytest_hive/pytest_hive.py

- Correctly forward an error encountered during test setup (in fixtures, for example) to the hive server (this fixes the error observed in the screenshot from hiveview below).
- Additionally forwards a failure to the hive server if an error occurs during test teardown.
None

fix(consume): correctly forward test setup error to hive server

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py

- EOF can have truncated data (these are valid containers).
- Properly specify non-returning code section.

fix(tests): EOF - EIP-3540: update validation tests for recent spec

---

tests_consume/test_via_rlp.py

This PR adds a more helpful message in the case that the simulator fails to connect to the client container. Currently, in the UI, we have the somewhat unhelpful:
This was initially hidden by the bug fixed in #569.

feat(rlp): add helpful assert message upon client initialization error in simulator

---

docs/CHANGELOG.md
src/cli/gentest.py
whitelist.txt

This PR:
- Fixes the `gentest` cli script which got broken by the pydantic refactor (original gentest pr: #470).
- Adds quick-start documentation to `gentest`'s module docstring.
These problems came to light whilst verifying #568.

fix(cli): update gentest to use pydantic models

---

tests_consume/test_via_rlp.py

This PR fixes the indices used in the block RLP filenames (`000n.rlp`) that get created in the client container. `n` should start from 1 (block 1), not 0 (genesis).
This was an oversight in the initial rlp implementation and brings the `*.rlp` file naming inline with the Hive consensus simulator:
None.

fix(rlp): fix indexing in block rlp filenames

---

tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py

It takes 1hr and 27 minutes to fill this EIP-2935 test, and given that the spec is changed, this test is probably out-of-date too.
So we will be skipping filling this test until https://github.com/ethereum/execution-spec-tests/issues/570 is implemented.
None

skip(tests): Lengthy EIP-2935 test

---

docs/CHANGELOG.md
src/ethereum_test_tools/exceptions/exceptions.py
whitelist.txt

Convert retesteth exceptions into pyspec format
Adjust the .json fillers accrodingly for consume command

feat(fw): add missing retesteth exceptions

---

docs/CHANGELOG.md
src/ethereum_test_tools/vm/opcode.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/__init__.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/helpers.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/spec.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py

Port over ethereum/tests EIP-4200 tests, both validation and execution.
Some duplicate tests were dropped, and some new immediate tests were
added.

new(tests) EIP-4200 relative jumps

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py

Makes the following fixes:
- `test_code_section_header_body_mismatch`: Change expected exception from `EOFException.INVALID_SECTION_BODIES_SIZE` -> `EOFException.INVALID_TYPE_SECTION_SIZE`
- `test_legacy_initcode_invalid_eof_v1_contract::trailing_bytes_after_data_section`: Correct output (`NON_RETURNING_SECTION`) in code section
- `test_eofcreate_deploy_sizes::64k-1` skip test due to oversized container in the pre-alloc.
None

fix(tests): EIP-7620,EIP-3540: Failing EOF tests

---

src/ethereum_test_tools/eof/v1/__init__.py
src/ethereum_test_tools/tests/test_eof_v1.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_eof_example.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_execution_function.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
tests/prague/eip7692_eof_v1/eip6206_jumpf/test_jumpf_execution.py
tests/prague/eip7692_eof_v1/eip6206_jumpf/test_jumpf_stack.py
tests/prague/eip7692_eof_v1/eip6206_jumpf/test_jumpf_target.py
tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py
tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_exchange.py
tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_swapn.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_code_validation.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_data_opcodes.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py

Having non-returning code sections in EOF is much more common (at least in tests) and because we rely on the default values the `NON_RETURNING_SECTION` is better default.
I only update container.py for visualization and fixed JUMPF failing tests (including one typo). New default can be applied to other tests later.

feat(fw): make NON_RETURNING_SECTION default in Container

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py

I added an instrumentation to `eof_test()` to collect all EOF bytecodes and report duplicates.
These are some duplicated test cases removed.
I don't think we have to clean it all right now, but this is handy tool for migrating tests from other places.

fix(tests): EOF - EIP-3540: Remove duplicated validation tests

---

tests/prague/eip2537_bls_12_381_precompiles/helpers.py

Fix a warning while generating tests because some of the classes for EIP-2537 tests were named `class Test*` but were not pytests.
None

fix(tests): Pytest warning on EIP-2537 tests

---

.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
setup.cfg
tox.ini

Adds a step toward deprecating the requirement of solc for EEST (using solc-select instead).
Tox passes after merging this into my origin main, check recent commits:
https://github.com/spencer-tb/execution-spec-tests
I personally have not used an "installed solc" for the past 3 months, and instead used `solc-select`.
Due to the latter I've kept these changes trailing in my local repo for running tox.
https://github.com/ethereum/execution-spec-tests/pull/461 - planning to split the latter into smaller PRs, this PR being one of them.
Future PRs will include the deprecation of solc completely in within EEST in favor of solc-select.

feat(ci): use solc-select for tox

---

docs/CHANGELOG.md
tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py

Fix typo found by Spencer in selfdestruct test that affected verkle experiments

bug(tests):  fix typos in selfdestruct test

---

src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
whitelist.txt

We are changing the EOF validation API (e.g. eofparse, EOF validation tests): the top-level EOF container must not have truncated/missing data section. This is how you would validate "genesis" EOF containers and is also less confusing for EOF tool users.
This change introduces new error kind: `TOPLEVEL_CONTAINER_TRUNCATED` and matches the recent change in evmone.

refactor(tests,tw): EOF - Top-level container must not be truncated

---

.github/workflows/coverage.yaml

Fix evmone coverage script issue with PRs from remote repos
Support EOF tests coverage
https://github.com/ethereum/execution-spec-tests/pull/598

support coverage script for EOF tests

---

.github/actions/build-fixtures/action.yaml

Fixes the new `solc-select` dependency required to build fixtures, for both stable/develop fixture releases as well and feature (EOF/Verkle) fixture releases.
This was an oversight from the following PR: https://github.com/ethereum/execution-spec-tests/pull/604

fix(ci): add solc-select to fill stage of build fixtures

---

docs/CHANGELOG.md
src/cli/gen_index.py
src/cli/hasher.py
src/ethereum_test_tools/spec/blockchain/types.py
whitelist.txt

Enables loading `ethereum/tests/BlockchainTests` (except for 5 json files that define invalid fields via "bigint").
1. Makes `post_state` an optional field in blockchain fixtures.
2. Adds a list of fixtures to skip in `genindex` (the fixtures here all currently use `bigint` to define invalid fields in json).
3. Updates `hasher` to use `_info["generatedTestHash"]` as a synonym for `_info["hash"]` (this allows `genindex` to check whether the `index.json` is up-to-date for `ethereum/tests`; otherwise it must be regenerated every time).
This requires: https://github.com/ethereum/tests/pull/1380.
Test loading of fixtures into EEST pydantic models with:
```console
genindex -i ~/path/to/ethereum/tests/BlockchainTests/
```
Expected output:
```
Skipping …
```

feat(consume): enable loading of `ethereum/tests/BlockchainTests`

---

.github/workflows/coverage.yaml

Fetch legacy tests to measure coverage as well (>Constantinople <=Cancun)
When converting .json tests. use it's most recent filled .json version as well as legacy version of the file to compare the coverage

use legacy tests to measure coverage as well

---

src/ethereum_test_tools/common/types.py

Using `PrivateAttr` seems to be a more standard way of achieving this in pydantic:
https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes
#584

refactor(fw): use pydantic PrivateAttr for model class params

---

tests/prague/eip7692_eof_v1/eip7069_extcall/helpers.py
tests/prague/eip7692_eof_v1/eip7069_extcall/test_address_space_extension.py
tests/prague/eip7692_eof_v1/eip7069_extcall/test_returndataload.py
whitelist.txt

Simple test case covering the updated out-of-bounds behavior of RETURNDATACOPY accross legacy and EOF contracts.
I'm not sure whether to place this new test in the existing `7069_extcall` subdir or in its own, please advise.
Related update to the spec https://github.com/ethereum/EIPs/pull/8617. Update to evmone https://github.com/ethereum/evmone/pull/909

new(tests): EIP-7069: Different RETURNDATACOPY oob

---

src/ethereum_test_tools/eof/v1/__init__.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py

test eof container custom_size field
this analyze ori test collection and extend with pyspec his test cases

test eof container custom_size field

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/coverage.yaml

make coverage script to run on native evmone test runner tools as well

feat(github): coverage on native evmone test runners

---

tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py

Contributing an EOFCREATE edge case from https://github.com/ipsilon/execution-spec-tests/pull/1 upstream
N/A

new(tests): EOFCREATE frame reverts with EOF container

---

src/pytest_plugins/test_filler/test_filler.py

Fixes the name of the root folder in the generated .tar.gz file to always be `fixtures` instead of the name of the output folder.
@pdobacz 
None

fix(plugins): Root folder name in generated .tar.gz

---

src/pytest_plugins/forks/forks.py

According to this stack-overflow answer https://stackoverflow.com/a/64937074 it is not recommended to call `pytest.skip` during `pytest_generate_tests` because it skips the entire module, which is what seems to be happening on PR #636, where there are two different `pytest.mark.valid_until` markers in two separate functions, and if the second one does not allow filling with the currently selected forks, none of the tests are executed.
None

fix(plugins/forks): remove `pytest.skip` from pytest_generate_tests

---

.github/workflows/coverage.yaml

When parsing coverage tests file, check that the tests are found in /tests and /legacytests repositories
https://github.com/ethereum/execution-spec-tests/pull/636

feat: coverage script check file existance in tests

---

.github/workflows/tox_verify.yaml
configs/evm.yaml

- Temporarily disable `tox -e tests-develop` until we have a stable devnet-1 implementation of the transition tool.
- Update geth's evm to `lightclient/prague-devnet-1`
#606

fix(github,configs): Temporarily disable `tox -e tests-develop`, update geth evm

---

docs/CHANGELOG.md
src/ethereum_test_tools/common/types.py
tests/prague/eip7002_el_triggerable_withdrawals/helpers.py
tests/prague/eip7002_el_triggerable_withdrawals/test_withdrawal_requests.py
tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals.py

Update tests and framework to match changes described in https://github.com/ethereum/execution-apis/pull/549
None

fix(fw,tests): Withdrawal request v1 update execution-apis #549

---

docs/CHANGELOG.md
src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/opcode.py

Introduce keyword arguments to some of the opcodes:
- `Op.CREATE`
- `Op.CREATE2`
- `Op.EOFCREATE`
- `Op.CALL`
- `Op.DELEGATECALL`
- `Op.STATICCALL`
- `Op.CALLCODE`
- `Op.EXTCALL`
- `Op.EXTSTATICCALL`
- `Op.EXTDELEGATECALL`
And most of the keyword arguments also have defaults, but they cannot be mixed with positional arguments, so this is valid:
```python
Op.CALL(address=0x1234)
```
but this is not:
```python
Op.CALL(Op.GAS, address=0x1234)
```
This feature allows easier parametrization, as we no longer have to workaround the cases where an opcode has different number of parameters or in different order:
```python
@pytest.mark.parametrize("op", [Op.CREATE, Op.CREATE2])
def test_example(op: Op):
op(offset=0, size=1234)
```
And in this case the `salt` parameter of `CREATE2` is simply passed …

feat(vm): Opcode keyword arguments

---

docs/CHANGELOG.md
src/ethereum_test_tools/eof/v1/__init__.py
src/ethereum_test_tools/spec/eof/eof_test.py
src/ethereum_test_tools/spec/eof/types.py

Introduces `kind` field in the `Container` class and the `EOFTest` class, used to mark a container as a specific kind of container, such as "INITCODE".
When the field is set:
- `evmone-eofparse` is called with the `--initcode` flag
- the output EOF fixture contains `containerKind: "INITCODE"` field in all vectors, by default it contains `containerKind: "RUNTIME"`.
Example of a test fixture JSON file after this change:
```json
{
"tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py::test_all_opcodes_in_container[fork_CancunEIP7692-eof_test-opcode_STOP]": {
"vectors": {
"0": {
"code": "0xef00010100040200010029030001001404002000008000146000600060006000600060006000600060006000600060006000600060006000600060006000600000ef0001010004020001000104000000008000000011223344556677 …
```

feat(fw): EOF - Add `containerKind` to EOF fixtures, add `--initcode` flag when calling evmone-eofparse

---

src/ethereum_test_tools/vm/opcode.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py

Fixes the DATALOADN stack specs in `opcode.py`, also removes the workarounds in one test
N/A

fix(fw,tests): Fix Op.DATALOADN stack

---

src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
src/ethereum_test_tools/spec/eof/eof_test.py
src/ethereum_test_tools/spec/eof/types.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Test 3 rules
- Opcodes in subcontainers, by usage kind (EOFCREATE/RETURNCONTRACT)
- Mixed reference container (both EOFCREATE and RETURNCONTRACT)
- No unused containers

new(test) EOFCREATE and RETURNCONTRACT opcode validation tests

---

src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_container_size.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_code_validation.py

Add tests aligning with https://github.com/ethereum/EIPs/pull/8670 / https://github.com/ipsilon/eof/pull/125
na

new(tests): EOF - EIP-3540: MAX_INITCODE_SIZE validation

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/consume/types.py
src/ethereum_test_tools/tests/test_exceptions.py

Tox began failing for some unknown reason with the following mypy error:
```
src/ethereum_test_tools/tests/test_exceptions.py:16: error: Need type annotation for "GenericExceptionListAdapter"  [var-annotated]
src/ethereum_test_tools/tests/test_exceptions.py:17: error: Need type annotation for "TransactionExceptionListAdapter"  [var-annotated]
src/ethereum_test_tools/tests/test_exceptions.py:18: error: Need type annotation for "BlockExceptionListAdapter"  [var-annotated]
src/ethereum_test_tools/common/types.py:1242: error: Self? has no attribute "secret_key"  [attr-defined]
src/ethereum_test_tools/spec/consume/types.py:152: error: Self? has no attribute "test_cases"  [attr-defined]
Found 5 errors in 3 files (checked 123 source files)
```
This PR fixes all issues.

fix(fw): Tox

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py

Update a couple of new tests trip the new "no orphan containers" rule.

fix(tests): EOF - EIP-3540: Remove Orphans Containers in Tests

---

.github/workflows/coverage.yaml

this should fix coverge script on prs coming from remote repos
https://github.com/ethereum/execution-spec-tests/pull/647

fix(github): Coverage script on remote repo

---

converted-ethereum-tests.txt
src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_returncontract.py
tests/prague/eip7692_eof_v1/tracker.md

This migrates `RETURNCONTRACT` validation tests from ethereum/tests.
Note: according to the latest spec these cases are valid only for "initcode" containers, and next step would be to support `initcontainer` flag in test fixtures - see the branch https://github.com/ipsilon/execution-spec-tests/tree/eof-returncontract-initcode

new(tests): EOF - EIP-7620: RETURNCONTRACT validation tests

---

src/ethereum_test_tools/spec/eof/eof_test.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Fixes all container type errors in EOF tests, and move stuff out of `tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py`
None

fix(tests): EOF - Container type errors

---

src/ethereum_test_tools/exceptions/evmone_exceptions.py
src/ethereum_test_tools/exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

This adds new EOF validation error: incompatible container kind. And fixes existing tests.

feat(tests): EOF - EIP-7620: Incompatible container kind validation error

---

README.md
src/evm_transition_tool/geth.py

In windows, geth binary file ends with exe extension

fix(fw): EVM binary pattern for windows

---

.github/workflows/coverage.yaml
converted-ethereum-tests.txt
tests/homestead/coverage/test_coverage.py

Farther support of the coverage git workflow:
- The scripts errors out properly if the test filling didn't work 
- If eof test is detected, retesteth run will be skipped as eof format has changed
- Fix missing coverage file to run with type3 transaction (that covers 16 lines in evmone)
- Use docker hub login to grant more download attempts of docker images

fix(tests): coverage script support

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_extcode.py

The test takes the result of `EXTCODESIZE` as the size for the `EXTCODECOPY`.
In a world where the `EXTCODESIZE` is properly implemented for an EOF target but the `EXTCODECOPY` is not, the result from `EXTCODECOPY` will still be correct since `EXTCODESIZE` outputs 2 and the first 2 bytes of any EOF container will be `0xef00`. This change recommends a random size (say 6) so that the difference between correct and incorrect implementations can manifest itself in the `SSTORE`

fix(tests): EOF - EIP-3540: EXTCODECOPY a hard-coded size for EOF target

---

docs/CHANGELOG.md
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_data_opcodes.py
tests/prague/eip7692_eof_v1/eip7480_data_section/test_datacopy_memory_expansion.py

Memory expansion tests for DATACOPY, minor refactor to MCOPY memory expansion test, made in order for them to match conventions.
I eyeballed the resulting JSONs from the MCOPY test and the divergence seems to be immaterial (different contract addresses).
The new test is a shameless rip-off the MCOPY mem expansion test. I'm not sure whether shared pieces should be refactored, please advise if so and how.
Working towards filling the gaps detected in https://github.com/ipsilon/eof/pull/138

new(tests): EOF - EIP-7480: Add tests for DATACOPY memory expansion

---

setup.cfg
src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/spec/consume/types.py

Issue fixed in PR #660 was potentially caused by pydantic being automatically updated to 2.8.0.
This PR pins the minor version to be 2.8 so we don't have surprises in the future.
Also remove `type: ignore` introduced in #660.
None.

fix(setup): Pin pydantic minor version

---

src/ethereum_test_tools/tests/test_vm.py
src/ethereum_test_tools/vm/bytecode.py
src/ethereum_test_tools/vm/opcode.py

This PR implements the following changes:
- Refactors `Bytecode` class to its own file `vm/bytecode.py`
- Trims `FixedSizeBytes` arguments on opcode calls to remove zeros and use smaller `PUSH` operations
- Implements `MSTORE` macro, which takes an arbitrary length `bytes` object and automatically creates the bytecode to place it in the EVM execution memory.
None

feat(fw): Refactor `Bytecode`, create `MSTORE` macro

---

src/ethereum_test_tools/common/types.py
src/ethereum_test_tools/tests/test_types.py

Fixes a bug where the `copy` method from `CopyValidateModel` includes unset fields when dumping the model to re-validate.
Produces identical fixtures as main branch.
Required for #676
@gumb0 
None

fix(fw): Fix `CopyValidateModel`

---

docs/CHANGELOG.md
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Test cases that check subcontainer validation in a deeply nested subcontainer, and in code sections other than section 0.

new(tests): EOF - EIP-7620: Add more tests for validating EOF subcontainer kinds

---

tests/prague/eip7692_eof_v1/eip7069_extcall/test_returndatacopy_memory_expansion.py

Follow-up in a similar vein to #664 (#664 includes basic refactors to the MCOPY test, which this test is also based on), with the same disclaimers (lots of copy pasted code) and same question about how to best refactor it (if at all)
Working towards filling the gaps detected in https://github.com/ipsilon/eof/pull/138

new(tests): EOF - EIP-7069: RETURNDATACOPY mem expansion and copy OOG

---

tests/prague/eip7692_eof_v1/eip7069_extcall/helpers.py
tests/prague/eip7692_eof_v1/eip7069_extcall/test_calldata.py
whitelist.txt

Tests to validate that inputdata passed into EXT*CALL operations is handled correctly.

new(tests) EXT*CALL input data validation

---

docs/CHANGELOG.md
tests/prague/eip7692_eof_v1/eip4750_functions/__init__.py
tests/prague/eip7692_eof_v1/eip4750_functions/helpers.py
tests/prague/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

new(tests): EOF - EIP-4750: Runtime stack overflow at CALLF

---

src/ethereum_test_fixtures/__init__.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py
src/pytest_plugins/consume/hive_simulators/rlp/conftest.py

Moves common fixtures from `src/pytest_plugins/consume/hive_simulators/rlp/conftest.py` and `src/pytest_plugins/consume/hive_simulators/engine/conftest.py` to a generalized form within `src/pytest_plugins/consume/hive_simulators/conftest.py`.

Changes to #691

---

src/evm_transition_tool/evmone.py
src/evm_transition_tool/transition_tool.py
src/evm_transition_tool/types.py

Removes the empty-to-string workaround since https://github.com/ethereum/evmone/issues/923 has been fixed and closed.
None

fix(evm_transition_tool): Remove evmone empty-to-string workaround

---

docs/CHANGELOG.md
tests/prague/eip7692_eof_v1/eip6206_jumpf/test_jumpf_execution.py

Tests for runtime stack overflow at JUMPF instruction. Similar to https://github.com/ethereum/execution-spec-tests/pull/678.

new(tests): EOF - EIP-6206: Runtime stack overflow at JUMPF

---

src/evm_transition_tool/file_utils.py
src/evm_transition_tool/transition_tool.py

Fix JSON dump when using `--evm-dump-dir`.
None

fix(evm_transition_tool): fix `--evm-dump-dir`

---

src/cli/gentest.py
src/ethereum_test_tools/rpc/rpc.py
src/ethereum_test_tools/rpc/types.py
src/ethereum_test_types/types.py

Adds missing methods and typing to the `ethereum_test_tools/rpc` library.
Used in some draft PRs.
None

chore(tools/rpc): Improve RPC typing

---

docs/CHANGELOG.md
src/cli/pytest_commands.py
whitelist.txt

This PR allows us to run consume commands using the following Dockerfile entrypoint from hive:
```dockerfile
ENTRYPOINT ["consume", "engine", "--input=https://.../execution-spec-tests/releases/.../fixtures.tar.gz", "-v"]
```
The condition `if not sys.stdin.isatty():` checks if the standard input (stdin) is connected to a terminal. If it's not connected to a terminal, it implies that the input might be coming from a pipe or a file, which is why the command adds --input=stdin. 
In a Docker container, `sys.stdin.isatty()` returns False because Docker doesn't provide a terminal interface by default. This causes an issue where the input is incorrectly automatically set to stdin when running in Docker.
To fix the latter we additionally check for `--input` within the consume command arguements. …

chore(consume): fix `--input` when running from hive

---

src/ethereum_test_specs/eof.py
src/evm_transition_tool/transition_tool.py

Fixes trace dumping in two scenarios.
None

fix(specs,transition_tool): Trace dump fixes

---

src/cli/pytest_commands.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py
src/pytest_plugins/consume/hive_simulators/timing.py

Creates `TimingData` class to better manage the time metrics of a consume test.
The formatted output now looks like this:
```
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py .
Timings (seconds): 
Total: 0.7915
Start client: 0.5919
Test case execution: 0.0126
Initial forkchoice update: 0.0028
Get genesis block: 0.0020
Payloads execution: 0.0073
Payload 1: 0.0073
engine_newPayloadV4: 0.0043
engine_forkchoiceUpdatedV3: 0.0030
Stop client: 0.1718
```
And the sections are recorded even in case of an exception due to the context management of the new class (using `with`).

feat(consume): Enhance timing data

---

src/ethereum_test_vm/opcode.py
src/ethereum_test_vm/tests/test_vm.py

The naming convention of opcodes defined with immediates clashes with
fixture parsing code. Use an underscore instead of brackets
This allows opcodes with immediates to be parameters for tests and not throw strange errors when the fill fails due to the client tool.

fix(fw): Change opcode with immediate name

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py

Includes a special case uncovered via fuzzing:
`ef0001 010000 028000`, courtesy @chfast

new(tests): EOF - EIP-3540: Expand section size testing

---

src/ethereum_test_exceptions/evmone_exceptions.py
src/ethereum_test_exceptions/exceptions.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

EOF tests for a very deeply nested container and one level of all
possible containers.

new(tests) Deep and wide EOF subcontainers

---

src/pytest_plugins/filler/pre_alloc.py
tests/shanghai/eip3651_warm_coinbase/conftest.py
tests/shanghai/eip3651_warm_coinbase/spec.py
tests/shanghai/eip3651_warm_coinbase/test_warm_coinbase.py
tests/shanghai/eip3855_push0/conftest.py
tests/shanghai/eip3855_push0/spec.py
tests/shanghai/eip3855_push0/test_push0.py
tests/shanghai/eip3860_initcode/conftest.py
tests/shanghai/eip3860_initcode/helpers.py
tests/shanghai/eip3860_initcode/spec.py
tests/shanghai/eip3860_initcode/test_initcode.py
tests/shanghai/eip4895_withdrawals/conftest.py
tests/shanghai/eip4895_withdrawals/spec.py
tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Updates all Shanghai tests to use dynamic pre allocation account addresses.
Refactors most tests to be more update with existing framework standards.
Adds additional call contents tests for EIP-3855: PUSH0 Instruction.
Todo: Update EIP-4895: Beacon chain withdrawals test cases.
Requires https://github.com/ethereum/execution-spec-tests/pull/584 to be merged to main.

feat(tests): use dynamic pre alloc within shanghai tests

---

docs/CHANGELOG.md
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py

Filled tests now contain the `index.json` file by default.
#715

feat(filler): generate index

---

tests/prague/eip7692_eof_v1/tracker.md

fix(docs): Add more cases to EOF tracker

---

docs/CHANGELOG.md
src/cli/gen_index.py
src/cli/tests/test_pytest_fill_command.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py

Adds a `fixtures/.meta/` folder for the following metadata files that are generated from a `fill`/`consume` operation.
```tree
├── assets/
│   └── style.css
├── fixtures.ini
├── index.json
├── report_consume.html
└── report_fill.html
```
The aim of this PR is to clean the additional files created. Primarily so client devs can simply choose to ignore `.meta/` when executing tests from fixture releases within there CI or otherwise. This gives us freedom to dump anything within the folder for the long term.
N/A

feat(fw): use a metadata folder within fixtures

---

docs/CHANGELOG.md
src/cli/pytest_commands/fill.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py

Fixes an issue that occurs due to the fixture collectors still producing fixtures while the index was being generated at the same time.
Solution is to use a file lock (like in the consume command) to only generate the index until the last fixture collector is being cleaned up.
None

fix(plugins/filler): Index generation concurrency issue

---

docs/CHANGELOG.md
src/cli/gen_index.py
src/ethereum_test_exceptions/exceptions.py
src/ethereum_test_fixtures/base.py
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_fixtures/consume.py
src/ethereum_test_fixtures/eof.py
src/ethereum_test_fixtures/file.py
src/ethereum_test_fixtures/state.py
src/ethereum_test_fixtures/tests/test_eof.py
src/ethereum_test_types/eof/v1/__init__.py

Fixture filling was failing due to the index generation not supporting parsing EOF tests.
Fixed:
- EOF fixture parsing due to `ContainerKind` not parsing correctly on read
- `EOFException` parsing due to not being supported by `from_pipe_str` function
- Refactored `ExceptionBase` and subclasses string parsing 
Closes #724

fix(fixtures): Fix index generation for EOF tests

---

tests/prague/eip7692_eof_v1/tracker.md

fix(docs): Add some execution cases to EOF test tracker

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
src/pytest_plugins/consume/hive_simulators/exceptions.py
src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py

Fixes a bug in the consume (hive) genesis mismatch exception. For cases where the hash mismatch was present the error would overwrite the incorrect hash to the correct hash showing no mismatch within the exception. This occurred as we cast the returned genesis block from clients into the `FixtureHeader` mode, which always recalculates the block hash.
Additionally adds a further check to highlight if fields in the recieved client genesis block are unexpected. Highlighting that an incorrect fork could be enabled.
N/A

bug(consume): genesis block hash exception

---

.github/workflows/fixtures_feature.yaml
docs/CHANGELOG.md

Allow automatic fixture building of all features that start with the given feature name included in the tag.
For example, if we create a tag called `eip7692@v123.0.0`, and there are two features named `eip7692` and `eip7692-prague`, fixtures for both features will be built and automatically included in the new release.
Test workflow run here: https://github.com/marioevz/execution-spec-tests/actions/runs/10308733453
None.

feat(github): Allow starts-with feature building when tagging

---

docs/CHANGELOG.md
docs/writing_tests/test_markers.md
src/cli/tests/test_pytest_fill_command.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/generators.py
src/ethereum_test_types/tests/test_eof_v1.py
src/ethereum_test_types/tests/test_types.py
src/ethereum_test_types/types.py
src/ethereum_test_vm/__init__.py
src/ethereum_test_vm/bytecode.py
src/ethereum_test_vm/evm_types.py
src/ethereum_test_vm/helpers.py
src/ethereum_test_vm/opcode.py
src/pytest_plugins/filler/pre_alloc.py
src/pytest_plugins/filler/tests/test_pre_alloc.py
src/pytest_plugins/forks/forks.py
src/pytest_plugins/help/help.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/frontier/opcodes/test_dup.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py
whitelist.txt

Adds the `with_all_evm_code_types` marker that can be added to a test as follows:
```python
@pytest.mark.with_all_evm_code_types
@pytest.mark.valid_from("Frontier")
def test_something_with_all_evm_code_types(evm_code_type: EVMCodeType):
pass
```
and the test will be parameterized for parameter `evm_code_type` only with value `[EVMCodeType.LEGACY]` starting on fork Frontier, and eventually it will be parametrized with with values `[EVMCodeType.LEGACY, EVMCodeType.EOF_V1]` on the EOF activation fork.
Adding the `evm_code_type` parameter to the function signature is optional and can be done only if required.
In all calls to `pre.deploy_contract`, if the code parameter is `Bytecode` type, and `evm_code_type==EVMCodeType.EOF_V1`, the bytecode will be automatically wrapped in an EOF V1 …

feat(fw,forks,tests): Add EVM code type marker

---

docs/writing_tests/test_markers.md
pytest.ini
src/ethereum_test_types/helpers.py
src/ethereum_test_types/tests/test_helpers.py
tests/byzantium/eip198_modexp_precompile/test_modexp.py
tests/cancun/eip1153_tstore/test_tstorage.py
tests/cancun/eip1153_tstore/test_tstorage_create_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_reentrancy_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
tests/cancun/eip4844_blobs/common.py
tests/cancun/eip4844_blobs/conftest.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py
tests/cancun/eip4844_blobs/test_blobhash_opcode.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile_gas.py
tests/cancun/eip5656_mcopy/test_mcopy.py
tests/cancun/eip5656_mcopy/test_mcopy_contexts.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py
tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py
tests/paris/security/test_selfdestruct_balance_bug.py
tests/prague/eip7702_eoa_code_tx/test_eoa_code_txs.py

Used to mark tests that cannot work without making impractical (for real networks) modifications to the pre-alloc, such as deploying a contract in an address to allow a collision with another deployment.
This will help us not having to run these tests in devnets because is unfeasible.
Updates `compute_create_address` helper to take an `opcode` parameter and switch between `CREATE` or `CREATE2` (`EOFCREATE` eventually) to calculate the address.
Converts the following tests to use the `pre` fixture to use `pre.deploy_contract`, `pre.fund_eoa` and `pre.fund_address`:
- tests/cancun/eip1153_tstore/test_tstorage*.py
- tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
- tests/cancun/eip4844_blobs/test_blob_txs*.py
- tests/cancun/eip4844_blobs/test_blobhash_opcode.py
- …

refactor(tests): Remaining pre alloc updates

---

src/ethereum_test_types/eof/v1/__init__.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py

Add optional `Container.expected_bytecode` with raw bytes of the expected constructed bytecode.
This allows confirming that raw EOF and `Container()` representations are identical.

feat(fw): add optional `Container.expected_bytecode`

---

converted-ethereum-tests.txt
src/ethereum_test_types/eof/v1/__init__.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Migrate `EOFCREATE` tests from ethereum/tests which become outdated (contain unreferenced subcontainers).

new(tests): migrate "valid" EOFCREATE validation

---

tests/prague/eip7692_eof_v1/tracker.md

There's a lot of testing needed for stack validation, so I split the cases into subsections.
(Note there are still many execution cases missing from the tracker, I plan to submit another batch pointing to cases generated by evmone)

fix(docs): Add stack validation cases to EOF tracker

---

converted-ethereum-tests.txt
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py

Migrate tests from EOFTests/efValidation/EOF1_truncated_section_.json.

new(tests): EOF - EIP-3540: migrate tests for truncated sections

---

docs/CHANGELOG.md
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/rlp/conftest.py
src/pytest_plugins/filler/filler.py
whitelist.txt

Adds the consume and hive commands to re-run a test case within hiveview. This is to aid test case reproduction for client devs incase of a failure.
Requires a small change to `app-suite.js` within hive: https://github.com/ethereum/hive/commit/cdbd33641dd2ba94133360535662e7309c34d83c#
You can test using this branch: https://github.com/spencer-tb/hive/tree/prague/devnet-1
Gives us the following on hiveview:
N/A

feat(consume): add reproducible consume/hive commands

---

tests/verkle/eip4762_verkle_gas_witness/test_codecopy_generic_initcode.py
tests/verkle/eip4762_verkle_gas_witness/test_creates.py
tests/verkle/eip4762_verkle_gas_witness/test_extcodesize.py
tests/verkle/eip6800_genesis_verkle_tree/test_contract_codechunking.py
tests/verkle/eip6800_genesis_verkle_tree/test_contract_creation.py
tests/verkle/eip6800_genesis_verkle_tree/test_storage_slot_write.py

The `verkle/main` branch had a recent change in the testing library which didn't allow anonymous parameters for `compute_create_address(...)`.

verkle: fix compute_create_address signature calls

---

.github/actions/build-besu-evm/action.yaml
.github/actions/build-evm/action.yaml
.github/actions/build-fixtures/action.yaml
configs/evm-impl.yaml
configs/evm.yaml
configs/feature.yaml
docs/CHANGELOG.md
src/ethereum_test_forks/forks/forks.py
src/pytest_plugins/forks/forks.py
tests/prague/eip7692_eof_v1/__init__.py

#736 broke feature building for `eip7692-prague` because `PragueEIP7692` does not exist in main so the simultaneous building of both `eip7692`+`eip7692-prague` would fail when the release is tagged.
This PR not only fixes the issue but also allows forks to be specified in comma-separated value, so now the EOF fork is defined as:
```python
EOF_FORK_NAME = "CancunEIP7692,PragueEIP7692"
```
Which means that the EOF tests now can be filled in either fork, and this results in the correct and automatic filling of both `eip7692` and `eip7692-prague` features in the same release.
This was achieved by a refactor of `src/pytest_plugins/forks/forks.py`, by simply using sets instead of lists, after many attempts including constructing a "fork-tree", which was unsuccessful.
This PR also adds the …

feat(plugins,forks,github): Allow dual-feature (Prague+Cancun) build on EOF releases

---

converted-ethereum-tests.txt
src/ethereum_test_types/eof/v1/__init__.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_migrated_valid_invalid.py

Migrate https://github.com/ethereum/tests/blob/develop/src/EOFTestsFiller/EIP3540/validInvalidFiller.yml.

new(tests): EOF - EIP-3540: Migrate validation tests: EIP3540/validInvalidFiller.yml

---

tests/prague/eip7692_eof_v1/eip7069_extcall/test_calls.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
whitelist.txt

Mainly inspired by https://github.com/ipsilon/eof/pull/138 and evmone state_transition tests. Following the conventions used in #730, in particular the test `test_eof_eofcreate_msg_depth` is an extension of the `test_eof_calls_msg_depth`, just even more complex and magic. I'm not sure if this isn't too much, WDYT? It would however be good to have this (exotic) condition covered (and we decided we do want this `msg.depth` rule applied for various reasons).

new(tests): EOF - EIP-7620: tests for msg.depth and static flag

---

docs/CHANGELOG.md
docs/writing_tests/writing_a_new_test.md
src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/utility/pytest.py
src/ethereum_test_tools/utility/tests/test_pytest.py
whitelist.txt

This PR tries to make this parametrizing helper function a pure helper library function which doesn't obfuscate how parametrization is achieved via pytest (respectively by the test implementer in their definition of cases).
Changes:
- Don't return a `pytest.mark.parametrize` decorator, rather a list of arguments to supply to `pytest.mark.parametrize()`.
- Make each case in `cases` a `pytest.param()`. This is a bit tricky: The `argvalues` in this case must be a dictionary containing the actual names and values of the parameters to be parametrized - a `ValueError` is raised if this is not the case.
- Raise `UnknownParameterInCasesError` if a case in `cases` contains a parameter not present in `defaults` 6591eb73425cffbdb5ed2a23ec0c3879c0a807ab
- Update docs.
- Add tests.
Original PR: #739

refactor(fw): `parametrize_with_defaults` -> `extend_with_defaults`

---

tests/prague/eip7702_set_code_tx/test_gas.py

Contains the required changes to the 7702 tests if #757 is merged in #739.
#757, #739.

refactor(tests): update for parametrize_with_defaults -> extend_with_defaults

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py

Upstreaming tests from specs implementation. Test 1 - 128 inputs in section 2.

new(tests): EOF - EIP-3540: Test types with 128 inputs

---

tests/verkle/eip6800_verkle_tree/test_verkle_from_mpt_conversion.py

The current EIP-6800 defines the balance as a value of [up to 128 bits](https://eips.ethereum.org/EIPS/eip-6800#header-values). We had a test which defined a pre-state with a balance of $10^{40} > 128$ bits.

verkle: fix balance overflow

---

converted-ethereum-tests.txt
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_order.py

Test containers section being out of order in the header and/or body.
This extends and follows the convention of the test_section_order()
for the optional container section.
This also converts EOFTests/efValidation/EOF1_section_order_.json.

new(tests): EOF - EIP-3540: out of order container section

---

tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_header_body_mismatch.py

Refactors the parametrization of `tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_header_body_mismatch.py::test_code_section_header_body_mismatch` to use
[`extend_with_defaults`](https://ethereum.github.io/execution-spec-tests/main/writing_tests/writing_a_new_test/#the-extend_with_defaults-utility) to try and improve readability.
#731

refactor(tests): use extend with defaults

---

docs/CHANGELOG.md
src/cli/pytest_commands/consume.py

Fixes returning a 0 (pass) exit code when failing consume runs.
This cropped up in the geth verkle CI where tests would fail within consume direct but pass the CI step. @jsign
N/A

chore(consume): return exit-code from consume commands

---

converted-ethereum-tests.txt
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Migrate EOFTests/efValidation/EOF1_embedded_container_.json.

new(tests): EOF - EIP-7620: migrate "embedded container" tests

---

tests/cancun/eip5656_mcopy/test_mcopy.py
tests/cancun/eip5656_mcopy/test_mcopy_contexts.py
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py

This is https://github.com/ethereum/execution-spec-tests/pull/726 rebased after the EVM code type marker got merged to `main` and cleaned up. I also completed the set of EOF-MCOPY tests by applying the parameter in the remainder of existing 5656 tests.
I ran it through evmone intentionally breaking the MCOPY implementation in various ways, and the failures appear to be "in-sync" with ones which manifested in the old version of the test, as well as make sense in general.

new(tests): EIP-5656/7692 - use new marker to EOF-ize MCOPY test (2)

---

converted-ethereum-tests.txt
docs/CHANGELOG.md
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_tools/tests/test_code.py
tests/frontier/opcodes/test_all_opcodes.py

define lists of opcodes by fork and verify that they are actually supported only at the allowed forks
PR https://github.com/ethereum/tests/pull/1399

feat(tests): test all opcodes by fork

---

.github/actions/build-fixtures/action.yaml
.github/workflows/coverage.yaml
README.md
docs/CHANGELOG.md
docs/getting_started/executing_tests_command_line.md
docs/getting_started/quick_start.md
pyproject.toml
pytest-framework.ini
pytest.ini
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/solc.py
src/pytest_plugins/filler/tests/conftest.py
src/pytest_plugins/filler/tests/test_solc.py
tox.ini
whitelist.txt

- Adds a new plugin `solc` (most logic is refactored from `fill` to this plugin).
- Adds a new command-line flag `--solc-version=x.y.z` to `fill`
- Adds logic to install the version specified by the flag via `solc-select` automatically when `fill` is called.
- If `--solc-bin` is specified, `solc-select` is not used; old behavior remains.
The only difference is that by default (if neither of the solc flags are specified), the first solc in the path is no longer taken; rather the default version of solc as currently specified by the plugin is used via `solc-select` (0.8.24).
`solc-select` has proven to be reliable if configured correctly. Unfortunately, the config is lost when switching venv; this avoids this pitfall.
#604 #618

feat(fill): add solc plugin and automatic installation of solc

---

src/cli/gen_index.py
src/pytest_plugins/consume/consume.py

This PR fixes two bugs for `consume`'s `--input` flag with remote URLs:
1. For the case that the tarball is already downloaded and extracted to `cached_downloads`.
2. And a pre-`.meta` directory release (such as v3.0.0), cf #721.
This fixes this behaviour, for example:
```
consume direct --input https://github.com/ethereum/execution-spec-tests/releases/download/v3.0.0/fixtures_stable.tar.gz
``` 
#721

fix(consume): couple of bugfixes when --input is a release tarball

---

uv.lock

Updates the `uv.lock` file. This is necessary because:
- #777 introduced a `uv.lock` file
- #772 modified dependencies for solc (added an upper bound <2.0.0), which was not taken into account for in #777.
#777, #772.

chore: update uv.lock for updated solc deps

---

.github/configs/feature.yaml
docs/CHANGELOG.md

This PR aims to reduce the number of tests in our fixture releases. Where the new strategy includes the following:
- `fixtures_stable`: contains mainnet so only Cancun.
- `fixtures_develop`: contains mainnet plus Prague.
- `fixtures_legacy`: contains all forks pre-mainnet.
The mainnet, development and legacy fork variables within `feature.yaml` can be updated to reflect these changes in the future.
Tox should still fill all tests for all forks to assert the framework is not broken.
N/A

chore(ci): remove redundant tests for fixture releases.

---

tests/prague/eip7692_eof_v1/tracker.md

- Update some entries which have been migrated from ethereum/tests.
- Add new cases found by fuzzing.
- Fix typos.

chore(tests): update EOF tests tracker

---

src/ethereum_test_vm/opcode.py

DATALOAD pushes an item, same as RETURNDATALOAD and CALLDATALOAD, not sure why I missed this when doing the recent DATALOADN fix. I think now the 4 data opcodes are ok
I noticed this after getting deep into the `Bytecode.__add__` algorithm for calculating max stack height. I have a case which it seems to be mishandling (no jumps or callfs!), but I have so far been unable to fix the algorithm. If I give up, I'll just post an issue to reproduce the problematic case.
NA

fix(fw): DATALOAD pushed_stack_items

---

tests/prague/eip7692_eof_v1/eip6206_jumpf/test_nonretruning_validation.py
tests/prague/eip7692_eof_v1/tracker.md
whitelist.txt

Add new EOF validation tests where the a section marked returning/non-returning does not match the reality.
https://github.com/ipsilon/eof/issues/146

new(tests): EOF: tests for invalid non-returning sections

---

src/ethereum_test_specs/base.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/eof.py
src/ethereum_test_specs/state.py
src/ethereum_test_specs/tests/test_expect.py
src/ethereum_test_specs/tests/test_fixtures.py
src/ethereum_test_tools/tests/test_code.py
src/pytest_plugins/filler/filler.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_migrated_valid_invalid.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_order.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
tests/prague/eip7692_eof_v1/eip4750_functions/test_code_validation.py

`EOFTest` spec base now automatically checks for duplicate containers during the fill process.
The simple approach is to define a global variable that contains all containers filled up until now, and fail the test in the case that the test currently being generated has already been seen.
An exception to this rule is on `EOFStateTest` specs because these tests can generate multiple state tests on the same container, but in the case of a simple EOF test, if the container has already been seen, the test is gracefully skipped.
All of the following tests were detected as duplicates and only one of them is left now in code.
- tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py::test_version_validation[fork_CancunEIP7692-eof_test-version_1], …

fix(tests): EOF - Remove duplicate container tests, automatically check for duplicates

---

docs/CHANGELOG.md
src/pytest_plugins/forks/forks.py

Don't print the following if we're generating fixtures for a fork under development:
```
Only executing tests with stable/deployed forks: Specify an upcoming fork via --until=fork to add forks under development.
```
None.

fix(forks): small pytest session header fix with dev forks

---

src/ethereum_test_vm/bytecode.py
src/ethereum_test_vm/tests/test_vm.py

Split out of #785 with a unit test added.
I've noticed that the algorithm might not handle all cases well, and I am proposing an alternative. I've left all my overly verbose comments in the code to illustrate the train of thought, as this has been quite hard to grasp the original code intentions (maybe there has been an easier fix hidden from my sight there).
n/a

 fix(fw): max stack height calculation in __add__ 

---

tests/prague/eip7702_set_code_tx/test_set_code_txs.py

This PR tests interaction between EIP-7702 (Set EOA account code) and EIP-1153 (transient storage). 
The call chain contract will call into the EOA, which will then SSTORE in slot 1 the TLOADed value of transient slot 2, and then TSTORE the value 3 in transient slot 2. Then, it will return to the call chain contract and it will now call into the account which the EOA is delegated to and thus re-run the same code. The transient storage should be empty, thus the storage should stay empty.
This is parametrized by:
- It will perform both CALL and STATICCALL from the chain call contract EDIT: I should remove STATICCALL since we cannot SSTORE
- The contract which is called first (EOA or the code contract) is also switched
TODO: cleanup
None

new(test): EIP-7702 + EIP-1153: test that TransientStorage stays at correct address

---

tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

…e subcontainer twice
This test should test that its valid for two EOFCreates to reference the same subcontainer
@shemnon removed a superfluous case from geth that would fail with this test: https://github.com/MariusVanDerWijden/go-ethereum/pull/56

new(tests): EOF - EIP-7620: EOFCREATE referencing the same subcontainer twice

---

tests/prague/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Signed-off-by: Danno Ferrin <danno@numisight.com>
Test dangling data inside a subcontainer

new(tests): EOF - EIP-7620: Dangling data in subcontainer test

---

src/ethereum_test_types/eof/v1/__init__.py
src/ethereum_test_types/tests/test_eof_v1.py

Adds `initcode_prefix` parameter to `Container.Init` in order to add executable bytecode that must be appended before `EOFCREATE[0](0, 0)` in the resulting container's code section.
None

fix(fw): EOF - Accept `initcode_prefix` on EOF `Container.Init`

---

docs/CHANGELOG.md
src/ethereum_test_tools/code/generators.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

- Fixes some issues with EIP-7702 tests when parametrized to EOF variants in `PragueEIP7692` fork.
- Fixes `Conditional` code generator in EOF mode.
We should be able to release a new EOF tests release after this is merged.
None

fix(tests): Fix Existing EOF + EIP-7702 Tests

---

docs/CHANGELOG.md
docs/gen_test_case_reference.py
docs/templates/base.md.j2
docs/templates/directory.md.j2
docs/templates/function.html.j2
docs/templates/function.md.j2
docs/templates/function_parameter_datatable.html.j2
docs/templates/markdown_header.md.j2
docs/templates/module.md.j2
docs/writing_tests/exception_tests.md
docs/writing_tests/index.md
mkdocs.yml
src/ethereum_test_tools/utility/versioning.py
src/pytest_plugins/filler/gen_test_doc/__init__.py
src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py
src/pytest_plugins/filler/gen_test_doc/page_props.py
tests/prague/__init__.py
tox.ini
whitelist.txt

This is a rewrite of the automatic test case doc generation as a pytest plugin (as apposed to a standalone script). A preview is available at https://ethereum.github.io/execution-spec-tests/pr-801-preview.
1. Test module pages: Added a table that provides and overview of its test functions, e.g., [tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add](https://ethereum.github.io/execution-spec-tests/pr-801-preview/tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add/).
2. Added test function pages which include a table which tries to give an overview of its parametrized test cases, e.g., [tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add::test_valid](https://ethereum.github.io/execution-spec-tests/pr-801-preview/tests/prague/eip2537_bls_12_381_precompiles/test_bls1 …

feat(docs): re-write test gen doc flow with pytest plugin

---

.github/workflows/docs_main.yaml
.github/workflows/docs_tags.yaml

**#792 would also fix this; we can disregard this PR if #792 gets merged first/quickly**
#801 re-implements the "Test Case Reference" generation script as a pytest plugin (based on top of `fill`). As the forks plugin (and others; didn't check) require a `t8n` tool in the path, we need to provide one, even if it's not strictly necessary to build docs.
This is a tricky subject. I'm not a fan of requiring a t8n tool to collect tests/build doc, but if we use t8n properties in test markers or other places, it's not easy to avoid.
#801

fix(docs,ci): add build-evm-base to docs deploy workflows

---

docs/CHANGELOG.md
src/cli/gentest.py
src/ethereum_test_rpc/__init__.py
src/ethereum_test_rpc/rpc.py
src/ethereum_test_rpc/types.py
src/ethereum_test_tools/rpc/__init__.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py

Moves all functionality included in `ethereum_test_tools.rpc` to a new library called `ethereum_test_rpc`, and also adds some other new functionality.
None

refactor(tools,rpc): Move `ethereum_test_tools.rpc` to `ethereum_test_rpc`

---

tests/prague/eip7692_eof_v1/eip7069_extcall/helpers.py
tests/prague/eip7692_eof_v1/eip7069_extcall/test_gas.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/prague/eip7692_eof_v1/eip7620_eof_create/test_gas.py
tests/prague/eip7692_eof_v1/gas_test.py

EOFCREATE gas testing using the "Op.GAS harness" used in #771.
~I'm pushing early to signal the [fix(fw): max stack height calculation in `__add__`](https://github.com/ethereum/execution-spec-tests/commit/acee5dab6abac2c8293d3951b5a8613ecf0e0729). The new bytecodes used in the new tests didn't have the correct autocalculated max stack height. After some digging, I've noticed that the algorithm might not handle all cases well, and I am proposing an alternative. I've left all my overly verbose comments in the code to illustrate the train of thought, as this has been quite hard to grasp the original code intentions (maybe there has been an easier fix hidden from my sight there).~ EDIT: the max stack height fix split out to https://github.com/ethereum/execution-spec-tests/pull/810, merge 810 …

new(tests): EOF - EIP-7620 EOFCREATE gas testing

---

tests/cancun/eip1153_tstore/test_tstorage_clear_after_tx.py

The runtime code of the TSTORE test is not valid EOF, it requires a
terminating instruction.

fix(tests): fix TSTORE EOF variant test

---

tests/prague/eip7692_eof_v1/eip6206_jumpf/test_nonreturning_validation.py
tests/prague/eip7692_eof_v1/tracker.md

Recently some confusion was reported whether what are "non-returning instructions" mentioned in the test. It looks like a mental shortcut, and can also raise questions like "is RETURNCONTRACT or RETURN one?". This clarifies this and also adds some coverage for such instructions (which are basically "terminating but not RETF or JUMPF-to-returning").
Also fixes a typo in that file's name.
NA

new(tests): EOF - EIP-6206: clarify "non-returning instruction"

---

docs/dev/docs.md
docs/dev/interactive_usage.md
docs/dev/test_actions_locally.md
docs/getting_help/index.md
docs/getting_started/installation_troubleshooting.md
docs/library/pytest_plugins/index.md
docs/library/pytest_plugins/navigation.md
docs/navigation.md
whitelist.txt

Adds:
- a new problem/solution to docs/getting_started/installation_troubleshooting.md, thanks for the info @gurukamath!
- styles docs/getting_started/installation_troubleshooting.md using admonitions
- fixes code blocks in docs/dev/test_actions_locally.md
- fixes navigation for docs/library/pytest_plugins.
- docs/library/pytest_plugins/navigation.md was deleted as defining nav menus in subdirs is no longer supported 
- fixes name of testing discord channel, thanks for the heads up @raxhvl!
- adds a new section describing how to work interactively with EEST packages docs/dev/interactive_usage.md
None

fix(docs): miscellaneous improvements to troubleshooting, navigation, styling

---

src/pytest_plugins/pytest_hive/pytest_hive.py

Fix a small regression that crept in when introducing the concurrency plugin, #824
We need some basic smoke testing for `consume` asap.
#824

fix(consume): use the session_temp_folder introduced in #824

---

.github/actions/setup-uv/action.yaml
.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
pyproject.toml
src/ethereum_test_base_types/base_types.py
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_fixtures/tests/test_blockchain.py
src/ethereum_test_tools/__init__.py
src/ethereum_test_types/__init__.py
src/ethereum_test_types/helpers.py
src/ethereum_test_types/tests/test_transactions.py
src/ethereum_test_types/types.py
src/ethereum_test_vm/bytecode.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip5656_mcopy/test_mcopy.py
tests/constantinople/eip1014_create2/test_create_returndata.py
tests/prague/eip2537_bls_12_381_precompiles/conftest.py
tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_extcode.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py
tox.ini
uv.lock

- Use `ethereum_types` instead of `ethereum.base_types`
- Replace uses of `ethereum.crypto.hash.keccak256` with internal function that directly uses `coincurve`
- Refactor some methods to return `Bytes` in order to use `Bytes.keccak256`
Bonus:
- Bump uv version in ci.
- Configure tox-uv (in tox.ini) to use uv.lock.
- Configure runner as ubuntu-latest (this was bumped to ubuntu-24.04 https://github.com/actions/runner-images/commit/ae99c16b0cf27c0cca7ef0b08e7bcf13c33f6cfa)
- 
- Follow-up issue: #852 
- ethereum/execution-specs#1007

fix(fw,tests): Replace `ethereum.base_types` with `ethereum-types`, replace `ethereum.crypto.hash`

---

.github/workflows/coverage.yaml
.github/workflows/docs_main.yaml
.github/workflows/docs_tags.yaml
.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml

#792 changed the images used from `ubuntu-latest` to `ubuntu-24.04` (latest pointed to `ubuntu-22.04` at the time). This PR reverts this change as latest has been bumped to `ubuntu-24.04` in Github Actions in https://github.com/actions/runner-images/commit/ae99c16b0cf27c0cca7ef0b08e7bcf13c33f6cfa.
Using `ubuntu-latest` simplified the need to use `-P` to map the image correctly. The following is from the never published and now defunct docs:
```
"Specifying the `ubuntu-24.04` docker image"
[#792](https://github.com/ethereum/execution-spec-tests/pull/792/) made EELS the default `t8n` tool. Our Github workflows were changed to use the `ubuntu-24.04` docker image which has OpenSSL 3.0.7, required by EELs to have RIPEMD160 support (used by the precompile at `0x03`). As of 2024-09-30 …
```

chore(ci): change image from ubuntu-24.04 to ubuntu-latest

---

README.md
SECURITY.md
docs/index.md

- Add a SECURITY.md
- Add short comments to the README and to the html landing page nudging people to the bounty program.
None

feat(docs): add a `SECURITY.md` describing how to report vulnerabilities 

---

converted-ethereum-tests.txt
tests/prague/eip7692_eof_v1/eip4750_functions/test_code_validation.py

This migrates tests for unreachable code sections from
EOFTests/efValidation/unreachable_code_sections_.json
but also complements test cases with focus on containers where
each section is referenced by some section but some are not reachable
from section 0.

new(tests): EOF - EIP-4750: unreachable code sections

---

src/ethereum_test_vm/opcode.py

Just a minor issue I've noticed. It didn't affect any bytecode generation, but fixing anyway
NA

fix(fw): EOF - Fix EXCHANGE's data_portion_length

---

.github/workflows/docs_tags.yaml
docs/CHANGELOG.md

Fixes a bug within the `Deploy Docs Tags` workflow trigger.
For pre-releases such as `verkle@v0.0.4`, this workflow was triggered deploying and publishing the docs for this tag.
Please see the docs: https://ethereum.github.io/execution-spec-tests/verkle@v0.0.4/
Our check to trigger this workflow was `v*` so any pre-release starting with `v` would always trigger this docs deployment. The past 3 verkle releases did not trigger this as they failed at the docs build step.
Open to changing to always build and deploy the docs for all releases, including pre-releases.
N/A

bug(ci): fix deploy docs tags workflow trigger

---

docs/dev/test_actions_locally.md
docs/getting_started/installation_troubleshooting.md
docs/writing_tests/verifying_changes.md
src/pytest_plugins/filler/filler.py
whitelist.txt

Docs:
- Improve "Running Github Actions Locally" developer docs section.
- Add RIPEMD160 precompile problem to "Installation Troubleshooting".
- Also snuck in: Improve tox commands in "Verifying Changes" (`tox` -> `uvx --with=tox-uv tox`).
Filler:
- Set `interpolation` to `None` in `configparser.ConfigParser(interpolation=None)` to avoid issues parsing the `GITHUB_REF` in when workflows are ran with `nektos/act`.
#792

feat(docs,filler): add info about ripemd160 & update github actions

---

docs/javascripts/site.js
docs/stylesheets/custom.css
docs/templates/function.html.j2
docs/templates/function_parameter_datatable.html.j2
mkdocs.yml

Fixes:
-  Issues with custom fork and test filters.
-  Resolved a bug causing the datatable to break when changing entries per page.
Enhancements:
-  Upgraded jQuery from 3.5.1 to 3.7.1.
-  Upgraded DataTables from 1.10.21 to 2.1.7.
-  Migrated to minified scripts / css where possible for faster page load.
-  Added a plugin for searchable dropdowns.
#842

🐞 fix: Datatable custom filter and other goodies

---

docs/javascripts/site.js
docs/stylesheets/custom.css
docs/templates/function_parameter_datatable.html.j2

A native button for selecting visible column has been added to the parameter test cases dataTable. This PR makes the styling of the button consistent with the existing UI.

✨ feat: Styling of native dataTable buttons

---

docs/CHANGELOG.md
eels_resolutions.json
pytest-framework.ini
pytest.ini
src/pytest_plugins/eels_resolver.py
src/pytest_plugins/filler/tests/test_filler.py
whitelist.txt

Currently, as EEST doesn't configure the EELS resolver, it takes the HEAD of execution-specs `master` for all forks. This exposes EEST to any issues that make it to execution-specs `master`. This PR aims to eliminate this risk and improve reporting the EELS version used to fill forks: 
- Add a config file `eels_resolutions.json` that pins the ethereum/execution-specs main branch reference for deployed and Prague forks, see the [ethereum-spec-evm-resolver README](https://github.com/petertdavies/ethereum-spec-evm-resolver/tree/ed7dbce2e64c57812821d96297b6e0efc2967802?tab=readme-ov-file#example-config).
- Use the `eels_resolutions.json` in `fill` and the framework tests automatically by setting the `EELS_RESOLUTIONS_FILE` envvar in an `eels_resolver` plugin. The value will not be clobbered, …

feat(fill): add a config file for the eels resolver to pin versions

---

tests/verkle/eip4762_verkle_gas_witness/test_balance.py
tests/verkle/eip4762_verkle_gas_witness/test_calls.py
tests/verkle/eip4762_verkle_gas_witness/test_codecopy_generic.py
tests/verkle/eip4762_verkle_gas_witness/test_coinbase_fees.py
tests/verkle/eip4762_verkle_gas_witness/test_contract_execution.py
tests/verkle/eip4762_verkle_gas_witness/test_creates.py
tests/verkle/eip4762_verkle_gas_witness/test_extcodesize.py

This PR contains fixes to pass stricter exhaustive checks.
Must use https://github.com/gballet/go-ethereum/pull/505 for filling.

witness: exhaustive check fixes

---

src/ethereum_test_specs/blockchain.py
src/ethereum_test_types/verkle/types.py
tests/verkle/eip4762_verkle_gas_witness/test_balance.py
tests/verkle/eip4762_verkle_gas_witness/test_calls.py
tests/verkle/eip4762_verkle_gas_witness/test_codecopy_ext_precompile.py
tests/verkle/eip4762_verkle_gas_witness/test_codecopy_generic.py
tests/verkle/eip4762_verkle_gas_witness/test_coinbase_fees.py
tests/verkle/eip4762_verkle_gas_witness/test_contract_execution.py
tests/verkle/eip4762_verkle_gas_witness/test_creates.py
tests/verkle/eip4762_verkle_gas_witness/test_extcodesize.py
tests/verkle/eip4762_verkle_gas_witness/test_selfdestruct.py
tests/verkle/eip4762_verkle_gas_witness/test_transfer.py

The previous exhaustive witness check was one way (iterating through the actual witness only). This PR expands upon this to fully check the expected/actual witness together.
N/A

feat(verkle): add two-way exhaustive witness checks

---

tests/verkle/eip4762_verkle_gas_witness/test_creates.py

This PR adds tests that cover contract creation via tx or `CREATE*` instructions with insufficient gas which generate partial witnesses.

new(tests): eip-4762 contract creations with insufficient gas

---

tests/verkle/eip4762_verkle_gas_witness/test_extcodehash.py

This PR adds tests to check for partial witnesses generated by insufficient gas while executing `EXTCODEHASH` instruction.

new(tests): eip-4762 EXTCODEHASH with insufficient gas

---

tests/verkle/eip4762_verkle_gas_witness/test_codecopy_generic.py

This PR enables tests to cover partial witness generation for `(EXT)CODECOPY` when there's insufficient gas.

new(tests): eip-4762 (EXT)CODECOPY with insufficient gas

---

docs/CHANGELOG.md
docs/dev/docs.md
docs/gen_test_case_reference.py
docs/javascripts/site.js
docs/stylesheets/custom.css
docs/templates/base.md.j2
docs/templates/function.html.j2
docs/templates/function.md.j2
docs/templates/function_parameter_datatable.html.j2
docs/templates/module.md.j2
mkdocs.yml
src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py
src/pytest_plugins/filler/gen_test_doc/page_props.py
tests/frontier/opcodes/test_dup.py
tox.ini
whitelist.txt

The test function parameter tables introduced in #801 try to only show "relevant" test function parameters. It's a nice idea, but I think this obfuscates the fact that we always parametrize by fork and potentially fixture type, so I think it's better to be transparent about that but limit the number of entries displayed by using additional select elements with reasonable defaults.
Preview available at [pr-842-preview](https://ethereum.github.io/execution-spec-tests/pr-842-preview/).
Example:
- Follows-up from:
-  #801
Includes:
- #853 
- #871 
Done:
- #813 
- Generate test function parameters for all forks by running `fill` with `--until={GENERATE_UNTIL_FORK}` instead of `--fork=...`.
- Specify a target fork that can be used to display a default set of parameters …

feat(docs): include all parameters in test parameter datatables

---

pytest-execute-hive.ini
pytest-execute.ini
pytest.ini
src/ethereum_test_fixtures/base.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/execute/execute.py
src/pytest_plugins/execute/rpc/hive.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/pytest_hive/pytest_hive.py
src/pytest_plugins/shared/execute_fill.py
src/pytest_plugins/solc/solc.py

- Moves some common pytest fixtures and hooks to a new shared plugin `pytest_plugins.shared.execute_fill`.
- Removes some duplicate code and unused fixtures from the `execute` plugins and helper functions.
Mario, could be easier/faster to review each commit individually, they're quite small.
#686

refactor(execute,fill): share common plugin functionality

---

tests/verkle/eip4762_verkle_gas_witness/test_sload.py
tests/verkle/eip4762_verkle_gas_witness/test_sstore.py

This PR adds tests for partial witness generation in SSLOAD/SSTORE instructions generated by insufficient gas.

eip4762: SSTORE/SLOAD insufficient gas tests

---

src/cli/hasher.py

Small fix to the `hasher` command to skip `.meta` folder in the fixtures folder.
None

fix(cli): Fix hasher, skip `.meta`

---

src/ethereum_test_types/tests/test_types.py
src/ethereum_test_types/types.py

We see this check done by ethereumjs t8n that actually after PoS, ommers root is required to be a has of empty list. 
But pyspec passes 0 padded hash by default. only ethereumjs does this check. this seems to only be related to ParentUncleHash field.

feat(pytests): OmmersRoot is EmptyOmmersRoot by default instead of 0

---

docs/CHANGELOG.md
pyproject.toml
pytest.ini
src/cli/pytest_commands/fill.py
src/cli/tests/test_pytest_fill_command.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/forks/forks.py
uv.lock

Changes the terminal output to emphasize that `fill` did not test the client; rather it generated fixtures that can be executed against a client.

feat(fill): emphasize that no tests were executed during a fill pytest session

---

.github/configs/feature.yaml

Updates `eip7692-osaka` feature configuration to also fill tests under `tests/prague`, in order to fill tests that do cross-functional testing on Prague EIPs too.
None

fix(github): Fix `eip7692-osaka` to also fill `tests/prague`

---

tests/osaka/eip7692_eof_v1/eip4750_functions/helpers.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py
whitelist.txt

Add a test to cover cases where stack would not overflow but CALLF stack
reservation rules would cause a revert.

new(tests): EOF - EIP-4750: Stack  validation in CALLF

---

docs/dev/test_actions_locally.md
whitelist.txt

@winsvega tested the docs. This PR deals with the feedback from #904.
Resolves #904

fix(docs): fix/add test github actions locally page

---

tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_migrated_valid_invalid.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

Correct an erroneous test where a rule was applied to the operand stack that was meant for the return stack

bug(tests) - CALLF rule #4 applies to return stack, not operand stack

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_execution.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_extcode.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

- Basic EOF execution tests migrated from ethereum/tests:
`EIPTests/StateTests/stEOF/stEIP3540/EOF1_Execution.json` ([filler source](https://github.com/ethereum/tests/blob/develop/src/EIPTestsFiller/StateTests/stEOF/stEIP3540/EOF1_ExecutionFiller.yml))
- Extend execution test of legacy invoking `EXTCODE*` instruction on EOF with the case from ethereum/tests.

new(tests): basic EOF execution tests

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py

The RJUMP/RJUMPI/RJUMPV execution tests were actually migrated by @shemnon in https://github.com/ethereum/execution-spec-tests/pull/581
This adds just one more basic RJUMPI/RJUMP test.

new(tests): EOF - EIP-4200: migrate remaining RJUMP* execution tests

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

Use pytest parametrize to combine very similar tests for `CALLF` execution.

refactor(tests): EOF - EIP-4750: parametrize CALLF execution tests

---

tests/osaka/eip7692_eof_v1/eip6206_jumpf/helpers.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_execution.py

Signed-off-by: Danno Ferrin <danno@numisight.com>
Just like CALLF, JUMPF has a stack overflow by rule check that
tests were not tripping.

new(tests): EOF - EIP-6206: Add stack overflow by rule check to JUMPF

---

.github/actions/build-evm-client/evmone/action.yaml
.github/workflows/coverage.yaml

Enable coverage script on any test .py files changes:
if no new lines in converted-ethereum-tests.txt, then seek for .py files with tests and compare the coverage
from before and after PR, otherwise it compares the coverage from test repo and .py produced tests as before.
Script is reworked. use uv to run fill correctly
remove retesteth to simplify the script
use changed files github macro to detect changed files
Demo: https://github.com/ethereum/execution-spec-tests/pull/841
Rebase of: https://github.com/ethereum/execution-spec-tests/pull/707

feat(coverage): Enable coverage on any test change (rebased with uv)

---

.github/configs/evm.yaml
src/ethereum_test_specs/blockchain.py
src/ethereum_test_types/verkle/tests/test_verkle_witness.py
src/ethereum_test_types/verkle/types.py
src/evm_transition_tool/types.py

Add the `parent_root` to the witness in the verkle fixtures.
Fixes a bug in the `verkle_proof` where the `depthExtensionPresent` field was creating non-zero padded values in some instances. These are now zero padded.
Requires this commit when fill with geth: https://github.com/spencer-tb/go-ethereum/commit/1b5cd40f011923efad391c4115fb333db23a3826#diff-06c63748460168e12cbf03984f37c000908e0b7ff50ca0dfe28db286a1dfd36eR395
N/A

feat(verkle): add parent root to witness

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

Add tests implementing fibonacci sequance and factorial using recursive CALLF instructions.
They were originally contributed to ethereum/tests by @hugo-dc in https://github.com/ethereum/tests/commit/89c2147b9b7495421eecb4443012da0fc7d5a3a4.
I'm migrating the tests separately because they are nice examples.

new(tests): EOF - EIP-4750: add fibonacci and factorial tests for CALLF

---

src/cli/eofwrap.py

Fixes a merge issue from #832, when merged after #896.
`requests_root` header field is removed in favor of `requests_hash`, but this field should not be manually overridden by `eofwrap` anyway since it's calculated by t8n automatically, and trying to force the value (or remove it by placing `None` instead) could render the block invalid.
Fix is to remove all EIP-7685 modifications in `eofwrap`.
Skipping changelog since I think it's not necessary.
None

fix(cli/eofwrap): fix merge issue (EIP-7685 updates)

---

src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py
src/pytest_plugins/consume/hive_simulators/rlp/conftest.py
src/pytest_plugins/execute/rpc/hive.py

EEST's Hive simulators are now organized in Hive as:
```
simulators/ethereum/eest
├── consume-engine
│   └── Dockerfile
├── consume-rlp
│   └── Dockerfile
└── execute
└── Dockerfile
```
This PR: 
- Renames the test suite names used in `hiveview` to better reflect this (current status in screenshot below).
- Uses the value provided on the consume command-line for the input value displayed in `hiveview`'s test report "Description" for the help on how to reproduce the commands.
None

chore(consume): rename test suites

---

src/ethereum_clis/clis/execution_specs.py
src/ethereum_clis/transition_tool.py

There appears to be a brief delay between the Unix socket file being created and connections being accepted on the socket. This may be the cause of sporadic CI failures with the EELS daemon.
This PR adds a check to `start_server()` to see if the EELS daemon has actually started accepting connections.
Resolves #852

fix(ethereum_clis): Retry on connection error in `_evaluate_server()` for EELS daemon

---

src/cli/pytest_commands/consume.py

Fixes the duplication of user-specified pytest flags to `consume` hive commands.
For example,
```
consume engine --collect-only -q
```
was actually executed as
```
uv run pytest --collect-only -q -c pytest-consume.ini -p pytest_plugins.pytest_hive.pytest_hive src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
```
This often didn't have any side effects, but, in the above example, ran the command effectively as:
```
consume engine --collect-only -qq
```
which silenced the output of node ids from pytest, i.e,. the following was output:
```
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py: 3
```
instead of the expected output
```
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py::test_via_engine[tests/istanbul/eip1344_chainid/test_chain …
```

fix(cli/consume): fix duplication of user-provided pytest flags

---

docs/CHANGELOG.md
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Add test where a single transaction includes as many delegations as the max block gas allows:
- With or without balance in the auth signer accounts (empty vs non-empty account in state)
- With 20 million gas (to execute test on live networks) or 120 million gas
None

new(tests): EIP-7702: Add many-delegations test

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): EOF - EIP-7692: migrate `CALLF` execution tests

---

src/ethereum_test_vm/opcode.py
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
whitelist.txt

Continues #833 with some tests with JUMPF to non-returning functions. I got stuck on JUMPF to returning functions so I'm making this little step first.
na

new(tests): EOF - EIP-4200 EIP-6206 RJUMPI with JUMPF

---

src/pytest_plugins/eels_resolver.py

While debugging the eels-resolver to use a file and incorporate `Osaka`, I realized that the plugin was running after the fill `pytest_configure` so the resolver's help (to get the supported forks) was being run without the environment variables set.
This is fixed by adding a `@pytest.hookimpl(tryfirst=True)` decorator to the `pytest_configure` in the `eels_resolver` plugin. 
None

fix(plugins/eels_resolver): add `tryfirst`

---

src/ethereum_test_base_types/composite_types.py

Print hint string if assigned in Storage class
Usage:
```
Op.SSTORE(post.store_next(0, hint="expected_result"), Op.MLOAD(0))
...
post={
runner_contract: Account(
storage=post,
)
},
```
Surpasses https://github.com/ethereum/execution-spec-tests/pull/807

feat(base_types): storage key hint in Storage class

---

docs/CHANGELOG.md
src/ethereum_test_vm/bytecode.py

Fixes `Bytecode` equality comparison method to take other properties into account when comparing against some other `Bytecode` object.
The issue surfaced when I tried to implement tests for EIP-5920 that contains the `PAY` opcode, which collides with the `EXTDELEGATECALL` opcode for EOF. When both opcodes were included in the same Enum, it seems like this class internally performs an optimization that compares all items and reuses instances that return `__eq__() == True`, which lead to the `Op.PAY` being equal to the value assigned to `Op.EXTDELEGATECALL`.
None.

fix(vm): `Bytecode` comparison

---

tests/verkle/eip6800_genesis_verkle_tree/test_storage_slot_write.py

This PR adds a tests related to a disagreement found by the txfuzzer in devnet7 caused by underspec.
Despite, we'll fix the spec to clarify what to do in this case, this extra test is useful to catch regressions.
Note: I'm waiting for an extra EL client (apart from Geth) to pass this fixture, then I'll merge it.

verkle: add extra SSTORE test

---

docs/CHANGELOG.md
src/ethereum_clis/clis/besu.py
src/ethereum_clis/clis/execution_specs.py
src/ethereum_clis/transition_tool.py
src/ethereum_test_specs/state.py
whitelist.txt

Pass the `state_test` property to the t8n that support/require it.
In this PR the only updated tool is EELS, and the information is passed as an URL parameter, which is then converted to a CLI argument on the receiving end.
Requires:
- https://github.com/ethereum/execution-specs/pull/1030
- https://github.com/petertdavies/ethereum-spec-evm-resolver/pull/5
None

feat(clis/transition_tool): Pass `state_test` to transition tool if supported

---

docs/CHANGELOG.md
src/pytest_plugins/filler/pre_alloc.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Simple test to verify that the code can be set for an account with a non-empty storage (In case account delegated previously, set some storage value, then reset its delegation to empty).
Also fixes the `pre.fund_eoa` method to consider the extra nonce bump that would realistically be required if an account removed its delegation.
None

new(tests): EIP-7702:  Set code of non-empty-storage account

---

README.md

Fix broken images links in README.md
None

chore(docs): fix broken images links in readme

---

tests/osaka/eip7692_eof_v1/__init__.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/__init__.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/__init__.py
tests/osaka/eip7692_eof_v1/eip4750_functions/__init__.py
tests/osaka/eip7692_eof_v1/eip5450_stack/__init__.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/__init__.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/__init__.py
tests/osaka/eip7692_eof_v1/eip7069_extcall/__init__.py
tests/osaka/eip7692_eof_v1/eip7480_data_section/__init__.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/__init__.py
tests/osaka/eip7692_eof_v1/eip7698_eof_creation_tx/__init__.py
tests/prague/__init__.py

- Adds a link to prague-devnet-5,
- Adds EOF EIP links and a top-level description of every EOF EIP included.
#956

feat(docs): add prague-devnet-5 link; add EOF EIP links/info

---

src/ethereum_test_vm/bytecode.py

Without this, I cannot fill eof tests with:
```
$ fill  --fork Osaka tests/osaka/eip7692_eof_v1/
...
___________________________________________________________ test_invalid_opcodes_after_stop[fork_Osaka-eof_test-terminating_opcode_STOP-opcode_OPCODE_0C] ___________________________________________________________
[gw3] linux -- Python 3.10.12 /home/user/sources/ethereum/execution-spec-tests/.venv/bin/python3
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py:141: in test_invalid_opcodes_after_stop
terminating_code = Bytecode(terminating_opcode)
src/ethereum_test_vm/bytecode.py:92: in __new__
raise TypeError("Bytecode constructor '__new__' didn't return an instance!")
E   TypeError: Bytecode constructor '__new__' didn't return an instance!
```
I think #932 …

fix(fw): allow Bytecode(Opcode)

---

pyproject.toml
uv.lock

This PR fixes [interactive usage of EEST with ipython](https://ethereum.github.io/execution-spec-tests/main/dev/interactive_usage/).
I tested this change on top of dac90491d0 from [`raxhvl/feat/make-test`](https://github.com/raxhvl/execution-spec-tests/tree/feat/make-test) cf #950: The interactive CLI command `uv run et make test` works without a problem with these changes, CC @raxhvl .
Here's the explanation from `pyproject.toml`:
```toml
"questionary @ git+https://github.com/tmbo/questionary@ff22aeae1cd9c1c734f14329934e349bec7873bc",
"prompt_toolkit>=3.0.48,<4",  # ensure we have a new enough version for ipython
```
This issue was introduced in #947

fix: upgrade questionary to allow compatbility with ipython

---

.github/actions/build-evm-base/action.yaml
.github/actions/build-fixtures/action.yaml
.github/configs/evm.yaml
.github/configs/feature.yaml
src/ethereum_test_vm/bytecode.py

Follows up #896 with a new build step which adds eofwrapped `ethereum/tests` to the EOF tests prerelease. Depends on #961 , hence opening as draft.
na

 feat(ci,eof): include eofwrap in EOF prerelease

---

eels_resolutions.json
src/pytest_plugins/forks/forks.py
uv.lock

This PR aims to get a clean fill of `./tests/prague` as of `prague-devnet-4` specs with this EELS Prague fork: 
https://github.com/ethereum/execution-specs/tree/forks/prague
#943

chore(fill): fix prague filling with EELS

---

tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Tests:
- Sending the transaction directly to the account that is clearing its delegation
- Set the delegation again in the same transaction and call the zero address (check that it was not added to the access list)
- Check that the max call stack is respected when delegated accounts are being used
@lightclient 
None

new(tests): EIP-7702: More delegation clearing tests

---

docs/CHANGELOG.md
docs/library/cli/et.md
docs/library/cli/index.md
src/cli/et/cli.py
src/cli/et/commands/__init__.py
src/cli/et/commands/clean.py
src/cli/et/make/cli.py
src/cli/et/make/commands/test.py
whitelist.txt

Introduces `uv run et clean`.
closes #976.

✨ feat(cli): et clean

---

docs/CHANGELOG.md
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_fixtures/tests/test_blockchain.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_rpc/types.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_types/types.py
src/pytest_plugins/execute/rpc/hive.py
tests/cancun/eip4844_blobs/test_blob_txs.py

Adds the required framework changes for EIP-7742 within pectra devnet-5.
Fills with the following EELS resolution change for Prague:
```json
"Prague": {
"git_url": "https://github.com/spencer-tb/execution-specs.git",
"branch": "forks/prague",
"commit": "857c3fa4d733535f32e9f17250d5790dd7ab5a76"
}
```
N/A

feat(fw,tests): EIP-7742: Framework changes

---

.github/configs/eels_resolutions.json
.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
tox.ini

This PR proposes an alternative to #995 to fix the current CI fails running the framework tests:
- `tox_verify` checks out ethereum/execution-specs.
- Added `.github/configs/eels_resolutions.json` which resolves forks to this local clone.
- `tox_verify` sets the `EELS_RESOLUTIONS_FILE` env var to `<WORKSPACE>/.github/configs/eels_resolutions.json`
- `tox.ini` uses the `EELS_RESOLUTIONS_FILE` env var (**(only) in the `framework` testenv**) if it has been set.
Improvements:
- It'd be nice to provide the ref as a config and use it for local, user runs, via the resolver too. If this is the preferred approach, I would do this in a follow-up PR.
#995.

fix(ci): use local eels

---

docs/CHANGELOG.md
tests/prague/eip7702_set_code_tx/spec.py
tests/prague/eip7702_set_code_tx/test_gas.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Addresses changes in https://github.com/ethereum/EIPs/pull/8969
Requires https://github.com/ethereum/execution-specs/pull/1042
@petertdavies 
None

fix(tests): EIP-7702: Remove delegation behavior of EXTCODE*

---

README.md

`README.md` had one working link and one broken link to the `installation_troubleshooting` page. This sets the broken one to match the working one.

fix(docs): fix link to installation troubleshooting in README

---

tests/frontier/opcodes/test_all_opcodes.py

Fixes a test broken by #933.
Contract creating transactions should be defined as `to=None` and not `to=b""`.
None

fix(tests): Fix `test_all_opcodes.py`

---

tests/osaka/eip7692_eof_v1/eip7069_extcall/test_calls.py
whitelist.txt

Since RIP-7212 has been in and out of Prague some clients have it activated when it should not be. Verify the precompile does nothing.

new(tests): EOF - EIP-7069: Test EOF calls to p256verify

---

.github/configs/evm.yaml
.github/configs/feature.yaml
eels_resolutions.json

Add EELS as the filler for any `pectra-devnet-5` release.
Removes the `pectra-devnet-3`/`pectra-devnet-4` evm release candidates.
N/A

chore(ci): update for `pectra-devnet-5`

---

docs/CHANGELOG.md
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/gas_costs.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
tests/prague/eip7623_increase_calldata_cost/__init__.py
tests/prague/eip7623_increase_calldata_cost/conftest.py
tests/prague/eip7623_increase_calldata_cost/helpers.py
tests/prague/eip7623_increase_calldata_cost/spec.py
tests/prague/eip7623_increase_calldata_cost/test_execution_gas.py
tests/prague/eip7623_increase_calldata_cost/test_transaction_validity.py
tests/shanghai/eip3860_initcode/test_initcode.py

Adds tests for [EIP-7623: Increase calldata cost](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7623.md).
Modifies `transaction_intrinsic_cost_calculator` that is returned by the fork objects to account for the extra intrinsic cost that the EIP adds.
Also a new parameter is added to the function in order to return different values depending on how the function is used:
- Return the minimum gas that the transaction requires to be included
- Return the gas cost that is deducted before the transaction starts execution
Some tests were broken because they needed a transaction to start with a deterministic amount of gas and also with a given calldata length.
Solution to most of these issues was to add an access list so the intrinsic gas cost exceeded the new floor data cost.
None

feat(forks,tests): Add EIP-7623

---

docs/CHANGELOG.md
src/ethereum_clis/clis/besu.py
src/ethereum_clis/transition_tool.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/helpers.py
src/ethereum_test_specs/state.py

Allow tests marked as slow (with `@pytest.mark.slow`) to have a higher timeout when making a request to the t8n server.
I was writing a test to verify the maximum discount BLS multi-scalar-multiplication and it takes the t8n server 30 seconds to respond, which exceeds the 20 second timeout that is hard-coded by default.
None

feat(clis,specs): Tests marked as `slow` have greater t8n server `timeout`

---

src/ethereum_test_forks/forks/forks.py
tests/prague/eip2537_bls_12_381_precompiles/spec.py
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1mul.py
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g2mul.py
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_precompiles_before_fork.py

This is a set of minimal changes that removes the BLS G1/G2 MUL precompiles (EIP-2537). All existing tests for MULs are redirected to MSMs because these are ABI and gas equivalent (main reason for the spec change).
You can also notice that we had more tests for MULs than for MSMs meaning there were test cases missing for MSMs.
I have filled these tests with modified evmone.
EIP-2537 update: https://github.com/ethereum/EIPs/pull/8945

chore(tests): EIP-2537: remove BLS MUL precompiles (MVP)

---

tests/prague/eip7702_set_code_tx/spec.py
tests/prague/eip7702_set_code_tx/test_invalid_tx.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Updates the tests to use a u256 chain ID in 7702 set code txs.
- ethereum/EIPs#9143
- Note this counter proposal to #9143: ethereum/EIPs#9152
- ethereum/execution-specs#1057
Fills using:
```
fill tests/prague/eip7702_set_code_tx/ --fork=Prague -n auto
```
with the eels resolutions file:
```json
{
"Prague": {
"git_url": "https://github.com/danceratopz/execution-specs.git",
"branch": "eip-7702-chain_id-u256",
"commit": "febb39764b8760715136981649773a1c48e98f8e"
}
}
```

chore(tests): EIP-7702: update auth.chainid in set code txs to u256

---

src/ethereum_test_specs/blockchain.py

The `vkt` object was not being properly initialized when generating a blockchain engine test.
This PR fixes it by copying the initialization lines from the normal blockchain test generation.
None

fix(specs): Fix verkle blockchain engine test generation

---

docs/CHANGELOG.md
docs/writing_tests/test_markers.md
src/pytest_plugins/__init__.py
src/pytest_plugins/forks/__init__.py
src/pytest_plugins/forks/forks.py
src/pytest_plugins/forks/tests/test_covariant_markers.py
src/pytest_plugins/forks/tests/test_fork_parametrizer_types.py

This PR introduces a new decorator called `fork_covariant_parametrize`.
The goal of the decorator is to be able to dynamically parametrize a test depending on which fork the tests are being filled.
This is done using a custom function that is passed to the decorator, which will then be executed once per fork that the test is being filled with.
It allows to dynamically create a different amount of test cases per fork (Useful for EIP-4844 tests which are being modified by fork now).
```python
import pytest
from pytest_plugins import fork_covariant_parametrize
def covariant_function(fork):
return [[1, 2], [3, 4]] if fork.name() == "Paris" else [[4, 5], [5, 6], [6, 7]]
@fork_covariant_parametrize(parameter_names=[
"test_parameter", "test_parameter_2"
], fn=covariant_function) …
```

feat(pytest/plugins): Fork covariant parametrize

---

tests/osaka/eip7692_eof_v1/eip7069_extcall/test_gas.py

**Fix Typo in `test_gas.py`**
This pull request corrects a typo in the `test_gas.py` file. Specifically, the word "comsumption" was corrected to "consumption" in the comment section.
- **File Modified:** `tests/osaka/eip7692_eof_v1/eip7069_extcall/test_gas.py`
- **Summary of Changes:**
- Corrected the typo in the comment from "comsumption" to "consumption" for better clarity.
This typo correction improves the readability and accuracy of the comment regarding the purpose of the tests.
---
**Allow edits by maintainers:** [x]

fix(tests): Typo in `tests/osaka/eip7692_eof_v1/eip7069_extcall/test_gas.py`

---

README.md

Update `Contributing` section of the README to discourage typo-fixing PRs.
None

chore(README): `Contributing` section update

---

.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml
docs/CHANGELOG.md

Use self-hosted runner to build fixtures for releases.
None

feat(ci): self-hosted fixture building

---

docs/CHANGELOG.md
docs/writing_tests/test_markers.md
src/pytest_plugins/__init__.py
src/pytest_plugins/forks/__init__.py
src/pytest_plugins/forks/forks.py
src/pytest_plugins/forks/tests/test_covariant_markers.py
src/pytest_plugins/forks/tests/test_fork_parametrizer_types.py

Convert `fork_covariant_parametrize` into a marker `pytest.mark.fork_parametrize` in order to not have to import the function.
None

fix(plugins/forks): Make `fork_covariant_parametrize` into a marker

---

tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals_consolidations.py

Fix empty list tests where the tests were hard-coding the hash to be invalid, but the invalidity was only true for the previous hash calculation method.
Add more tests and also future-proof (or at least fail test generation) in case there is a new request type introduced by a future fork.
Thanks to @rkrasiuk for finding this outdated test case!
None

fix(tests): EIP-7685: Remove outdated test, add more tests

---

src/pytest_plugins/forks/forks.py

Fixes the warnings:
```
./tests/cancun/eip4844_blobs/test_blob_txs.py:373: PytestUnknownMarkWarning: Unknown pytest.mark.parametrize_by_fork - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.parametrize_by_fork
```
Fix for:
- #1057 (which forgot to register the marker explicitly in the pytest ini config).

fix(pytest): add `parametrize_by_fork` marker to pytest's ini config

---

docs/CHANGELOG.md
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_fixtures/tests/test_blockchain.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_forks/forks/helpers.py
src/ethereum_test_specs/state.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/cancun/eip4844_blobs/common.py
tests/cancun/eip4844_blobs/conftest.py
tests/cancun/eip4844_blobs/spec.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py
tests/cancun/eip4844_blobs/test_blobhash_opcode.py
tests/cancun/eip4844_blobs/test_blobhash_opcode_contexts.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

This PR removes activation of EIP-7742 at Prague, but leaves the framework changes.
Adds [EIP-7691 Blob throughput increase](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7691.md) by making a refactor of EIP-4844 tests to accept dynamic parameters during test generation.
This PR requires https://github.com/ethereum/execution-spec-tests/pull/1019.
#956

feat(forks,specs,tests): EIP-7691, EIP-4844: Refactor to use dynamic parameters

---

tests/prague/eip2537_bls_12_381_precompiles/conftest.py
tests/prague/eip7002_el_triggerable_withdrawals/helpers.py
tests/prague/eip7251_consolidations/helpers.py
tests/prague/eip7702_set_code_tx/test_gas.py

various small fixed to make tests work in external testnets
I've got most of these prague tests running:
- eip2537_bls_12_381_precompiles (except all tests in test_bls12_variable_length_input_contracts.py with manual 100M gas limit attribute)
- eip7002_el_triggerable_withdrawals
- eip7251_consolidations
- eip7623_increase_calldata_cost
- eip7702_set_code_tx

fix(tests): fixes to get tests running in external testnets

---

src/ethereum_test_base_types/base_types.py
src/ethereum_test_base_types/conversions.py
src/ethereum_test_types/types.py
tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py
tests/cancun/eip1153_tstore/test_tstorage_selfdestruct.py
tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Changes `left_pad_zeros_up_to_size` to be instead an optional parameter in all classes that inherit `FixedSizeBytes`.
So for example `Hash(left_pad_zeros_up_to_size("0x00", 32))` is equivalent to `Hash("0x00", left_padding=True)`.
If neither `left_padding` or `right_padding` are specified, and the input is shorter than the expected size, an exception is raised.

Refactor `left_pad_zeros_up_to_size` to a parameter in the `FixedSizeBytes` constructor

---

src/pytest_plugins/consume/hive_simulators/ruleset.py

Adds the Prague blob schedules (EIP-7840) to the hive simulator ruleset (as done in https://github.com/ethereum/hive/pull/1207)
- https://github.com/ethereum/EIPs/pull/9129
- https://github.com/ethereum/hive/pull/1207

chore(consume): add blob schedule rules to hive ruleset

---

converted-ethereum-tests.txt
tests/frontier/opcodes/test_push.py

Introduces tests for `PUSH*` opcodes ported from `ethereum/tests`.
closes #974

✨ feat(tests): PUSH*

---

pyproject.toml
uv.lock

Add https://pypi.org/project/ethereum-rlp/ as a dependency to address the recent fails in CI, cf #1083.
This also required bumping the version of `uv` used in CI to `0.5.20` to fix #1084.
Fixes #1083.

chore(all): add ethereum-rlp as a dependency

---

.github/configs/eels_resolutions.json
eels_resolutions.json

Update the eels resolutions keys for the Paris fork from `Paris` to `Merge` (and remove `EELSMaster` from the CI resolution file).
This PR resolves (one of) the underlying reasons for this fail, see [this comment](https://github.com/ethereum/execution-spec-tests/issues/1083#issuecomment-2595249139) in from the following ticket for more details.
- #1083

fix(fill,fw,ci): use t8n fork name in eels resolutions keys

---

src/cli/eofwrap.py

There is no support for invalid FixtureTransactions to be read from JSON, so we cannot include invalid blocks easily. However as this is not central to the behavior eofwrap tests are intended to test, we can just skip these invalid blocks with the same end effect on the test.
~Unfortunately, the fix isn't limited to that. It seems like the fix to requests serialization/hashing (#990) missed a detail when the `requests_lists` is used to construct requests (like from t8n output). Please double check carefully if this fix is fine.~
~Note also that for devnet-5 this would be partially hidden by the fact, that we don't include empty requests in the commitment anymore, meaning that all empty requests will not trigger the problem~
EDIT: request handling remains unchanged, see thread below
NA

 fix(eof): eofwrap.py to ignore invalid blocks 

---

.github/workflows/coverage.yaml

Enable coverage measurement on blockchain tests 
Coverage issue in https://github.com/ethereum/execution-spec-tests/pull/1075
~~- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).~~ Skipped

feat(github): Coverage script to detect blockchain tests

---

src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/tests/test_expect.py
tests/frontier/examples/__init__.py
tests/frontier/examples/test_block_intermediate_state.py
tests/frontier/examples/test_block_intermidiate_state.py
whitelist.txt

Allow verification of individual block states in blockchain test
https://github.com/ethereum/execution-spec-tests/issues/1033

feat(specs): verify intermidiate block state in blockchain test

---

src/cli/gentest/source_code_generator.py
src/cli/gentest/tests/__init__.py
src/cli/gentest/tests/test_cli.py
src/config/app.py
tox.ini

This PR introduces an end-to-end CI workflow for gentest.
closes #860

✨ feat(CI): CI for Gentest

---

src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py

This is a suggestion for #1095. 
It adds the check live as a dedicated fixture alongside the existing `environment` fixture in order to keep the hive client  config in one place.
I verified that the variable is correctly propagated locally for #1095 and for this PR.

Add check live port as dedicated fixture

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py

Use the [`"HIVE_CHECK_LIVE_PORT"` client environment value](https://github.com/ethereum/hive/blob/7910caeacba62a7172fd98dbe73322724c146297/internal/libhive/api.go#L265-L275) when starting a client for an Engine API test in the `consume` command.
This seems to be a recurrent issue when instantiating parallel client containers for hive runs, as it can be seen in https://hive.pectra-devnet-5.ethpandaops.io/suite.html?suiteid=1737336360-cdc9f3b55f2e828c17ab8b6c364934e8.json&suitename=eest%2Fconsume-engine#
The solution suggested by this PR is to signal hive to wait for the Engine API port (8551) instead of the RPC port (8545) before returning the client to the simulator (`consume`).
None

feat(plugins/consume): Check port 8551 on Engine API tests

---

src/ethereum_clis/clis/besu.py

Updates both the TYPE_4_TX_CONTRACT_CREATION and the INTRINSIC_GAS_TOO_LOW exception to their correct messages for Besu.
fixes #1100

devnet-5: Update exceptions messages for Besu

---

tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py

Adds some more edge cases for testing blob gas handling at fork transitions (for the case that blobs are already activated in both forks).
#1082

feat(tests): more blob gas tests for fork transitions

---

docs/CHANGELOG.md
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py

Implements fork transition tests for the blob target and max increment by EIP-7691 that occurs on the Prague activation.
Test expectation: At the first block of Prague, we use the`TARGET_BLOB_GAS_PER_BLOCK`,`MAX_BLOB_GAS_PER_BLOCK` and `BLOB_BASE_FEE_UPDATE_FRACTION_PRAGUE` constants in EIP-7691, just the same as we use for subsequent blocks for Prague:
```
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py::test_fork_transition_excess_blob_gas_at_blob_genesis[fork_ShanghaiToCancunAtTime15k-max_blobs-blockchain_test]
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py::test_fork_transition_excess_blob_gas_at_blob_genesis[fork_ShanghaiToCancunAtTime15k-max_blobs-blockchain_test_engine]
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py::test_fo …
```

feat(tests): EIP-7691: Fork transition tests

---

tests/prague/eip7685_general_purpose_el_requests/conftest.py
tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals_consolidations.py
tests/prague/eip7685_general_purpose_el_requests/test_request_types.py

Updates EIP-7685 to take into account the following execution-apis PRs:
- https://github.com/ethereum/execution-apis/pull/622
- https://github.com/ethereum/execution-apis/pull/623 (Not yet merged)
#1094

fix(tests): EIP-7685: Return Engine API error code for invalid params

---

tests/cancun/eip6780_selfdestruct/test_selfdestruct.py

```   
if selfdestruct_contract_initial_balance > 0:
pre.fund_address(selfdestruct_contract_address, selfdestruct_contract_initial_balance)
```
when selfdestruct_contract_initial_balance is >0, the contract will be called one time which make comparision when slot 0 is wrong. 
```
============================================================= test session starts ==============================================================
platform darwin -- Python 3.13.1, pytest-7.4.4, pluggy-1.5.0 -- /Users/son.ho/Backend/ronin-execution-spec-tests/.venv/bin/python
Generating fixtures for: Cancun
Only generating fixtures with stable/deployed forks: Specify an upcoming fork via --until=fork to add forks under development.
solc: 0.8.24
Start seed for EOA: …
```

fix(tests): [eip6780] avoid call fund address for unexpected triggering contract in execute mode

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py

It takes a single test case for `CALLF`'s invalid code section index to separate more specific test and add 2 more cases (one from ethereum/tests).
The same test case are going to be done later for `JUMPF`.

new(tests): extend tests for CALLF invalid section index

---

tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_validation.py

new(tests): tests for JUMPF invalid section index

---

src/ethereum_test_base_types/base_types.py
src/ethereum_test_base_types/tests/test_base_types.py

Pass all aguments to Address() to the super constructor. This fixes ability to create addresses out of shorter bytes, e.g. `Address(my_bytes, left_padding=True)`.
Solves an issue introduced by #1010.
- ~~[ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).~~ skipped

fix(fw): fix Address padding options

---

docs/CHANGELOG.md
tests/prague/eip7623_increase_calldata_cost/conftest.py
tests/prague/eip7623_increase_calldata_cost/test_execution_gas.py
tests/prague/eip7623_increase_calldata_cost/test_refunds.py

This PR updates EIP-7623 tests in accordance with [#9227](https://github.com/ethereum/EIPs/pull/9227).
This file introduces tests that verify all types of refunds:
- Storage Reset.
- Authorization with Authority already in State.
Including tests that use both refunds at the same time.
Test scenarios include execution gas usage when:
- Execution gas minus refund is greater than the data floor.
- Execution gas minus refund equal to the data floor.
- Execution gas minus refund is less than the data floor.
Refunds are removed from this file altogether.
None

fix(tests): EIP-7623 update due to spec change

---

tests/osaka/eip7692_eof_v1/eip7069_extcall/test_gas.py
tests/osaka/eip7692_eof_v1/gas_test.py

Test the creation gas charge of a contract when the contract was called and remained "empty."

new(tests): EOF - EIP-7069: Test EXTCALL creation gas charge

---

tests/osaka/eip7692_eof_v1/eip7069_extcall/test_address_space_extension.py

Simplify and properly convert bytes to `Address` using `left_padding`.

fix(tests): fix address padding in extcall tests

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): CALLF with truncated immediate bytes

---

.github/actions/build-fixtures/action.yaml

Minor fix to skip dumping debug information on fixture creation during a feature release tag.
None

fix(github): Add `--skip-evm-dump` to `build-fixtures/action.yaml`

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

This case is ported from a valid EOF validation test in ethereum/tests.

new(tests): add one more CALLF execution test

---

src/ethereum_clis/clis/besu.py

INITCODE_SIZE_EXCEEDED name. Tested with pectra-devnet-5@v1.3.0

chore(evm): use correct exception message for besu

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip7480_data_section/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): DATALOADN with truncated immediate bytes

---

src/ethereum_test_tools/utility/generators.py

This PR modifies the `@generate_system_contract_deploy_test` decorator to additionally generate tests for the case when the target contract address has a non-zero balance prior to deployment.
This adds additional tests for EIP-7002, EIP-2935 and EIP-7251.
Initial suggestion from @jochem-brouwer in [#el-testing](https://discord.com/channels/595666850260713488/1333302287484977253/1333356400092643400).
#1024, the PR where the system test contract generator was added.

feat(fill): also test system contract deployments with balance

---

src/ethereum_test_vm/bytecode.py
src/ethereum_test_vm/tests/test_vm.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py

This provides a basic requested feature to allow concatenating `Bytecode` with verbatim `bytes`.
This implementation overload the `__add__` and make the basic use case work.
However, this is not very consistent. E.g. 
- `code + b"\x00"` means something different than `code + Bytecode(b"\x00")`
- `Bytecode() + b"\x00"` works in places where `Bytecode()` is expected but `b"\x00"` don't.
The reason this is not a complete solution is that `Bytecode()` already has a constructor from `bytes` but its purpose is different and unknown to me. We should consider changing the semantic of conversion from bytes to `Bytecode()` by just copying the bytes.
There is one more option for handling truncated opcode immediate bytes: take verbatim bytes from `[]`, e.g. `Op.PUSH3[b"\x00"]`. This currently …

feat(fw): allow adding verbatim bytes to Bytecode

---

docs/CHANGELOG.md
docs/gen_test_case_reference.py
pytest.ini
src/cli/pytest_commands/fill.py
src/ethereum_test_fixtures/file.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py
stubs/xdist/__init__.pyi
stubs/xdist/methods.pyi

Improves xdist workload distribution method by reverting `--dist` flag to its default value, `load`, and also make the fixture collector multi-process safe by creating a lock file per fixture file generated, and locking->reading->writing the file instead of overwriting it.
Description of xdist scoping here https://github.com/ethereum/execution-spec-tests/issues/159#issuecomment-1604250000

feat(fill): improve performance when xdist is enabled

---

docs/CHANGELOG.md
src/ethereum_clis/transition_tool.py
src/ethereum_test_base_types/reference_spec/git_reference_spec.py
src/ethereum_test_base_types/reference_spec/reference_spec.py
src/ethereum_test_fixtures/base.py
src/pytest_plugins/filler/filler.py

This PR consumes the metadata passed on from the `ethereum-spec-evm-resolver` and appends this information to the ``_info`` section in generated test jsons.
- `ethereum-spec-evm-resolver` PR: https://github.com/petertdavies/ethereum-spec-evm-resolver/pull/8

feat(t8n,filler): Append EELS resolution information to ``_info`` for generate test jsons

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py

Test the case where adding auxdata to a subcontainer could result in the parent containers data section if the subcontainer were not copied.

feat(tests): EOF - EIP-7620: verify RETURNCONTRACT does not overwrite containing contract

---

uv.lock

Updates the resolver version to https://github.com/petertdavies/ethereum-spec-evm-resolver/commit/c35d96f80cb7bcf82890dd8dacbbb73c7d7a4671 in order to start using the feature introduced in  #1123.
None

uv.lock: Update eels resolver to `c35d96`

---

docs/consuming_tests/consume_command.md

Added documentation for the `consume` command in the "Consuming Tests" section. This documentation includes:
- What is consume and its purpose
- When to use it
- How to use it with different methods (direct, engine, hive, rlp)
- Examples and Hive considerations (including --dev mode and --client-config flag)
Fixes #1125

docs(consume): add consume command documentation

---

src/ethereum_clis/clis/execution_specs.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Adds two tests where either the authorization reuses the same nonce as a prior transaction (valid block), or a transaction reuses the nonce of an authorization included in a prior transaction (invalid block).
None

feat(tests): EIP-7702: Invalid block test

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Following recent additions to EOF functions tests, convert the remaining
test cases from EIP4750/validInvalid.json.
This also updates the EOF test case tracker.
Requires: #1122.

new(tests): convert remaining EOF functions tests (EIP4750) 

---

src/ethereum_test_specs/eof.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_size.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_eof_example.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_migrated_valid_invalid.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_section_header_body_mismatch.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_section_order.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_execution.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_stack.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_target.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_nonreturning_validation.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_exchange.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_swapn.py
tests/osaka/eip7692_eof_v1/eip7480_data_section/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_returncontract.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Renames the `data` field of `EOFTest` to a more appropriate name of `container`.
All EOF tests have been refactored to use the new name.
`EOFStateTest` now inherits `Transaction` and the fields `tx_gas_limit` and `tx_data` have been deprecated in favor of the `Transaction.gas_limit` and `Transaction.data` fields. Tests using either of these fields have been modified to use the new fields.
Note that `EOFStateTest.gas_limit` is redefined to have a default of 10,000,000, since the `Transaction` default is 21,000, and some EOF tests relied on the higher limit.
Other `Transaction` fields such as `expected_receipt` are now available in the `EOFStateTest` object, and can be used automatically to make verifications in the state test.
Tests were filled before and after this change and the …

reafactor(specs,tests): Rename `EOFTest.data` -> `EOFTest.container`, rebase `EOFStateTest`

---

converted-ethereum-tests.txt
docs/CHANGELOG.md
tests/istanbul/eip152_blake2/__init__.py
tests/istanbul/eip152_blake2/test_blake2.py

Add tests for [EIP-152: BLAKE2 compression function `F` precompile](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-152.md).
Test cases pulled from https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stPreCompiledContracts/blake2BFiller.yml
ethereum/tests#1431

feat(tests): EIP-152 precompiled contracts with Blake2

---

src/cli/gentest/tests/test_cli.py

This avoids running into #1149.
#999

test(gentest): add `--skip-evm-dump` option to `fill`

---

src/cli/tests/test_pytest_fill_command.py

Running `phil` in the framework tests "sometimes" caused `phil`'s pytest-custom-report (emoji) config to leak out into the framework pytest session terminal results and unsettling unfamiliar users.

test(fill): remove test for `phil`

---

src/pytest_plugins/execute/execute.py

Fixes an issue when using `uv run execute` where now the `config.selected_forks` variable that is prepared by the forks plugin also contains the transition forks, which resulted in the `execute` command always failing to start.
Bug introduced in fork plugin refactor in:
- #1081

fix(execute): fix selected forks incompatibility

---

src/ethereum_clis/clis/besu.py

Tested with pectra-devnet-5@v1.3.1

fix(clis/besu): nonce mismatch exception mapping

---

tests/prague/eip6110_deposits/test_deposits.py

Mark the `many_deposits` tests as slow due to timeouts that have been happening when filling using max parallelism.
None

fix(tests): EIP-6110: Add `slow` marker to `many_deposits` test

---

docs/CHANGELOG.md
docs/getting_started/installation.md
uv.lock

chore(tooling): update `uv.lock` for compatibility with `uv>=0.5.22`

---

.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
eels_resolutions.json
pyproject.toml
src/ethereum_test_types/types.py
uv.lock

~~Requires #1180~~
Bumps the version of execution-spec used by:
1. EEST libraries (`uv.lock`, `pyproject.toml`), and,
2. EEST test fixture generation (`eels_resolutions.json`, `tox_verify.yaml`)
to https://github.com/ethereum/execution-specs/commit/9923823367b5586228e590537d47aa9cc4c6a206.
Note, the version is intentionally added to `pyproject.toml` to pin `ethereum` when used with ediable, interactive use (`uvx --with-editable . ipython`).
None

chore(tooling): update `execution-specs` version to `99238233`

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip7480_data_section/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip7480_data_section/test_data_opcodes.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): add tests for DATALOADN validation and execution

---

tests/cancun/eip6780_selfdestruct/conftest.py
tests/cancun/eip6780_selfdestruct/test_reentrancy_selfdestruct_revert.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py

```
plugins: html-4.1.1, json-report-1.5.0, metadata-3.1.1, custom-report-1.0.1, xdist-3.6.1, typeguard-4.3.0
collected 6 items / 1 deselected / 5 selected                                                                                                                                                                  
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py::test_selfdestruct_created_in_same_tx_with_revert[fork_Cancun-transaction_post-no_outer_selfdestruct-same_tx] Starting EOA index: 0x7e86ab011d54ff42e0187e246ce6a5900063147355b14f27feae79f32f533eef
Deploying contract with gas limit: 135602
Deploying contract with gas limit: 162902
PASSEDUsed balance=0.000429135000000003
tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py::test_selfdestruct_created_in_same_tx …
```

feat/adapt eip6780 selfdestruct revert & reentrancy_selfdestruct to execute mode

---

docs/CHANGELOG.md
src/pytest_plugins/eels_resolver.py
src/pytest_plugins/filler/filler.py
uv.lock
whitelist.txt

Fixes format issues when the output is the stdout.

fix(plugins/filler): Fix filler stdout output

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py

Improve tests for EOF magic and version bytes in the EOF prefix by omitting parameters of valid values. Also add some new parameter values suggested by ethereum/tests.

feat(tests): improve tests for EOF prefix

---

tox.ini

Fixes CI failures by changing the `package` type to `editable` instead of `wheel`.
Issue showed up because of the use of `uvx --with=tox-uv tox` throughout the CI, and the `tox-uv` plugin being updated to version [1.23.0](https://github.com/tox-dev/tox-uv/releases/tag/1.23.0).
We could try to pin the `tox-uv` version to prevent this from happening, but for the time being this patch will do.
CI failure example: https://github.com/ethereum/execution-spec-tests/actions/runs/13207079743/job/36872669510

fix(tox): Change `package` to editable in tox.ini

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py

new(tests): add EOF tests for type section missing

---

tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py

new(tests): a test for empty EOF type section

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py

new(tests): add a test for multiple EOF type sections

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py

new(tests): add a test case for EOF code header missing

---

docs/gen_test_case_reference.py
tox.ini

When using `tests` as arg the build time can be more than 40 sec, when using `tests/frontier` it is around 7 sec on my machine. While working on the docs it is nice to have the options to have access to a faster build mode that doesn't spend most of its time rebuilding docs you are not modifying anyways. It is advised to create a bashrc alias for the usage example commands. Before creating a PR for any docs changes it is advised to run `uvx --with=tox-uv tox -e docs` once to ensure that there are no issues when building using the `--strict` flag.

feat(docs): added fast build mechanic with usage examples

---

src/cli/eofwrap.py

Fixes a small bug introduced by the ruff refactor and adds a temp solution to load in blockchain fixtures from `ethereum/tests` due to the introduction of `FixtureConfig` in this [PR](https://github.com/ethereum/execution-spec-tests/pull/1040).
Note that in the most recent `ethereum/tests` release only the Pyspecs/ tests contain this field.
N/A

chore(cli): temp eofwrap pydantic fix

---

tests/osaka/eip7692_eof_v1/eip7698_eof_creation_tx/test_eof_creation_tx.py

Test two inbound cases, one where the deploy fails, then verifying the nonce is not incremented. The next with a "short data" subcontainer.

new(tests) EIP-7698 failed nonce and short data tests

---

docs/CHANGELOG.md
pyproject.toml
src/ethereum_test_base_types/composite_types.py
src/ethereum_test_forks/helpers.py
tests/cancun/eip4788_beacon_root/conftest.py
tests/osaka/eip7692_eof_v1/eip7069_extcall/test_returndataload.py
uv.lock

Updates `mypy` from `0.991` to `>=1.15.0,<1.16`.
An update is long overdue, but @felix314159 ran into a fatal error with `mypy==0.991`, which was fixed by upgrading. 
Note: According to the [pydantic docs](https://docs.pydantic.dev/latest/integrations/mypy/#supported-mypy-versions):
> Pydantic supports the mypy versions released less than 6 months ago. Older versions may still work with the plugin but won't be tested.
I didn't encounter any issues with the pydantic mypy pluging, although we don't take advantage of any of the stricter checks offered by the plugin, cf #1218.
**Speed-up**
Upgrading gives a nice speed-up compared to 0.991, here's the timings on my machine to run:
```
rm -rf .mypy_cache/; uv run mypy src tests docs .github/scripts
```
- `main`: 36s
- `tooling/update-mypy`: 16s …

chore(tooling,deps): update mypy to latest release

---

tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py

The previous description incorrect mentions `RJUMPI` instead of `RJUMP`.

fix(tests): correct test_rjumpi_at_the_end description

---

docs/CHANGELOG.md
docs/changelog_section_template.md
whitelist.txt

Adds the missing items from the changelog with some reformatting.
Bumps the next section in the changelog for the next release.
N/A

chore(docs): add missing items from changelog

---

converted-ethereum-tests.txt
src/ethereum_clis/clis/evmone.py
src/ethereum_test_exceptions/exceptions.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Add new `EOFCREATE` validation tests inspired by an ethereum/tests file.

new(tests): add more EOFCREATE validation tests

---

docs/CHANGELOG.md
src/ethereum_test_specs/eof.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_size.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_migrated_valid_invalid.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py
tests/osaka/eip7692_eof_v1/eip7480_data_section/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

~~REQUIRES #1220~~ Merged
Create a state test out of an `eof_test` by:
1) in the case of a run-time container, wrapping the container under test within an init container and sending a contract-creating transaction
2) in the case of an init container, the container is wrapped in a factory container (which would execute the initcode to create a contract) and the factory container is wrapped within an init container, which is finally sent as a contract-creating transaction
All state tests generated automatically from the `eof_test` spec now have a different test ID, along with an extra marker applied.
The test ID will show `state_test_from_eof_test` instead of simply `state_test`, e.g.:
`test_swapn_on_max_stack[fork_Osaka-state_test_from_eof_test-swapn_operand_0]`
intead of: …

feat(specs): EOF: `eof_test` generates state tests, and `execute` in live devnets

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Add test cases for max stack height validation for code sections having at least one RJUMP instruction. These cases are converted from ethereum/tests.

new(tests): add more RJUMP validation tests

---

docs/CHANGELOG.md
src/ethereum_test_execution/base.py
src/ethereum_test_fixtures/base.py

Fixes the following error:
```
================================================================ FAILURES ================================================================
__________________________ test_all_opcodes_in_container[fork_Osaka-blockchain_test_from_eof_test-opcode_STOP] ___________________________
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py:115: in test_all_opcodes_in_container
eof_test(
src/pytest_plugins/filler/filler.py:695: in __init__
fixture = self.generate(
src/ethereum_test_specs/eof.py:464: in generate
raise Exception(f"Unknown fixture format: {fixture_format}")
E   Exception: Unknown fixture format: <class 'ethereum_test_fixtures.blockchain.BlockchainFixture'>
============================================================ warnings summary …
```

fix(execution,fixtures): Labeled formats comparison

---

docs/CHANGELOG.md
src/ethereum_clis/clis/execution_specs.py
whitelist.txt

A `fill`-ing error found by @gurukamath on macOS appeared for python version `3.11.2`. The key issue is specifically due to a platform limitation in `cpython` as commented here: https://github.com/python/cpython/issues/105912#issuecomment-1858769943
The error occurs as the requests library (via urllib.request) attempts to perform a proxy bypass check on a URL that uses the `http+unix://` scheme. A crash occurs when running the function `proxy_bypass_macosx_sysconf` causing an empty label to be passed to the IDNA encoder. Key error logs are below:
```console
.venv/lib/python3.11/site-packages/requests/utils.py:816: in should_bypass_proxies
bypass = proxy_bypass(parsed.hostname)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py:2654: in proxy_bypass
return …
```

bug: fix EELS t8n for CPython versions on macOS

---

docs/CHANGELOG.md
src/pytest_plugins/consume/direct/conftest.py

Changes to `consume direct` behavior:
1. Rename the `--fixture-consume-bin` option to `--bin`.
2. Removes the default value for `--fixture-consume-bin`, previously this was `["evm"]` geth. Now this value must be explicitly specified (some preparation for #1232), unless ran with `--collect-only`.
3. Enables `--collect-only` without `--bin`.
4. Fixes `--bin`'s type: `list` -> `Path`.
The main motivation of this PR was 3. in order to enable consume unit testing without requiring a fixture consumer binary (required for #1221).
- #1232
- #935
- #1221

feat(consume): allow `consume direct --collect-only` without `--bin`

---

converted-ethereum-tests.txt
tests/frontier/precompiles/test_precompiles.py

Add tests to check each precompile at specific addresses.
Tests from: https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stPreCompiledContracts/idPrecompsFiller.yml
Removed in:
https://github.com/ethereum/tests/pull/1444

feat(tests) Precompile Checks

---

.pre-commit-config.yaml

Adds the tox `typecheck` env to the default pre-commit config, cf https://ethereum.github.io/execution-spec-tests/main/dev/precommit/
None

feat(tooling): run `tox -e typecheck` in pre-commit

---

docs/CHANGELOG.md
pyproject.toml
src/cli/gentest/tests/test_cli.py
src/cli/pytest_commands/consume.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/direct/conftest.py
src/pytest_plugins/consume/direct/test_via_direct.py
src/pytest_plugins/consume/tests/test_consume_args.py
src/pytest_plugins/filler/tests/test_filler.py
uv.lock
whitelist.txt

This PR improves how the `consume` hive simulators handle the `--sim.parallelism` (^= `HIVE_PARALLELISM`) and `--sim.limit` (`HIVE_TEST_PATTERN`) args.
Don't activate `pytest-xdist` if `--sim.parallelism` is 1 (the default). This sets `-n=1` in the pytest simulator which superflously activates the pytest-xdist plugin. This has no benefits and obfuscates pytest output; xdist is now only used if `HIVE_PARALLELISM > 1`.
The previous behavior was to pass `HIVE_TEST_PATTERN` to pytest's `-k` argument, which is very pytest specific. This PR adds a dependency on `pytest-regex` and allows users to provide a regex to `--sim.limit` which is more consistent with other simulators.
To ensure transparent behavior between running between the two modes: 
1. Directly `./hive --sim …

feat,test(consume): use regex for `--sim.limit`; don't use xdist if `--sim.parallelism=1`

---

.vscode/settings.json

Update `ruff` settings in vscode to get rid of the "legacy server" warning that's been popping up recently.

fix warning in vscode about ruff legacy server

---

docs/CHANGELOG.md
src/ethereum_test_execution/base.py
src/ethereum_test_fixtures/base.py
src/pytest_plugins/shared/execute_fill.py

#1220 added labeled fixture and execute formats, which were added as markers to each generated test.
This caused a warning due to appear because the label markers were not registered during the config phase of the pytest plugins.
This PR adds all known fixture or execute formats markers to the config at the start.
None

fix(execute,fill): Fix warnings due to labels being unknown markers

---

docs/CHANGELOG.md
src/ethereum_test_execution/base.py
src/ethereum_test_fixtures/base.py
src/ethereum_test_specs/eof.py
src/ethereum_test_specs/state.py
src/pytest_plugins/shared/execute_fill.py

Follow-up to #1220.
1. Register the new label type markers that get applied to tests to avoid pytest test session warnings, e.g.:
```
================================================== warnings summary ===================================================
src/pytest_plugins/shared/helpers.py:37
/home/dtopz/code/github/danceratopz/eest/src/pytest_plugins/shared/helpers.py:37: PytestUnknownMarkWarning: Unknown pytest.mark.state_test_from_eof_test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
getattr(
...
```
(can be reproduced via `fill tests/osaka --fork=osaka`).
2. Additionally adds a `description` field to `LabeledExecuteFormat` and `LabeledFixtureFormat` that can be used in the marker doc. …

fix(fill,execute): register new label type markers to prevent warnings

---

src/cli/gentest/request_manager.py
src/cli/gentest/test_context_providers.py
src/cli/gentest/test_providers.py
src/cli/gentest/tests/test_cli.py
src/config/env.py
src/ethereum_test_rpc/types.py
src/ethereum_test_types/types.py

Support for type 1 and 2 transaction.
I have not created a test case to test type 1 transaction. Let me know if that is okay.
closes #861

✨ feat(gentest): Support for transaction types

---

src/cli/eofwrap.py

Two minor fixes to `eofwrap.py` to enable including the eofwrap tests in EOF release
N/A

fix(eofwrap): fixture_format and auxiliary logging

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_validation.py

I've noticed we don't have a test where RETF and INVALID share the same code section. JUMPF tests seem not to be migrated yet, so the addition looks a bit silly, but I'm anticipating the migration will happen.
NA

new(tests): EOF - mix RETF with INVALID, RETF underflow

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Parametrize and add more test cases for invalid EOF code with RJUMP over an unreachable instruction.

new(tests): extend RJUMP over unreachable code

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): EOF validation JUMPF stack overflow

---

src/ethereum_clis/clis/evmone.py
src/ethereum_test_exceptions/exceptions.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py

Test EOF validation of ambiguous container kind:
a single subcontainer reference by both EOFCREATE and RETURNCONTRACT.

new(tests): Add tests for ambiguous subcontainer kind

---

.github/actions/build-evm-client/evmone/action.yaml

See https://github.com/ethereum/evmone/blob/0be7b1624b993fa7f3710ec61016c74163fe40f1/README.md?plain=1#L100
CC @winsvega, @reedsa
Should fix the fails when filling with `emvone` in the "Evmone Coverage Report" CI flow the coverage script in 
- #1244

chore(ci): enable all precompiles in `evmone` build

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Add test cases for max stack height validation for code sections having at least one RJUMPV instruction. These cases are converted from ethereum/tests.

new(tests): add more RJUMPV validation tests

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py

EIP-161 requires the creating instructions to bump the nonce of the account where the contract is created. This test uses a reentrant EOFCREATE factory, which without this rule would happily create the contract twice.
NA

new(tests): EOF - ensure EOFCREATE bumps nonce as EIP-161

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eip7698_eof_creation_tx/test_eof_creation_tx.py

Two minor details which may seem obvious, as they are carried over from the behavior of legacy CREATE,
NA

new(tests): EOF - ensure EOFCREATE memory and transfer

---

docs/CHANGELOG.md
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_fixtures/common.py
src/ethereum_test_fixtures/state.py
src/ethereum_test_fixtures/tests/test_blockchain.py

Unfortunately, the `yParity` field in authorization lists was named `v` in our state test fixture format, which differs from from EIP-7702:
https://github.com/ethereum/EIPs/blob/aa391ae306408fcd049a1442a5deab47675c0c87/EIPS/eip-7702.md?plain=1#L45
This change will enable erigon to correctly run the 7702 tests (with non-zero `yParity` in authorization lists, this default to `0` as it wasn't found).
Thanks to @holiman for detecting this issue.
- https://github.com/erigontech/erigon/issues/14073
- https://github.com/bluealloy/revm/pull/2150

bug(fill,types): duplicate `FixtureAuthorizationTuple`'s `v` field as `yParity`

---

docs/CHANGELOG.md
docs/templates/function.md.j2
whitelist.txt

Fixes #1291 by removing the automatically generated test function pages from the mkdocs-material search index.
This change reduces the size of `site/search/search_index.json` from ~123 Mb to ~2 Mb.
Fixes:
- #1291

fix(docs,ci): don't include function pages in site search index

---

docs/CHANGELOG.md
src/cli/eofwrap.py
src/ethereum_test_fixtures/base.py

Renames the `info["fixture_format"]` field to `info["fixture-format"]`.
Both `fixture-format` and `fixture_format` can be used when loading fixtures from now on -> old fixtures can be used with this new change. But this will break loading (new) fixtures using this format from older versions of EEST.
@winsvega noticed that this was inconsistent with the existing field names in `_info`, so we decided to fix this now, as it's only been recently introduced.
None
.

chore(fill,spec): write `fixture-format` not `fixture_format` to fixtures

---

.github/configs/evm-impl.yaml
.github/configs/feature.yaml
docs/CHANGELOG.md

To speed up the release process I've added a new user to the hive server called `usainbolt`. This user will be used entirely as a self-hosted runner set for the [Build and Package Fixtures](https://github.com/spencer-tb/execution-spec-tests/actions/workflows/fixtures.yaml) workflow step. Note this is only runs when creating new releases.
Currently our releases take a long time finish as fixture builds run sequentially, due to our single self-hosted runner instance. Everything in total currently takes around 5hrs. I've now added 6 self hosted runners.
This will take our entire release process time down to <3hrs. Note we could improve this by finding a way to fill the `slow` marked fixtures faster, ideally giving us a release build time of <30mins.
- Removed `pectra-devnet-6` as a separate …

chore(ci): use manual x-dist value for self-hosted runners

---

docs/CHANGELOG.md

Bumps the changelog to the latest version as part of the release process.
N/A

chore(docs): bump changelog for new release

---

docs/CHANGELOG.md
src/cli/gen_index.py

Two small fixes for index generation with ethereum/tests:
1. Allow index generation at any level of the directory structure by removing the relative path prefixes to fixtures that aren't supported. Only check their names (they have unique names). This allows `uv run genindex -i ethereum/tests/BlockchainTests/some/path`. Note, we can't load ethereum/tests state tests yet, only blockchain tests.
2. Include the ethereum/tests `info_[`generatedTestHash` as `fixture_hash`. This is not ideal, due to the info field name mismatch and as EEST fixture hashes are "0x" prefixed and ethereum/tests hashes aren't. But, it will at least allow verification that individual fixture files are up-to-date (this will not affect index.json regeneration, as this depends entirely on `hasher`).
- …

fix(consume): fixes for index generation with ethereum/tests

---

docs/CHANGELOG.md
src/ethereum_clis/__init__.py
src/ethereum_clis/clis/nethermind.py
whitelist.txt

Adds support for consuming state test, blockchain test and eof test fixtures with Nethermind's direct client test interface `nethtest`.
To run with eof test fixtures, the [feature/evm/eof Nethermind branch](https://github.com/NethermindEth/nethermind/tree/feature/evm/eof) is required:
```
dotnet build ./src/Nethermind/EthereumTests.slnx -c release
ln -s ~/bin/nethtest
```
The build currently fails, but `nethtest` gets build and seems to be functional.
Then, for example:
```
uv run consume direct --input=eip7692@latest --bin=~/bin/nethtest -n 8  # --sim.limit=".*-eof_test.*"
```
None

feat(clis,consume): add nethermind support to `consume direct`

---

.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
eels_resolutions.json
pyproject.toml
uv.lock

The `py_ecc` dependency has been changed from a git dependency to a standard PyPI dependency. Since EEST indirectly depends on `py_ecc` through EELS it needs its EELS dependency bumped.

chore(deps): Bump EELS dependency

---

docs/CHANGELOG.md
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/direct/conftest.py
whitelist.txt

1. Enables filtering of test cases by their fixture format via pytest markers (relevant for `consume direct` which supports multiple fixture formats.
2. Fixes a spurious and unnecessary warning when running `uv run consume direct --markers`.
```
$ consume direct --markers
@pytest.mark.blockchain_test_engine: Tests in `blockchain_test_engine` format 
@pytest.mark.eof_test: Tests in `eof_test` format 
@pytest.mark.state_test: Tests in `state_test` format 
@pytest.mark.transaction_test: Tests in `transaction_test` format 
@pytest.mark.Shanghai: Tests for the Shanghai fork
...
```
```
$ consume direct --input=develop@latest --bin=~/bin/nethtest -m blockchain_test -k chainid --collect-only -q
pytest-regex selected 14823 tests to run for regex: .* …
```

feat(consume): enable test case filtering by fixture format

---

docs/CHANGELOG.md
src/pytest_plugins/forks/forks.py
src/pytest_plugins/forks/tests/test_markers.py

Transition forks do not work within `--fork/from/until` when using `fill`. This PR fixes the latter.
```sh
>> uv run fill --fork ShanghaiToCancunAtTime15k 
Error: Unsupported fork provided to --fork: ShanghaiToCancunAtTime15k 
Available forks:
Byzantium, Prague, Homestead, Istanbul, Cancun, Frontier, London, Osaka, Paris, CancunEIP7692, Shanghai, ConstantinopleFix, Berlin, Constantinople
Available transition forks:
BerlinToLondonAt5, CancunToPragueAtTime15k, ShanghaiToCancunAtTime15k, ParisToShanghaiAtTime15k
Exit: Invalid command-line options.
```
More context: https://github.com/ethereum/execution-spec-tests/issues/1307

chore(fill): fix `--fork/from/until` for transition forks

---

docs/CHANGELOG.md
src/ethereum_clis/clis/geth.py

When running fill with the geth transition tool we get the following error:
```
tests/shanghai/eip3855_push0/test_push0.py:145: in test_push0_contract_during_call_contexts
state_test(env=env, pre=pre, post=post, tx=tx)
src/pytest_plugins/filler/filler.py:707: in __init__
_info_metadata=t8n._info_metadata,
E   AttributeError: 'GethTransitionTool' object has no attribute '_info_metadata'
```
This is because `GethTransitionTool` does not init the parent class `TransitionTool`.
N/A

chore(fill): fix for geth transition tool

---

docs/CHANGELOG.md
src/cli/gen_index.py
src/ethereum_test_fixtures/consume.py
src/ethereum_test_forks/helpers.py
src/pytest_plugins/consume/consume.py

This is a follow-up to #1304 that addresses two issues:
1. Running `consume` would raise an error if an unknown fork was encountered, i.e., if the index file contained a fork that was not supported by EEST. This is fixed by adding a `strict_mode` flag to `get_relative_fork_markers` and setting it to `False` when called from `consume`. This is required because ethereum/{tests,legacyTests} contains forks that EEST doesn't know about (yet).
2. With 1. added, `consume` would then issue warnings for unregistered marks for the marks that EEST doesn't know about. This can be fixed by registering markers for all the forks in the test cases. As a convenience, these are now added as top-level metadata to the index file.
```json
{
"root_hash": …
```

fix(consume): allow consumption of fixtures with unknown forks

---

src/ethereum_clis/clis/execution_specs.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

new(tests): add state test with empty 7702 authorization list

---

src/ethereum_test_specs/eof.py
src/ethereum_test_types/eof/v1/__init__.py
src/ethereum_test_types/tests/test_eof_v1.py
src/ethereum_test_vm/opcode.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/opcodes.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_opcodes_in_legacy.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_nonreturning_validation.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/__init__.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_returncode.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_subcontainer_validation.py
tests/osaka/eip7692_eof_v1/eip7698_eof_creation_tx/test_eof_creation_tx.py
tests/osaka/eip7692_eof_v1/eof_tracker.md
whitelist.txt

As title, aligns with https://github.com/ipsilon/eof/pull/182
NA

fix(tests): EOF - Rename RETURNCONTRACT to RETURNCODE

---

docs/CHANGELOG.md
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/releases.py
whitelist.txt

Adds tarball release URL download support for ethereum/tests and ethereum/legacytests to `consume`, for example:
```
consume cache --input=https://github.com/ethereum/tests/releases/download/v17.0/fixtures_blockchain_tests.tgz
```
An additional fix that was required to enable this feature with the above tarball: Don't assume that the directory contained within the tarball is hard-coded as "fixtures", now the top-level directory name is automatically detected, this was the offending code:
https://github.com/ethereum/execution-spec-tests/blob/ab62c8d674ad0de3b83718d837f231617153ce52/src/pytest_plugins/consume/consume.py#L122
and
https://github.com/ethereum/execution-spec-tests/blob/ab62c8d674ad0de3b83718d837f231617153ce52/src/pytest_plugins/consume/consume.py#L130
- Fixes #1302

feat(consume): add support for ethereum/{tests,legacytests} tarball urls

---

src/cli/gentest/request_manager.py
src/ethereum_test_rpc/rpc.py
src/pytest_plugins/execute/execute.py
src/pytest_plugins/execute/pre_alloc.py
src/pytest_plugins/execute/rpc/hive.py
src/pytest_plugins/execute/sender.py

Makes the following changes to help the refund logic complete in case of a failure during fixture setup:
Previously the sender refund logic was placed in the `base_test_parametrizer` function, which is responsible for setting up the `state_test`, `blockchain_test`, etc, fixtures that are used in tests to actually generate the test.
The problem was that this fixture is not guaranteed to be the first fixture prepared during the pytest routine, so it could be that we had a fixture order preparation of:
`pre` -> `sender` -> `blockchain_test`
If an error occurred during the `sender` fixture setup, which potentially used `pre` fixture to fund a sender account, the refund logic would not be reached because the setup failed before reaching `blockchain_test`
The fix in this case is to put all the …

refactor(plugins/execute): Refactor account refunds logic

---

.github/workflows/docs_deploy.yaml

Gives the ephemeral github token write access to github pages.  
Fixes the CI failure here: https://github.com/ethereum/execution-spec-tests/actions/runs/13910619884/job/38923833604
(hopefully :P)
- This didn't work #1319
- The original solution that did work #179

chore(ci): fix github pages docs push

---

src/ethereum_clis/clis/besu.py

We have recently removed the string `Hyperledger` from the version string of Besu's EVM tool.
The PR with this change can be found here: https://github.com/hyperledger/besu/commit/5215c953e0fbe0259479c0b272dfea343d101c92#diff-cff5ab4373e323fb0a6d885fcfda67b52b514d7109c194892d4874465b452d0eL43-L44
This PR updates the binary pattern to take this into consideration

fix(clis): Update Besu's binary pattern

---

src/cli/gen_index.py

Fixes a small issues that prevents index generation for EOF tests because they return `None` on `get_fork` call, so we would end up with a list that cotained `None` as the single element.
None

fix(cli/gen_index): Fix index generation for EOF files

---

tests/prague/eip7702_set_code_tx/test_set_code_txs.py

The transaction in this test is invalid for 2 reasons: empty `to` and also empty `authorization_list`. Some test runners that don't check for exact error can pass it for the wrong reason.

fix(test): improve EIP-7702 test for type 4 transaction with empty to

---

.github/actions/build-evm-client/besu/action.yaml
.github/actions/build-evm-client/ethjs/action.yml
.github/actions/build-evm-client/evmone/action.yaml
.github/actions/build-evm-client/geth/action.yaml
.github/actions/build-fixtures/action.yaml
.github/workflows/coverage.yaml
.github/workflows/docs_deploy.yaml
.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml
.github/workflows/tox_verify.yaml

execution-spec-tests was affected by a compromised action, see #1316. Pinning github actions to specific hashes avoids future vulnerabilities by automatically using an updated, compromised version.
Done with the help of the amazing https://github.com/ethpandaops/github-actions-checker
- Fixes #1316
Here's an example of an ethpandops pr that recently pinned its actions:
- https://github.com/ethpandaops/ethereum-package/pull/921

chore(ci): pin github actions at hashed versions

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/conftest.py

Fixes the `--sim.limit` flag value written to the test case description sent back to hive in order to help developers reproduce tests.
Thanks @macfarla for reporting!
None

chore(consume): fix `--sim.limit` in hive commands shown in test reports

---

src/ethereum_clis/clis/execution_specs.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Adds a test where the sender of a type-4 transaction (not an auth signer) contains code that is not a delegation (would require a contract-eoa address collision to be produced).
cc @gurukamath 
None

new(tests): EIP-7702: Sender not EOA test

---

docs/CHANGELOG.md
pyproject.toml

This will allow projects that use the `ethereum-execution-spec-tests` package to run:
```
eest make test
uv run eest make test
```
None

fix(make): include jinja2 templates in eest package

---

docs/CHANGELOG.md
pyproject.toml
uv.lock
whitelist.txt

Fixes the macOS failures in CI.
The issue stems from `solc-select`, due to the `pycryptodome` dependency, take a look at their [`pyproject.toml`](https://github.com/crytic/solc-select/blob/dev/pyproject.toml#L9):
```toml
dependencies = [
"pycryptodome>=3.4.6",
"packaging",
]
```
Within our CI we get the following [error](https://github.com/ethereum/execution-spec-tests/actions/runs/14039166908/job/39304679439):
```
× Failed to build `pycryptodome==3.15.0`
├─▶ The build backend returned an error
╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit
status: 1)
...
setuptools.errors.InvalidConfigError: Invalid dash-separated key
'py-limited-api' in 'bdist_wheel' (setup.cfg), please use the underscore
name 'py_limited_api' instead.
hint: This usually indicates a problem with …
```

chore(ci): explicity define version range for `pycryptodome`.

---

uv.lock

**Background**
- Prior to #1343, `uv.lock` had `pycrptodome` at `3.15.0`.
https://github.com/ethereum/execution-spec-tests/blob/e04edbe1f9c0b932b628165d12af8d244e4da776/uv.lock#L1319-L1321
- #1343 newly added `pycryptodome` to eest's package dependencies `"pycryptodome>=3.4.6,<3.10"` resulting in `uv.lock` pinning `pycryptodome` at `3.9.9`.
- The changes in #1343 weren't necessary and `pycryptodome` was removed from eest's package dependencies (#1345), but the version in `uv.lock` inadvertently remained at `3.9.9`.
https://github.com/ethereum/execution-spec-tests/blob/87131722a1bd16fc6209f0f63d4db838c2210d5d/uv.lock#L1315-L1317
- It seems (unverified, but likely) that older `pycryptodome` wheel packages (at least at 3.9.9) didn't include pre-compiled binaries, so require `gcc`.
- This …

fix(deps): revert pycryptodome to version used before #1343

---

tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py

The `check_contract` uses `MSTORE` to store `check_block_number` at memory offset 0. However, if `CALL` to `HISTORY_STORAGE_ADDRESS` is reverted, `MLOAD(0)` returns the value of `check_block_number` instead of `0x0`, as expected.
I ran this test in `execute` mode and found that it failed. My solution was to change `ret_offset` to avoid duplication with `check_block_number`. I ran it again and it worked as expected.

fix(tests): EIP-2935: change ret_offset to avoid duplicate

---

tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Fixes a broken test for EIP-7702 introduced in #1288
None

fix(tests): EIP-7702 verification/merge issue

---

src/pytest_plugins/spec_version_checker/spec_version_checker.py

For some reason the xdist started to fail and it was due to the items being added to the list of tests by the spec version checker were in a different order in each worker.
This PR sorts the modules before adding the tests to have a deterministic list.
None

fix(plugins/spec_version_checker): Sort modules

---

.github/actions/build-evm-client/evmone/action.yaml

Attempt to fix this failure:
https://github.com/ethereum/execution-spec-tests/actions/runs/14119176442/job/39594538181
It's running with version 4.0.0 now, which I'm assuming it's not supported by the version checker contained in evmone, so pinning to the latest v3 should do the trick.
None

fix(github): Pin cmake to a pre-4.0.0 version

---

converted-ethereum-tests.txt
docs/CHANGELOG.md
tests/istanbul/eip152_blake2/test_blake2.py
tests/istanbul/eip152_blake2/test_blake2_callcode.py
tests/istanbul/eip152_blake2/test_blake2_delegatecall.py

Convert remaining Blake2 precompile test cases for CALL and DELEGATECALL
#972 (stPreCompiledContracts / stPreCompiledContracts2)
* https://github.com/ethereum/tests/pull/1479

feat(tests) Additional blake2 precompile tests

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/ruleset.py

Primarily adds Osaka to the hive ruleset file. Additional refactoring includes a blob schedule function to prevent things getting messy (a quick addition while adding Osaka).
Previously, you had to manually write out blob schedule keys like this:
```python
"Prague": {
"HIVE_FORK_HOMESTEAD": 0,
...
"HIVE_CANCUN_TIMESTAMP": 0,
"HIVE_CANCUN_BLOB_TARGET": 3,
"HIVE_CANCUN_BLOB_MAX": 6,
"HIVE_CANCUN_BLOB_BASE_FEE_UPDATE_FRACTION": 3338477,
"HIVE_PRAGUE_TIMESTAMP": 0,
"HIVE_PRAGUE_BLOB_TARGET": 6,
"HIVE_PRAGUE_BLOB_MAX": 9,
"HIVE_PRAGUE_BLOB_BASE_FEE_UPDATE_FRACTION": 5007716,
},
```
Now, you can simply write:
```python
"Prague": {
"HIVE_FORK_HOMESTEAD": 0,
...
"HIVE_CANCUN_TIMESTAMP": 0,
"HIVE_PRAGUE_TIMESTAMP": 0,
**get_blob_schedule_entries(Prague),
},
```
N/A

chore: update hive ruleset and add osaka

---

docs/CHANGELOG.md
src/ethereum_test_specs/base.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/eof.py
src/ethereum_test_specs/state.py
src/ethereum_test_specs/transaction.py

Adds labeled markers and names to all execute formats, derived from the test spec type names of the test where they came from.
Since we only have a single execute format that matches all specs we have, all execute test names contain "transaction_post" in the ID, and no reference or marker to the specification that was used to fill it:
```
test_set_code_from_account_with_non_delegating_code[fork_Prague-transaction_post-self_sponsored_True-EMPTY_ACCOUNT]
```
With this change the test IDs now contain the name of the test spec that was used to produce the test:
```
test_set_code_from_account_with_non_delegating_code[fork_Prague-state_test-self_sponsored_True-EMPTY_ACCOUNT]
```
Also we can now narrow execution to a specific type of test using markers.
E.g.
```
uv run execute hive --fork=Prague …
```

feat(execute): Use test spec names as markers for `execute`

---

tests/osaka/eip7692_eof_v1/eip7069_extcall/test_calls.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

I worked on amending the spec for EXTDELEGATECALL restrictions and realized I'm not sure parts of it were tested. They were, but not in an explicitly intentional manner and also not through the lens of 7702. So there it is.
I'm not entirely sure I'm handling the migration trackers correctly - there's no such thing as `src/EIPTestsFiller/StateTests/stEOF/stEIP3540/EOF1_CallsFiller.yml` in `ethereum/tests`?
NA

 new(tests): EOF - EXTDELEGATECALL blocking vs 7702

---

tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_exchange.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_swapn.py

Add simple and asymmetric tests for swap/dup/exchange, to detect when operations are performed on the wrong end of the stack.

Add simple swap/dup/exchange tests

---

.github/PULL_REQUEST_TEMPLATE.md
.vscode/settings.json
README.md
docs/CHANGELOG.md
docs/consuming_tests/index.md
docs/dev/docs.md
docs/writing_tests/tutorials/blockchain.md
docs/writing_tests/tutorials/state_transition_bad_opcode.md
mkdocs.yml
pyproject.toml
src/cli/input/questionary_input_repository.py
src/config/docs.py
src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py
tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py
tests/frontier/opcodes/test_calldatacopy.py
tests/frontier/opcodes/test_dup.py

- The README had links pointing to an unversioned (and very out-dated) version of our docs in the root of the `gh-pages` branch; these now point to the `main` version. Thanks @jochem-brouwer for reporting!
- Update domain from github pages to eest.ethereum.org.
- Fixes bad links detected via https://github.com/lycheeverse/lychee
None

fix(docs): fix bad links in readme and elsewhere

---

tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_nonreturning_validation.py

Move some basic tests for invalid first section type to the parametrized tests of EIP-6206. Extend the test coverage by using more exhaustive combination of params.
This helps with later spec change of https://github.com/ipsilon/eof/issues/134.

new(tests): Aggregate EOF tests for invalid first section type

---

docs/CHANGELOG.md
src/ethereum_test_types/types.py
tests/prague/eip7702_set_code_tx/test_invalid_tx.py

Adds more serialization tests.
Requires #1359

new(tests): EIP-7702 more RLP tests

---

tests/prague/eip7623_increase_calldata_cost/test_execution_gas.py

This PR removes a duplicate reference of the [`authorization_refund` fixture.](https://github.com/ethereum/execution-spec-tests/blob/935b3e3de56546500b1a3f3c11190696369e162d/tests/prague/eip7623_increase_calldata_cost/conftest.py#L69-L72)
This effort is part of #1299

🧹 chore(tests): remove duplicate fixture in EIP-7623

---

tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Add exhaustive EOF stack underflow tests.
Replaces some of the example tests from https://github.com/ethereum/execution-spec-tests/pull/1331.

new(tests): Add exhaustive EOF stack underflow tests

---

docs/CHANGELOG.md
docs/dev/index.md
docs/dev/logging.md
docs/navigation.md
pytest-consume.ini
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py
src/pytest_plugins/consume/tests/test_consume_args.py
src/pytest_plugins/logging.py
src/pytest_plugins/logging/__init__.py
src/pytest_plugins/logging/logging.py
src/pytest_plugins/logging/tests/__init__.py
src/pytest_plugins/logging/tests/test_logging.py
src/pytest_plugins/pytest_hive/pytest_hive.py
whitelist.txt

The Besu Team reported some flaky looking `eest/consume-rlp` results in the Pectra dashboard, without any logging from the simulator side, we're essentially blind as to the timing of the simulator setup with regards to client startup. This PR adds logging to help debug this.
1. Use pytest's `--tb short` to only show relevant tracebacks for unexpected exceptions in test execution (e.g., timeout on rpc call; requests exceptions are notoriously noisy).
2. Add a new logging plugin. This is pretty ugly stuff, but the complexity seems necessary to achieve:
a. Getting timestamps in pytest's capd output (pytest has amazing logging, but this seemed unachievable with the built-in plugin, would be happy to be wrong).
b. Clean logging to file per logger with xdist.
c. Adding log lines to the file for …

feat(consume): enable logging, propagate logs to hive results

---

pyproject.toml
uv.lock

Adds a version specifier for the `types-requests` package which fixes the `uv` warning:
```
warning: Missing version constraint (e.g., a lower bound) for types-requests
```
Achieved via:
```
uv add --optional lint "types-requests>=2.31,<2.33"
```
None

chore(deps): add version specifier for `types-requests`

---

tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

This combines the cases of `test_all_opcodes_stack_underflow()` to `test_all_opcodes_variadic_stack_underflow()`.
By the way, this also improves some details, e.g. avoids instruction sequence as `RETURN STOP`.

refactor(tests): Merge EOF stack underflow tests

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): EOF validation RETF stack overflow

---

docs/CHANGELOG.md
tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py

Additional coverage for checklist items in https://github.com/ethereum/execution-spec-tests/blob/eip-checklist/docs/checklist_templates/eip_testing_checklist_template.md#-new-system-contract
* Add cases for calling history storage address with all call opcode variants.

feat(tests): Additional EIP-2935 coverage

---

src/ethereum_test_types/types.py

Tiny change to refactor the `__bytes__` method in `Requests` to remove a misleading comment and simplify a bit.
None

chore(types): Refactor and remove misleading comment in `Requests`

---

src/ethereum_test_types/eof/v1/__init__.py
src/ethereum_test_types/tests/test_eof_v1.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_nonreturning_validation.py

When building EOF code section assert that `max_stack_height` is at least `code_inputs`.
It will be impossible to encode such code types after https://github.com/ipsilon/eof/issues/134

fix(tests): Prevent EOF max stack height above number of inputs

---

tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_exchange.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_swapn.py

Some EOF stack underflow tests are duplicated.
The https://github.com/ethereum/execution-spec-tests/pull/1384 introduced duplicated EOF stack underflow tests by modifying the max_stack_height calculation.

fix(tests): de-duplicate EOF stack underflow tests

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip6206_jumpf/test_jumpf_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

Port ethereum/tests EOF validation tests for stack underflow.

new(tests): Add EOF validation tests for stack underflow

---

src/ethereum_test_specs/helpers.py
src/ethereum_test_specs/tests/test_expect.py

Couple of suggestions for `src/ethereum_test_specs/helpers.py` in #1396:
1. Define an enum class instead of using string literal for the execution context of the exception.
2. Rename `ty` to `execution_context`.
3. Add more specific exception class names.
#1396

Suggestions for #1396, refactor(exceptions,specs): Support general block exceptions - Pydantic context to parse using mapper

---

src/pytest_plugins/shared/execute_fill.py

Adds a marker that we can apply to tests that are relevant to zkEVM by using:
```python
@pytest.mark.zkevm
```
We can run fill for every fork but only tests that use this marker, e.g.:
```
uv run fill --from=Cancun --until=Osaka -m zkevm
```
@kevaundray
None

feat(fill,execute): add new `zkevm` marker

---

src/ethereum_test_vm/opcode.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_gas.py

Update with https://github.com/ipsilon/eof/pull/156, planned for EOF Osaka-devnet-1. EOFCREATE stack args order to match that of EXT*CALL.
Filling requires `evmone` with an update which will be flagged below :point_down:

fix(tests): EOF - Align EOFCREATE args with EXT*CALL

---

src/ethereum_test_fixtures/common.py
src/ethereum_test_types/types.py

EIP-7702 specs requires the signature component `v` to be called `yParity`.  #1286 addressed this issue for fixtures, this PR extends the fix for transaction payload, by moving the code to the parent class `AuthorizationTupleGeneric`.
#1286

🐞 fix(types): Add missing yParity in Authorization tuple

---

src/ethereum_test_execution/transaction_post.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/state.py
src/ethereum_test_specs/transaction.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

Currently, the test `test_eoa_tx_after_set_code` is including both setcode tx that sets code for an EOA and tx using EOA as sender in same block. However, it is invalid due to changes introduced in this PR https://github.com/ethereum/go-ethereum/pull/31430. When I try to run this test in `execute` mode, the second tx is rejected with the error `gapped-nonce tx from delegated accounts`
Here is my solution to fix it:
- I split txs into two blocks; the first includes setcode tx that set code for an EOA, and the second is the tx from that EOA
- We need to ensure txs of two different blocks must be included in different block as their order in node, so I refactored `TransactionPost` a little bit to send batches of txs by block.

fix(tests): EIP-7702: send tx of eoa after setcode tx is mined

---

.github/actions/build-evm-client/evmone/action.yaml
.github/configs/eels_resolutions.json
.github/workflows/tox_verify.yaml
src/conftest.py
src/ethereum_clis/clis/geth.py
src/ethereum_clis/ethereum_cli.py
src/ethereum_clis/tests/test_transition_tools_support.py
src/ethereum_clis/transition_tool.py
tox.ini

Despite checks, and unit test pass, evmone t8n input is still inconsistent
geth t8n requires  0x20000  format for hex input and support decimals
evmone t8n requires 0x020000 format for hex input and does not support decimals
eest t8n supports all
first I introduce a unit test CI to verify that test filling works correctly on t8n's
TODO
design a simple test that triggers interesting t8n input on all forks. (with blockheader history and all fork fields in env) to run as a reference
Current coverage script is broken because of t8n format inconsistency with evmone after changing fields from int to hex in:
- https://github.com/ethereum/execution-spec-tests/pull/1027/files

feat(unit-tests): verify transition tool support

---

.github/workflows/check-links.yml

Fixes indentation in the link checker github action and improves its title.
- #1375

fix(ci): fix bad indentation in link checker yml; update title

---

README.md

Adds additional badges to the repo readme.
#1401

chore(docs): add python, ruff, uv and license badges to readme

---

docs/CHANGELOG.md
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

- Add a test case that calls the delegated precompile acct directly from the same transaction as the auth. Supply enough gas only to cover the intrinsic cost of the call, with no extra gas for any precompile code execution.
- Update the test case for all call opcodes to use all of the call opcodes.
https://github.com/ethereum/execution-spec-tests/issues/1299

feat(tests): update 7702 precompile test cases

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py

Otherwise, the generated test names are too long and filling fails.

fix(tests): assign ids to parametrized EOF code sections

---

src/pytest_plugins/filler/filler.py

Avoid querying the git ref for every test function filled by caching the result in a session-scoped fixtures.
None

refactor(fill): use a session-scoped fixture for git tag or hash

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py

new(tests): EOF validation non constant stack

---

docs/CHANGELOG.md
src/cli/eofwrap.py
src/ethereum_clis/tests/test_transition_tools_support.py
src/ethereum_test_specs/base.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/eof.py
src/ethereum_test_specs/helpers.py
src/ethereum_test_specs/state.py
src/ethereum_test_specs/tests/test_expect.py
src/ethereum_test_specs/tests/test_fixtures.py
src/ethereum_test_specs/tests/test_transaction.py
src/ethereum_test_specs/transaction.py
src/ethereum_test_tools/tests/test_code.py
src/pytest_plugins/execute/execute.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/shared/execute_fill.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/cancun/eip4844_blobs/test_blob_txs_full.py
tests/cancun/eip4844_blobs/test_excess_blob_gas.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py
tests/prague/eip6110_deposits/test_deposits.py
tests/prague/eip7002_el_triggerable_withdrawals/test_withdrawal_requests.py
tests/prague/eip7251_consolidations/test_consolidations.py
tests/prague/eip7623_increase_calldata_cost/test_transaction_validity.py
tests/prague/eip7685_general_purpose_el_requests/test_multi_type_requests.py
tests/prague/eip7702_set_code_tx/test_gas.py
tests/prague/eip7702_set_code_tx/test_invalid_tx.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py
tests/shanghai/eip3860_initcode/test_initcode.py
tests/shanghai/eip4895_withdrawals/test_withdrawals.py

Introduce a new marker to mark tests that produce an invalid transaction or block.
```python
@pytest.mark.exception_test
```
Test filling now fails if this marker is not applied and the test contains either an invalid transaction or an invalid block.
This PR also marks all existing negative tests.
The pytest fixture request is now a private attribute of `BaseTest` and a new class method `from_test` is introduced as a generic to automatically generate a test type from an instance of another test type, which `BaseTest` attributes automatically.
Also request has no longer to be passed to `generate` method, so it has been removed from all unit tests.
None

feat(specs,tests): `exception_test` marker

---

docs/CHANGELOG.md
tests/prague/eip7623_increase_calldata_cost/conftest.py
tests/prague/eip7623_increase_calldata_cost/test_transaction_validity.py

Additionally parametrize the test functions:
1. https://github.com/ethereum/execution-spec-tests/blob/dcdbfb29bcf5635bc15a0d3fd32cc4fda52c7b1f/tests/prague/eip7623_increase_calldata_cost/test_transaction_validity.py#L79
2. https://github.com/ethereum/execution-spec-tests/blob/dcdbfb29bcf5635bc15a0d3fd32cc4fda52c7b1f/tests/prague/eip7623_increase_calldata_cost/test_transaction_validity.py#L141
with a "to" value that corresponds to an EOA. 
This adds an additional 96 test cases, due to the existing parametrization these tests. All mainnet clients were tested using consume-engine, no fails were found.
Coverage analysis of the tests themselves revealed that L47 in the `to` fixture was not hit:
https://github.com/ethereum/execution-spec-tests/blob/dcdbfb29bcf5635bc15a0d3fd32cc4fda52c7b1f/tests/ …

feat(tests): eip7623 - parametrize `test_transaction_validity_type_*` with a tx to an eoa

---

src/ethereum_clis/clis/besu.py
src/ethereum_clis/clis/ethereumjs.py
src/ethereum_clis/clis/evmone.py
src/ethereum_clis/clis/execution_specs.py
src/ethereum_clis/clis/geth.py
src/ethereum_clis/clis/nimbus.py
src/ethereum_test_exceptions/exceptions.py
src/ethereum_test_types/eof/v1/__init__.py
src/ethereum_test_types/tests/test_eof_v1.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_container_validation.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_eof_example.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py

feat(fw,tests): change EOF to stack_height_increase

---

src/ethereum_test_types/eof/v1/__init__.py
tests/osaka/eip7692_eof_v1/eip3540_eof_v1/test_eof_example.py
tests/osaka/eip7692_eof_v1/eip4750_functions/test_code_validation.py

The `max_stack_increase` is complementary but preferred to `max_stack_height`. Both cannot be set at the same time.

feat(fw): add max_stack_increase to EOF Section.Code

---

tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py

Convert all EOF validation tests for EIP-4200 (relative jumps) to use `max_stack_increase`. The conversion here is simple because all these tests use the code section 0 and therefore `max_stack_increase` is equivalent to `max_stack_height`.
https://github.com/ipsilon/eof/issues/134

refactor(tests): change RJUMP validation tests to max_stack_increase

---

tests/prague/eip7251_consolidations/test_consolidations.py
tests/prague/eip7685_general_purpose_el_requests/test_multi_type_requests.py

Removes the pytest skips within the EIP-7251 & EIP-7685 test cases.
These were valid points after the change from 1 to 2 for `Spec.MAX_CONSOLIDATION_PER_BLOCK`.
Additional cases validated on all clients using `consume engine`.
N/A.

chore(tests): remove pytest skips from eip7251/7685 cases

---

docs/CHANGELOG.md
eels_resolutions.json
src/ethereum_test_tools/code/generators.py
tests/prague/eip7702_set_code_tx/test_gas.py

This PR attempts to add some missing test cases based purely on a coverage analysis of the test source itself. In particular, L269 in `test_gas` was not hit:
https://github.com/ethereum/execution-spec-tests/blob/62d2563dcfd58242f1846bab13f29a64dc558567/tests/prague/eip7702_set_code_tx/test_gas.py#L256-L276
Either of these two test cases fill the line coverage gap, but I am out of my depth with 7702 and would appreciate feedback on the test cases and whether they're reasonable. In particular, the second case fails to fill for all but one parameter combo - it need further restriction on the conditions it runs (ran out of time on this one).
1. The `multiple_invalid_nonce_authorizations_self_sponsored_multiple_signers` test cases fill and add coverage. All clients pass with consume-engine.
2. …

feat(tests): add increased nonce with invalid nonce tests

---

tests/osaka/eip7692_eof_v1/eip4750_functions/test_callf_execution.py

This updates EIP-4750 CALLF tests to use `max_stack_increase` instead of `max_stack_height`.
In many places the value is correctly auto-computed so for these cases the explicit value is omitted.

refactor(tests): change CALLF tests to max_stack_increase

---

tests/osaka/eip7692_eof_v1/eip5450_stack/test_execution.py

Add new tests for validation and execution at the maximum runtime operand stack height (1024).

new(tests): add EOF execution at maximum stack height

---

README.md

Small change to prevent airdrop farmers or give us a place to point when closing there issues.
Time is valuable and sacred.
N/A.

chore(docs): update readme contribution section

---

.markdownlint.yaml
docs/CHANGELOG.md

Correctly configure `markdownlint` to expect an indentation of 4. An indent of 4 is required for HTML documentation to render correctly. For example, the 2 highlighted items are included incorrectly as top-level items, but should be a sub-list:
None.

chore(tooling): configure `markdownlint` ul indent to 4

---

src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py

A few suggestions for #1416.
Feel free to pick and choose, as you like.
- #1416

Suggestions for: feat(consume): add ExceptionMapper support to the consume-engine simulator

---

tests/prague/eip6110_deposits/test_deposits.py
tests/prague/eip7002_el_triggerable_withdrawals/test_withdrawal_requests.py
tests/prague/eip7251_consolidations/test_consolidations.py

Running coverage on the test cases themselves revealed that although `helpers.py` handled the case for higher call depths  in `update_pre`:
https://github.com/ethereum/execution-spec-tests/blob/ad5c0ad28b7a31c7449dc6899c04d29a6bac34aa/tests/prague/eip7251_consolidations/helpers.py#L190-L212
the logic was never hit in L197:L212.
This PR adds some tests which trigger requests with a `call_depth > 2`.
- #1299

feat(tests): add consolidations & withdrawal requests with `call_depth>2`

---

converted-ethereum-tests.txt
tests/osaka/eip7692_eof_v1/eip5450_stack/test_code_validation.py
tests/osaka/eip7692_eof_v1/eof_tracker.md

new(tests): EOF validation stack_range maximally broad

---

docs/CHANGELOG.md
src/ethereum_clis/clis/besu.py
src/ethereum_clis/clis/erigon.py
src/ethereum_clis/clis/ethereumjs.py
src/ethereum_clis/clis/geth.py
src/ethereum_clis/clis/nethermind.py
src/ethereum_clis/clis/reth.py
src/ethereum_test_exceptions/exception_mapper.py
src/ethereum_test_exceptions/exceptions.py
src/ethereum_test_rpc/rpc.py
src/ethereum_test_rpc/types.py
src/ethereum_test_specs/helpers.py
src/ethereum_test_specs/state.py
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/conftest.py
src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
src/pytest_plugins/consume/hive_simulators/exceptions.py
tests/cancun/eip4844_blobs/test_blob_txs.py
tests/prague/eip7685_general_purpose_el_requests/test_multi_type_requests.py
whitelist.txt

Adds support of the exception mapper to consume-engine:
`consume engine` now checks exceptions returned by the execution clients in their Engine API responses, specifically in the `validationError`field of the `engine_newPayloadVX` method.
Exception mappers of all current mainnet clients have been added to the `ethereum_clis` library.
The feature can be disabled by using `--disable-strict-exception-matching` for specific clients or forks.

feat(consume): add `ExceptionMapper` support to the consume-engine simulator

---

.github/actions/build-fixtures/action.yaml
.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml

Fixture building is currently failing due to the use of `vars`, which is not allowed in that context.
Solution is to accept all required vars as input and then populate the input in the caller workflows.
None

fix(github): Remove `vars` usage in build-fixtures

---

tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_creation_tx.py

The EIP-3541 handling of EOF code was to execute it as uncontained code, executing the first 0xef byte and reverting.

fix(tests): Create transaction sarting with `0xef` is a valid tx, but should fail execution

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_legacy_eof_creates.py

I've noticed that the assertions in one of the tests were quite loose, so I made them more specific
NA

fix(tests): EIP-7620 - make CREATE/CREATE2 restrictions specific

---

src/ethereum_clis/clis/besu.py

Adds exceptions to Besu's exception mapper:
-  `BlockException.SYSTEM_CONTRACT_EMPTY` 
-  `TransactionException.INVALID_DEPOSIT_EVENT_LAYOUT`
Here are the exceptions from `tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_layout[fork_Prague-blockchain_test_engine-log_argument_*]`:
```
amount_offset-value_max_uint256	                 Invalid amount offset: expected 320, but got -1
amount_offset-value_zero	                     Invalid amount offset: expected 320, but got 0
amount_size-value_max_uint256	                 Invalid amount size: expected 8, but got -1
amount_size-value_zero                           Invalid amount size: expected 8, but got 0
index_offset-value_max_uint256	                 Invalid index offset: expected 512, but got -1
index_offset-value_zero …
```

fix(clis): update besu's exception mapper (`SYSTEM_CONTRACT_EMPTY`, `INVALID_DEPOSIT_EVENT_LAYOUT`)

---

src/ethereum_test_fixtures/collector.py
src/ethereum_test_specs/static_state/account.py
src/ethereum_test_specs/static_state/common/common.py
src/ethereum_test_specs/static_state/common/docker.py
src/ethereum_test_specs/static_state/expect_section.py
src/ethereum_test_specs/static_state/general_transaction.py
src/ethereum_test_specs/static_state/state_static.py
src/ethereum_test_specs/static_state/state_test_filler.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/static_filler.py

@marioevz  please don't merge there are bullet points to complete:
_- [x] Make sure exceptions are working correctly after mapper refactoring (too many things to fix)_ https://github.com/ethereum/execution-spec-tests/issues/1440
the test generation is supported with lllc from docker hub. 
https://hub.docker.com/r/winsvega/lllc
it works fast using docker exec. all we need is to pull a docker image in our CI

feat(static tests) : do not compile test fillers source code while loading the models

---

tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_creation_tx.py

(requires evmone with [this update](https://github.com/ethereum/evmone/pull/1190) to fill) EDIT: Merged
Also **NOTE** that, same as https://github.com/ethereum/execution-spec-tests/pull/1475 this PR adds tests and facilities for behavior of "legacy creation txs" (to: nil, EOF container in data), which is likely to change based on recently obtained feedback. 
I'd like to merge this as a baby step (and https://github.com/ethereum/execution-spec-tests/pull/1475) and then update the behavior in a proper PR
NA

 new(tests): EIP-7873 expand legacy creation tx tests 

---

docs/CHANGELOG.md
src/pytest_plugins/filler/filler.py

Fixes the `fixture_source_url` field in the fixture `_info` section for the case of a test function who's body is simply `pass`. Here's an example of such a test function, whose test logic is applied via a decorate from an EEST framework generator:
https://github.com/ethereum/execution-spec-tests/blob/f330aac4ae776ebbbca6005bcfdabbb6b04cf76b/tests/prague/eip7251_consolidations/test_modified_consolidation_contract.py#L137-L151
In v4.3.0, consume test reports report an invalid URL (with a non-existent line number), e.g. https://hive.ethpandaops.io/#/test/pectra/1745242958-27275e8c3ce031d481359ddd1eb46b12?page=1&testnumber=4776 
In these special cases, pytest reports the generator function as the test function, instead of the original test function. For this case, where the test module name …

fix(fill): fix reported fixture source urls for the case of auto-generated tests

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_txcreate.py
tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_txcreate_failures.py

Introduces more detailed assertions on the post state of failure of TX/EOFCREATE
NA

new(tests): EIP-7620/7873 - ensure no account gets created on failure

---

.github/configs/evm.yaml
.github/configs/feature.yaml
docs/CHANGELOG.md
pyproject.toml

Requires #1439 and #1442.
Adds the `legacy` feature to build `fixtures_legacy` on every release.
We are going to use evmone due to speed because of some of the lengthier tests in `stTimeConsuming` that take longer than 60 seconds to execute with EELS, but this could change in the future.
None

feat(ci): Add `static` feature to produce `fixtures_static`

---

src/ethereum_clis/clis/evmone.py
src/ethereum_test_exceptions/exceptions.py
tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_legacy_eof_creates.py
tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_creation_tx.py

Updates according to:
- https://github.com/ethereum/EIPs/pull/9669
- ~~https://github.com/ethereum/EIPs/pull/9688~~ EDIT: dropped, keeping CREATE/CREATE2 failures light
Requires https://github.com/ethereum/evmone/pull/1205 to fill using `evmone`.
NA

fix(tests): Update legacy creation tx rules

---

src/ethereum_clis/clis/geth.py

Fixes issues where the error returned by geth does not match the expected ones for system contract failures.
The errors have different reasons (suberrors) that can not be checked. e.g.
`"system call failed to execute: execution reverted"`
`"system call failed to execute: invalid opcode: INVALID"`
So I tried to add a \s to indicate that there might be a string afterwards. Don't know if that works in python
Fixes these errors: https://hive.ethpandaops.io/pectra/suite.html?suiteid=1745760795-339cef2738231feaae6575b0136bc6b0.json#test-4783

fix(geth): fixes geth error mappings

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/pytest_hive/hive_info.py
src/pytest_plugins/pytest_hive/pytest_hive.py
src/pytest_plugins/shared/execute_fill.py
whitelist.txt

Fixes the commands in the test description that is shown in the Hive UI to help client devs reproduce fails:
- Adds a separate command to write the client yaml file.
- Newly uses the `HiveInfo` instance obtained from the `/hive` endpoint to get the exact hive command used, cf:
- https://github.com/ethereum/hive/pull/1198 
- https://github.com/marioevz/hive.py/pull/8
bc8713ee14
```
echo "\
- build_args:
GOPROXY: https://goproxy.primary.production.platform.ethpandaops.io
github: ethereum/go-ethereum
tag: master
client: go-ethereum
dockerfile: git
nametag: default
" > clients_eest.yaml
./hive --sim ethereum/eest/consume-engine --client.checktimelimit=180s --docker.buildoutput --sim.buildarg fixtures=https://github.com/ethereum/execution-spec-tests/releases/download/v4.3.0/fixtures_develop.tar …
```

fix(consume): fix the test re-run hive commands displayed in hive ui

---

docs/CHANGELOG.md
src/pytest_plugins/consume/hive_simulators/ruleset.py
tests/berlin/eip2929_gas_cost_increases/__init__.py
tests/berlin/eip2929_gas_cost_increases/test_precompile_warming.py
tests/frontier/precompiles/test_precompiles.py

Idea from @jochem-brouwer - thanks! Please check whether this test is doing what you intended.
Call BALANCE of a precompile address before and after a fork.
According to EIP-2929, when a transaction begins, accessed_addresses is initialized to include:
- tx.sender, tx.to
- and the set of all precompiles
This test verifies that:
1. Precompiles that exist in the predecessor fork are always "warm" (lower gas cost)
2. New precompiles added in a fork are "cold" before the fork and become "warm" after
These would perhaps be better as state tests. Feel free to close and implement a better suggestion, but happy for any feedback if you have time!
Also, this test should live in tests/paris, not tests/frontier, as they're only valid for EIP-2929, but it seemed silly to separate them from the other …

feat(tests): add eip-2929 precompile address warming tests

---

tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add.py

Adds the zkevm marker for bls g1 add tests.
Required to test an initial zkevm fixtures release.
N/A

chore(tests): add zkevm marker for bls g1 add tests

---

.github/configs/evm.yaml

Remove Pectra devnet-6 evm feature from GitHub CI.
N/A

chore(ci): remove pectra devnet 6 evm feature

---

docs/CHANGELOG.md
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_rpc/rpc.py
src/ethereum_test_rpc/types.py

Following: https://github.com/ethereum/execution-apis/pull/630
I don't think we needed to change much on our end but please double check. I added the `get_blobs` engine rpc method here on the assumption that we can maybe create a test suite that sends blob txs to ELs, then we call `get_blobs` to validate the response. This feels suited towards an extension in `execute`.
N/A.

chore: add osaka engine updates

---

src/pytest_plugins/filler/gen_test_doc/gen_test_doc.py

Fixes the docs building issue, for cases where the dir `tests/<dir>` is not labelled a valid fork.
#1499

chore(docs): add non forks to test case reference

---

src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/generators.py
tests/zkevm/test_worst_bytecode.py

@jsign I added the dynamic contract creation to your PR.
Basically we insert as many blocks as necessary to deploy contracts from that won't be there in the genesis.
The only three contracts in genesis are the factory, a contract that contains the initcode, and an entry point that calls the factory.
If we want to exhaust the gas using `EXTCODEHASH`/`EXTCODESIZE`, we need about 13,822 contracts deployed and these take around 1,974 blocks to be deployed.
Furthermore, the generated test does contain the contracts in the form of the post-allocation verification, so the fixture is a couple hundred of megabytes even when these contracts are not in the pre-allocation.

Dynamic contract creation

---

src/ethereum_test_tools/__init__.py
src/ethereum_test_tools/code/__init__.py
src/ethereum_test_tools/code/generators.py
tests/zkevm/__init__.py
tests/zkevm/test_worst_bytecode.py

This PR adds a test that creates the current bytecode worst case scenario for provers.
It creates the target bytecodes as part of pre-alloc, which isn't friendly for filling. An alternative would be to generate these bytecodes with txs. That probably requires creating blocks before the attack block since you can't deploy ~300MiB of code in a single block due to gas limits. Sounds doable, but it can take some work.
To fill: `uv run fill --from=Cancun --until=Cancun -m "zkevm and blockchain_test"`
cc @kevaundray @marioevz

zkevm: add bytecode worst case

---

tests/berlin/eip2929_gas_cost_increases/test_precompile_warming.py

Fixes an issue introduced in #1495 when using `int.from_bytes` without the `byteorder` keyword argument on python 3.10.
None

fix(tests): Fix precompile warmup tests on python 3.10

---

src/ethereum_clis/clis/besu.py

Final Besu mapper tweaks for deposits.
Here are the exceptions from `tests/prague/eip6110_deposits/test_modified_contract.py::test_invalid_log_length[fork_Prague-blockchain_test_engine-*]`:
```
slice_bytes_False                 Invalid deposit log length. Must be 576 bytes, but is 575 bytes
slice_bytes_True	          Invalid deposit log length. Must be 576 bytes, but is 577 bytes
```
#1487

chore: update besu exception mapper deposits

---

tests/zkevm/test_worst_compute.py

This PR adds a test that builds a block to maximize the number of keccak permutations for a given gas limit (considering the max contract size).  
There are two main aspects of the test design.
The metric we care about is gas per permutation, not simply max opcode calls. Although the dynamic cost of `KECCAK256` is linear in input length, memory expansion is quadratic, so there is a sweet spot for minimal cost per permutation.
Instead of baking magic numbers, the test does a scan for the optimal cost and then does the attack with it. This is much more transparent on how this optimal length is found, plus it sounds also more future-proof.
Another way of understanding the above is by looking at this chart I created from that same script, with a more detailed output:
Once the optimal length …

zkevm: keccak worst-case

---

src/ethereum_test_tools/code/generators.py
tests/zkevm/test_worst_bytecode.py

The previous bytecode-attack test relied on a contiguous PUSH20 + EXTCODESIZE pattern that embedded each 20-byte target address directly in the bytecode. Embedding the addresses with PUSH20 is far cheaper than loading them from storage, so it lets us amplify the attack.
However, contract-size limits cap the number of iterations we can fit in 24 KiB (or even 256 KiB), so the approach runs out of space long before it bumps into the block gas limit. For example, for 36M gas limit, you're limited by the 24KiB max size limit.
This strategy removes that bottleneck:
- Target deployment via CREATE2: The factory now spawns target contracts with CREATE2, incrementing a seed to derive unique addresses.
- Cheap address recalculation: because a CREATE2 address is keccak256(0xff || sender || salt || …

zkEVM: fix max contract size limitation in bytecode attack

---

src/cli/eest/make/commands/test.py

When using `uv run eest make test` it is quite annoying to cancel, even after pressing ctrl+C it will keep asking you questions and eventually fail due to never handling receiving None. This commit allows the user to cancel via ctrl+C at any time.

fix(cli/eest): allow user to cancel via ctrl+C in interactive test creator

---

docs/CHANGELOG.md
tests/prague/eip2537_bls_12_381_precompiles/conftest.py
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add.py
tests/zkevm/conftest.py
tests/zkevm/test_worst_bytecode.py
tests/zkevm/test_worst_compute.py

Automatically apply the `zkevm` marker to all tests under `./tests/zkevm/` and `./tests/prague/eip2537_bls_12_381_precompiles/` via conftest configuration.
Test via:
```
fill -m zkevm --from Cancun --until Prague --collect-only -q > zkevm.txt
```
[zkevm.txt](https://github.com/user-attachments/files/20032705/zkevm.txt)
Fixes 
- #1527

chore(tests): add conftests to zkevm & bls subdirs to apply zkevm marker

---

src/ethereum_clis/clis/nethermind.py

Adds more error messages from Nethermind client that cover withdrawals and consolidation system calls failures:
- out of gas
- no code
-

Add errors for system contracts failures in Nethermind

---

tests/zkevm/test_worst_compute.py

This PR introduces an attack vector for the MODEXP precompile.
We assume 32-byte operands for the base, modulus, and exponent, anticipating the activation of EIP-7883 on mainnet in the near future (TM). Beyond the 32-byte boundary, the cost per unit of work rises, so it is valuable to model that limit from the outset.
The test suite is already parameterised for multiple gas limits (and can easily be extended to cover base/modulo/exp sizes), but for now we target 36M gas-limit since it is the relevant case for zkVMs today.
SP1 cycles: 36M gas limit -> ~27 billion cycles.
cc @kevaundray

zkEVM: add modexp attack

---

tests/osaka/eip7692_eof_v1/eip7620_eof_create/helpers.py
tests/osaka/eip7692_eof_v1/eip7873_tx_create/test_txcreate_validates.py

This is a pretty beefy test which ensures that TXCREATE correctly handles its initcode validation regardless of many circumstances it might find itself in:
- eof/legacy
- static mode
- insufficient balance for endowment
- input
- in top frame or in *call frame
- first or second execution in the transaction
- with/without other invalid/valid initcodes in the tx.initcodes
- with/without an access list entry at the destination address
It is ~3K~ 6K test cases :/, but I've done some reduction of the domain to bring it down to that level. Despite being a lot, I'd argue that ensuring EOF validation runs when it should, regardless of what's happening around it, is warranted to compliment all the EOF validation tests we have
NA

new(tests): TXCREATE executes validation

---

src/ethereum_test_specs/blockchain.py

This PR is a requirement for #1575.

Add optional field to exclude including postState

---

.github/configs/feature.yaml
.github/workflows/fixtures.yaml
docs/CHANGELOG.md

Allows us to add `feature_only: <BOOL>` field to our features within release CI.
This lets us easily skip features for new full releases.
Currently we can't fill for EOF as the fork name required is missing for evmone.
Both zkevm and EOF both now have `feature_only: true`, meaning there releases must be created manually via the feature release process.
N/A

feat(ci): add feature skips to main release process

---

docs/dev/deps_and_packaging.md
uv.lock

`uv` `0.6.15` bumped `uv.lock` version to 2 and added a new field to dependency `url` fields: `upload_time`, which was renamed to `upload-time` in `0.7.0`. Generating `uv.lock` with a version `>=0.6.15` creates a lot of noise. Search for "upload" in https://github.com/astral-sh/uv/releases.
This PR uses `uv==0.7.3` to update the uv.lock and add these new fields, without any dependency changes to make it easier to parse the uv.lock in the case of a true dependency change.
In the future, we should only make dependency changes with `uv>=0.7.0` to avoid switching back and forth between formats; this is noted in the docs.
None

chore(tooling): bump `uv.lock` revision

---

docs/CHANGELOG.md
src/pytest_plugins/solc/solc.py

Read the [issue](https://github.com/ethereum/execution-spec-tests/issues/1512) for more context

fix(solc): don't install `solc` via `solc-select` on ARM; add version sanity check

---

src/ethereum_clis/clis/evmone.py
src/ethereum_clis/clis/reth.py

Fixes the following exceptions in the clients
- Reth: TYPE_3_TX_ZERO_BLOBS, TYPE_3_TX_ZERO_BLOBS
- evmone: TYPE_4_TX_PRE_FORK
None

fix(clis/reth,evmone): Exception mapper fixes

---

.github/workflows/coverage.yaml

To avoid confusion, I removed GeneralStateTests from ethereum/tests repo.
this pr adjusts the coverage script for that 
Note: leaving the checkbox `A PR with removal of converted JSON/YML tests from ` on, since we have BlockchainTests to port. But converted state tests does not require a pr, since ALL are deleted in ethereum/tests.
ethereum-converted-tests.txt still required. but we can start thinking to replace it with  pytest marker logic soon.
https://github.com/ethereum/tests/pull/1491

chore(coverage,ci): remove `GeneralStateTests` from ethereum/tests coverage

---

docs/CHANGELOG.md
src/pytest_plugins/filler/__init__.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/fixture_output.py
src/pytest_plugins/filler/tests/test_filler.py

This PR adds a `FixtureOutput` class (which inherits from pydantic `BaseModel`) to `filler.py` in order to encapsulate `fiil`'s fixture JSON output-related settings. It's instantiated from the values of the command-line arguments that modify JSON output: `--output`, `--flat-output`, `--single-fixture-per-file`.
Refactoring in preparation of:
- #1030

refactor(fill): encapsulate fixture output options in `FixtureOutput` class

---

src/ethereum_clis/clis/nethermind.py

More cases of error messages returned by Nethermind, with some of them corrected
Should fix eest tests for Nethermind

Add/correct error messages for Nethermind

---

docs/CHANGELOG.md
src/ethereum_test_specs/base.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/state.py

Suppress high tx gas limit warnings for zkevm tests
See https://github.com/ethereum/execution-spec-tests/pull/1591#discussion_r2086922876 from
- #1591

feat(fill,zkevm): suppress high tx gas limit warnings for zkevm tests

---

.github/configs/feature.yaml
tests/zkevm/test_worst_bytecode.py

This PR proposes a way to fill the bytecode attack, solving two main problems:
- Creating so many 24KiB contracts with 36M gas limit takes a lot of blocks, which bloats the generated fixture in size and generation time.
- Even if so many blocks in the fixture aren't a problem, all the ~300MiB of code appears in the `postState`, which also bloats the fixture. (This PR now uses a new feature introduced in https://github.com/ethereum/execution-spec-tests/pull/1578)
Results:
- I tested in Geth, and it runs exactly as expected.
- Filling this test on my machine with `--block-gas-limit 36M`
- Only two blocks are needed in the fixture. 
- Block 1 only has a single tx creating all contracts.
- Block 2 has the actual attack.
- Takes 2 mins to fill the test, which sounds quite fast considering it …

zkvm: allow using entire gas in bytecode attack

---

docs/CHANGELOG.md
src/cli/gentest/tests/test_cli.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/fixture_output.py
src/pytest_plugins/filler/tests/test_output_directory.py
tox.ini

Requires:
- #1471
Make `fill`'s output behavior more robust: Do not write generated fixtures into an existing, non-empty output directory; it must now be empty or `--clean` must be used to delete it first.
Fixes #1030:
- #1030

fix(fill): insist `fill`'s output directory is empty or doesn't exist

---

tests/zkevm/test_worst_bytecode.py
tests/zkevm/test_worst_compute.py

This PR:
- Adds tests four new precompiles: ECRECOVER, SHA2-256, IDENTITY, and RIPEMD.
- Removes `zkevm` pytest markers since the testing framework now automatically does this.
- Uses `Environment()` configured gas limits, which are expected to be correctly set via the new `--block-gas-limit` filling flag.
- I updated the CI pipeline to use 36M gas limit for filling.
Cycle counts in the new precompiles:
- ECRECOVER: 682 million cycles
- SHA2-256: 5.8 billion cycles
- IDENTITY: 305 million cycles
- RIPEMD: 360 million cycles
The last three are all part of a generic test since these precompiles have the same input parameter structure (i.e., `data`). The generic test automatically discovers the optimal input length for each case to amortize the static cost as much as possible against the …

zkevm: add ECRECOVER, SHA2-256, IDENTITY and RIPEMD precompiles

---

tests/zkevm/test_worst_compute.py

Replay of https://github.com/ethereum/execution-spec-tests/pull/1528 which died because it targeted a feature branch.
Add two `JUMP`-heavy workloads to see how zkVMs handle this. Cycle counts from [the Reth fork](https://github.com/kevaundray/reth/tree/kw/stateless-experiment-zkvm-benchmarks):
```
[crates/zkvm-benchmarks/host/src/main.rs:57:9] &reports = [
WorkloadMetrics {
name: "tests/zkevm/test_worst_compute.py::test_worst_jumps[fork_Cancun-blockchain_test]-1",
total_num_cycles: 700358751,
region_cycles: {
"validation": 449377028,
"read_input": 250977795,
"verify-witness": 342781,
},
},
]
```
```
[crates/zkvm-benchmarks/host/src/main.rs:57:9] &reports = [
WorkloadMetrics {
name: "tests/zkevm/test_worst_compute.py::test_worst_jumpdests[fork_Cancun-blockchain_test]-1",
total_num_cycles: …
```

feat(tests/zkevm): Test jump and jumpdest

---

.github/workflows/tox_verify.yaml
docs/CHANGELOG.md
tox.ini
whitelist.txt

Fixes timeouts during CI runs due to gas-intensive zkevm tests timing out in EELS.
It does so by:
- Creating a `tests-deployed-zkevm` tox environment which runs only zkevm tests and it uses `evmone-t8n` to do so.
- Removing `zkevm` marked tests from `tests-deployed` tox environment.
None

feat(ci,tox): Create `tests-deployed-zkevm` tox env, and ci workflow

---

tests/zkevm/test_worst_compute.py

This adds the benchmarks for EVM execution focused on binary instructions (takes two values, produces one).
The benchmark has simple structure: the contract code is the infinite loop will up to the code size limit with the parametrized binop applied to two initial values balanced with DUP2 instruction.
https://github.com/ethereum/execution-spec-tests/issues/1571

feat(tests): add benchmarks with mass binop opcodes

---

.gitignore

I also noticed while working with VS Code's debugger that my personal launch.json file was being tracked by git. This PR adds it to .gitignore to prevent accidental commits of personal debugging configurations.
This addresses issue #1622
Fixes #1622.

chore(tooling): add `.vscode/launch.json` to `.gitignore`

---

src/ethereum_clis/clis/ethrex.py
src/pytest_plugins/consume/hive_simulators/exceptions.py

Adds exception mapping for [ethrex](https://github.com/lambdaclass/ethrex) errors on consume tests

feat: add support for ethrex client

---

.github/workflows/coverage.yaml
tox.ini

Introduces to fixes to the CI:
- Coverage script now uses `--skip-evm-dump` to avoid dumping too many files to storage
- Coverage script also now uses `--block-gas-limit 36000000` to limit runtime of gas-intensive tests
- Tox workflow `zkevm` now also uses `--block-gas-limit 36000000`
None

fix(github/coverage,tox): Use skip-evm-dump for fill, add block-gas-limit to zkevm tox

---

.github/workflows/coverage.yaml
tests/zkevm/test_worst_bytecode.py
tests/zkevm/test_worst_stateful_opcodes.py
tox.ini

This PR adds zkvm tests for the cases described in https://github.com/ethereum/execution-spec-tests/issues/1583.
Soon I'll add here the run results.
Closes https://github.com/ethereum/execution-spec-tests/issues/1583
Cycles ascending:
```
tests/zkevm/test_worst_stateful_opcodes.py::test_worst_storage_access_cold[fork_Cancun-blockchain_test-absent_slots_True-SSTORE same value]-2   21508283
tests/zkevm/test_worst_stateful_opcodes.py::test_worst_storage_access_cold[fork_Cancun-blockchain_test-absent_slots_True-SSTORE new value]-2    21635414
tests/zkevm/test_worst_stateful_opcodes.py::test_worst_address_state_cold[fork_Cancun-blockchain_test-absent_targets_True-opcode_BALANCE]-1     116777803
tests/zkevm/test_worst_stateful_opcodes.py::test_worst_storage_access_cold[fork_Cancun-blockchain_tes …
```

zkvm: add stateful opcodes attacks

---

docs/CHANGELOG.md
pyproject.toml
src/pytest_plugins/consume/hive_simulators/conftest.py
src/pytest_plugins/filler/static_filler.py
tests/berlin/eip2930_access_list/test_tx_intrinsic_gas.py
uv.lock

Updates to pytest 8.3.5 (from pytest 7.4.4).
Sanity checks:
None

chore(deps,pytest): update pytest to v8

---

tests/zkevm/test_worst_compute.py

Add a worst-case test running a block with as many MOD instructions with arguments of the parametrized range.
https://github.com/ethereum/execution-spec-tests/issues/1571

feat(tests): add worst-case benchmark for `MOD`

---

tests/prague/eip2537_bls_12_381_precompiles/conftest.py
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_pairing.py

Fixes multi-inf tests in EIP-2537 to make them dynamic according to the set evn.gas_limit.
Test was failing with fill parameter `--block-gas-limit=36000000` due to the hard-coded number of pairings.
The test now uses a look to search for the maximum number of pairings that can fit within limit.
None

fix(tests): EIP-2537: Make pairing test dynamic to env.gas_limit

---

tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py

Add real point evaluation precompile input from Mainnet.

feat(tests): EIP-4844: add example input to the point evaluation

---

tests/istanbul/eip152_blake2/test_blake2_delegatecall.py

Reuse already defined constant `BLAKE2_PRECOMPILE_ADDRESS` in the blake2f precompile tests.

refactor(tests): EIP-152: reuse `BLAKE2_PRECOMPILE_ADDRESS`

---

.gitignore

Just a minor fix in `.gitignore`.
For newcomers, If they don't name their virtual environment `.venv`, the commands to install packages and possibly enter other cmds fail. You then get an instruction to either rename your virtual environment to `.venv` or use `--active`  to target the current virtual environment. If I decide to use `.venv` for simplicity, and for mere mortals like us using VS Code, `.venv` not being ignored by git puts a toll on the source control widget, which is quite useful for tracking files and resolving merge conflicts among other benefits.

chore(tooling): add `.venv/`, `logs/`, `fixtures-*` to `.gitignore`

---

pytest-execute-hive.ini
pytest-execute.ini

Adds the `ported_from` marker to the `pytest-execute*.ini` files to suppress a warning from appearing when running the command.
None

fix(pytest): Add `ported_from` to execute

---

tests/zkevm/test_worst_compute.py

This PR adds a test that executes an empty block (i.e., no txs).
This test mainly aims to discover the baseline cycle cost for zkVMs.

zkevm: add empty block execution

---

docs/CHANGELOG.md
tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py

This PR refactors the `SELFDESTRUCT` collision tests that used hard-coded addresses to instead use the `pre` fixture from the `pre_alloc` plugin.
Diffed the traces and evm execution is identical, interestingly:
1. Call data size changed: e.g. from 0x23 to 0x35 (line 3) - because now the initcode contains full 20 byte addresses instead of hard-coded addresses that occupy less bytes.
2. Gas values are slightly different: due to different initial allocations.
None

refactor(tests): use the `pre` fixture in `SELFDESTRUCT` collision tests

---

.github/configs/feature.yaml
docs/CHANGELOG.md
whitelist.txt

Add features:
- zkEVM with 60 million block gas limit
- zkEVM with 90 million block gas limit
- zkEVM with 120 million block gas limit
None

feat(github): Add zkevm 60M, 90M, 120M

---

tests/zkevm/test_worst_compute.py

This PR adds a new test to cover `bn128_pairings` but trying to amortize the base cost.
```
tests/zkevm/test_worst_compute.py::test_worst_precompile_fixed_cost[fork_Cancun-blockchain_test-bn128_one_pairing]-1    18246172460
tests/zkevm/test_worst_compute.py::test_amortized_bn128_pairings[fork_Cancun-blockchain_test]-1 18288797103
tests/zkevm/test_worst_compute.py::test_worst_precompile_fixed_cost[fork_Cancun-blockchain_test-bn128_two_pairings]-1   18686110369
```
Initially, I thought this amortized one had 8 billion cycles, but now I'm wondering if I missed one digit. These numbers make more sense.

zkevm: amortized bn128_pairings

---

src/pytest_plugins/consume/consume.py

Silences tarfile `DeprecationWarning` for fixture downloads in python 3.13!
Fixes #1423.

chore(fill): Silence tarfile DeprecationWarning in fixture download

---

.github/workflows/coverage.yaml
docs/CHANGELOG.md
src/pytest_plugins/filler/ported_tests.py

Fixes the coverage script on PRs that convert no tests by adding `--ported-from-output-file` to the fill command.

fix(github/coverage): Fix coverage script on PRs that do not convert tests

---

tests/zkevm/test_worst_compute.py
tests/zkevm/test_worst_stateful_opcodes.py

Convert benchmarks with single transaction to `state_test()`.

refactor(tests/zkevm): downgrade to state tests

---

tests/zkevm/test_worst_compute.py

This PR adds tests for `BLOBHASH` covering three cases:
- No blobs and access to index 0.
- One blob and access it via `BLOBHASH(0)` (positive)
- One blob and access non-existent index `BLOBHASH(1)`.
- Six blobs and access latest `BLOBHASH(5)`.
Cycles:
```
tests/zkevm/test_worst_compute.py::test_worst_blobhash[fork_Cancun-blockchain_test_from_state_test-no blobs]-1  756458180
tests/zkevm/test_worst_compute.py::test_worst_blobhash[fork_Cancun-blockchain_test_from_state_test-one blob but access non-existent index]-1    765426911
tests/zkevm/test_worst_compute.py::test_worst_blobhash[fork_Cancun-blockchain_test_from_state_test-six blobs, access latest]-1  1143120660
tests/zkevm/test_worst_compute.py::test_worst_blobhash[fork_Cancun-blockchain_test_from_state_test-one blob and accessed]-1 …
```

zkevm: add BLOBHASH test

---

tests/zkevm/test_worst_compute.py

This PR adds a benchmark for `CALLDATALOAD` covering both existinga and absent referenced calldata word.
Cycles:
```
tests/zkevm/test_worst_compute.py::test_worst_calldataload[fork_Cancun-blockchain_test_from_state_test-empty]-1 2015522043
tests/zkevm/test_worst_compute.py::test_worst_calldataload[fork_Cancun-blockchain_test_from_state_test-one-loop]-1      2363234163
tests/zkevm/test_worst_compute.py::test_worst_calldataload[fork_Cancun-blockchain_test_from_state_test-zero-loop]-1     2423217008
```
Targets #1657

zkevm: add CALLDATALOAD benchmark

---

src/cli/pytest_commands/processors.py

Fixes an issue introduced in #1654: `pytest_plugins.pytest_hive.pytest_hive` was not added to the arguments required to execute consume with hive.
None

fix(cli): Add `pytest_plugins.pytest_hive.pytest_hive` to Hive processor

---

.github/actions/build-fixtures/action.yaml
.github/configs/evm.yaml
tests/unscheduled/eip7692_eof_v1/eip7069_extcall/test_calldata.py
tests/unscheduled/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
tests/unscheduled/eip7692_eof_v1/eip7620_eof_create/test_memory.py
tests/unscheduled/eip7692_eof_v1/eip7620_eof_create/test_returncode.py
tests/unscheduled/eip7692_eof_v1/eip7873_tx_create/test_txcreate.py

Minor fixup to eof tests done in order to make a final release with the `EOFv1` pseudo-fork. This may make it easier to maintain EOF impl for teams which decide to.
NA

 fix(tests,eof): Specify Env(gas_limit)

---

src/pytest_plugins/shared/helpers.py

See #1680. 
@marioevz, can you please check whether this fix is enough?
Fixes:
- #1680

fix(execute): default to False if the option doesn't exist

---

docs/writing_tests/index.md
tests/berlin/eip2930_access_list/test_acl.py

Removes the unnecessary and hard-coded `secret_key` field from the `Transaction` used in `tests/berlin/eip2930_access_list/test_acl.py::test_access_list`. This is not required if `pre_alloc`'s `eoa_address_iterator` returns the default `TestAddress` and breaks in the case that the `eoa_address_iterator` has a global scope instead of the current function-level scope.
None
- ~[ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).~ skipped

refactor(tests): remove `secret_key` from `test_access_list`'s transaction

---

tests/zkevm/test_worst_compute.py

This PR adds coverage for many 0-param opcodes.
Cycles:
```
tests/zkevm/test_worst_compute.py::test_worst_zero_param[fork_Cancun-blockchain_test_from_state_test-opcode_GAS]-1      927313344
tests/zkevm/test_worst_compute.py::test_worst_zero_param[fork_Cancun-blockchain_test_from_state_test-opcode_TIMESTAMP]-1        945280386
tests/zkevm/test_worst_compute.py::test_worst_zero_param[fork_Cancun-blockchain_test_from_state_test-opcode_GASLIMIT]-1 945298712
tests/zkevm/test_worst_compute.py::test_worst_zero_param[fork_Cancun-blockchain_test_from_state_test-opcode_NUMBER]-1   945298968
tests/zkevm/test_worst_compute.py::test_worst_callvalue[fork_Cancun-blockchain_test_from_state_test-from_origin_False-non_zero_value_True]-1    983444990 …
```

zkevm: add 0-param opcodes coverage

---

src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
tests/zkevm/test_worst_bytecode.py
tests/zkevm/test_worst_compute.py
tests/zkevm/test_worst_stateful_opcodes.py

This PR expands the benchmark test which queries as many other accounts (`EXTCODE*` and `CALL*` operations) by also providing a max code size setting in the fork.
- Adds `max_code_size()` to forks
- Adds `max_initcode_size()` to forks
- Edits benchmark test to calculate a correct gas limit w.r.t. deploying the to-be-attacked contracts vs. the actual contract
Note that the deposit costs for the EIP-7907 are much higher (relative) than the original costs. This includes the 200 gas/byte code deposit cost, but also the quadratic memory expansion cost.
The cost of querying one such contract (the "loop cost" of the benchmark) is calculated as 2687 gas/contract. The deposit however costs at least 52M gas due to the 200 gas/byte deposit cost of the 0x40000 bytes. So the cost to deposit such …

feat(tests): Update benchmark test to query newly introduced `max_code_size()` from fork config

---

.github/workflows/coverage.yaml
docs/CHANGELOG.md
eels_resolutions.json
src/ethereum_clis/clis/besu.py
src/ethereum_clis/clis/erigon.py
src/ethereum_clis/clis/geth.py
src/ethereum_clis/clis/nethermind.py
src/ethereum_clis/clis/nimbus.py
src/ethereum_clis/clis/reth.py
src/ethereum_test_exceptions/exceptions.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
tests/osaka/eip7825_transaction_gas_limit_cap/__init__.py
tests/osaka/eip7825_transaction_gas_limit_cap/test_transaction_gas_limit_cap.py
tests/osaka/eip7825_transaction_gas_limit_cap/test_tx_gas_limit.py

Tests for [EIP-7825](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7825.md), imposing a 30 million gas limit to every transaction type.
N/A

feat(tests): EIP-7825: Transaction Gas Limit Cap

---

pyproject.toml
uv.lock

Bump eels resolver to use the latest commit which includes the following PR: https://github.com/petertdavies/ethereum-spec-evm-resolver/pull/10
The PR silences bloat GET request & I/O error messages so we can debug better when using `-s`.
N/A.

chore: use latest eels resolver

---

src/ethereum_test_fixtures/shared_alloc.py

Performs two fixes:
- Use correct name for function `model_post_init`
- Don't raise exception on duplicated accounts in the pre for multiple xdist workers. Reason being that we normally have consistent contracts across tests, for example system contracts.

fix(filler): Fix shared-pre-state on xdist

---

tests/zkevm/test_worst_compute.py

Adding benchmark test for the `P256VERIFY` precompile contract.
Issue: https://github.com/ethereum/execution-spec-tests/issues/1734

feat(zkevm): add p256verify to worst compute tests

---

docs/CHANGELOG.md
tests/zkevm/test_worst_blocks.py

In Nethermind’s test case, a block is filled with simple Ether transfer transactions, each transferring 1 wei. The purpose of this PR is to reproduce a specific scenario and expand test coverage. Four scenarios are included, as outlined below:
1. Account A sends Ether to itself
2. Account A sends Ether to Account B
3. Account A sends Ether to multiple different accounts
4. Multiple different accounts send Ether to Account A
Issue https://github.com/ethereum/execution-spec-tests/issues/1734

feat(zkevm): create pure ether transfer worst case

---

tests/zkevm/test_worst_compute.py

There is an issue with the original test case: the jump target is not a valid `JUMPDEST` operation.
More details could be found in the [discussion](https://github.com/ethereum/execution-spec-tests/pull/1693#discussion_r2122967972). 
The updated version precomputes valid jump destinations to improve the density of `JUMP` operations.
The repeated pattern is structured as follows:
```
0x00 PUSH2 DEST
0x03 JUMP
0x04 JUMPDEST
...
```
The first `JUMPDEST` is at offset `0x04`. Since each pattern occupies 5 bytes, subsequent `JUMPDEST` locations can be calculated as `4 + 5 * i`, where i is the pattern index. The total code size must remain within the allowed limit.

fix(tests/zkevm): update jump seq for valid dest

---

tests/zkevm/test_worst_compute.py

Create worst test cases for SWAP1-16 opcode.
Issue https://github.com/ethereum/execution-spec-tests/issues/1687

feat(zkevm/tests): add worst case tests for SWAP opcodes

---

docs/CHANGELOG.md
eels_resolutions.json
src/ethereum_test_tools/tests/test_code.py
tests/osaka/eip7939_count_leading_zeros/spec.py
tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py
whitelist.txt

Adds some updates and extra cases for the CLZ opcode test cases (EIP-7939).
N/A

feat(tests): updates eip7939 test cases

---

docs/CHANGELOG.md
eels_resolutions.json
src/ethereum_test_tools/tests/test_code.py
src/ethereum_test_vm/opcode.py
tests/osaka/eip7939_count_leading_zeros/__init__.py
tests/osaka/eip7939_count_leading_zeros/spec.py
tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py
whitelist.txt

Adds tests for CLZ ([EIP-7939](https://eips.ethereum.org/EIPS/eip-7939)).
N/A

feat(tests): add CLZ opcode EIP-7939) tests

---

tests/zkevm/test_worst_compute.py

Add the DUP opcode for zkevm tests.
This PR would be blocked until the PR https://github.com/ethereum/execution-spec-tests/pull/1768 is merged, as it would use EVM stack limit as a parameter.
Issue https://github.com/ethereum/execution-spec-tests/issues/1687

feat(zkevm/test): add worst case test for multiple DUP opcodes

---

docs/CHANGELOG.md
docs/running_tests/hive/dev_mode.md

Adds a workaround to run `./hive --dev` mode from macOS to the documentation.
N/A

docs(consume,execute): add hive dev mode macOS workaround

---

src/ethereum_clis/clis/besu.py
src/ethereum_clis/clis/erigon.py
src/ethereum_clis/clis/geth.py
src/ethereum_clis/clis/nethermind.py
src/ethereum_clis/clis/nimbus.py
src/ethereum_clis/clis/reth.py

Updates the exception mapper for EIP-7934. Note a temporary error is added to Nimbus for now.
#1730

chore(cli): add block rlp size limit exceptions

---

.github/configs/eels_resolutions.json
.github/workflows/tox_verify.yaml
pyproject.toml
src/ethereum_clis/transition_tool.py
src/ethereum_test_types/account_types.py
src/ethereum_test_types/trie.py
src/pytest_plugins/execute/rpc/hive.py
uv.lock

This PR is a related to #1763. It is the first part of the STEEL merge. It aims to remove the dependency that EEST has on EELS.
Closes #1735:
- #1735

chore(deps): remove dependency on `ethereum-execution`

---

src/ethereum_clis/clis/ethrex.py

- We've changed some error strings in Ethrex so this is for fixing the tests and passing them all :)
- I also add mapping for `SYSTEM_CONTRACT_EMPTY`, that we didn't have before.

fix(clis/ethrex): fix ethrex error mapping

---

docs/CHANGELOG.md
src/pytest_plugins/consume/simulators/hive_tests/test_via_engine.py

Adds a simple exponential retry for the initial fcu within consume engine.
Using generic retry logic on all RPC calls were considered via #1532, however, this case specifically requires us keep calling the initial fcu until the client is no longer syncing. There may be cases in the future where we want to check syncing in other scenarios.
Following a comment from @danceratopz:
> Hive allows the simulator to define a "check live port" which is used to verify that the client has finished starting up: 
> https://github.com/ethereum/execution-spec-tests/blob/851f9f5bc88d25f869a7fcd7798b10b9c5bceb7e/src/pytest_plugins/consume/simulators/single_test_client.py#L34-L47
> For the engine simulator it's 8551, for example:
> https://github.com/ethereum/execution-spec-tests/blob/851f9f5bc88d25f869a7fcd …

chore(consume): retry logic for initial consume engine fcu

---

.github/workflows/tox_verify.yaml

Added a self hosted runner to the longest running test: `Fill tests, deployed, ubuntu-latest, 3.11`. It looks like we can just specify a self-hosted runner and it will spin one up on demand. Explored adding a self-hosted runner to both unit tests and the zkevm tests, but neither one made a difference. This optimization saves ~5 minutes every run.
N/A.
```console
```
Does this warrant an entry into the CHANGELOG?

chore(ci): Add self hosted runner to Ubuntu tests_deployed Github workflow

---

.github/workflows/coverage.yaml

Fixes the check for modified/deleted files when deciding whether to fill pre-patched tests
N/A.
```console
```

fix(github): Coverage check for modified files

---

docs/CHANGELOG.md
src/cli/extract_config.py
src/cli/order_fixtures.py
src/ethereum_clis/transition_tool.py
src/ethereum_test_base_types/base_types.py
src/ethereum_test_base_types/pydantic.py
src/ethereum_test_fixtures/collector.py
src/ethereum_test_rpc/rpc.py
src/ethereum_test_rpc/types.py
src/ethereum_test_specs/base.py
src/ethereum_test_specs/helpers.py
src/ethereum_test_specs/static_state/common/compile_yul.py
src/ethereum_test_tools/code/generators.py
src/ethereum_test_tools/utility/generators.py
src/ethereum_test_types/account_types.py
src/ethereum_test_types/trie.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/logging/logging.py
src/pytest_plugins/pytest_hive/pytest_hive.py
tests/istanbul/eip152_blake2/test_blake2.py

This PR modernizes the EEST codebase to leverage Python 3.11+ language features (and some neglected 3.10 features) for improved performance, readability, type safety, and security.
**Benefits**: Eliminates boilerplate `TypeVar` declarations, improves type safety, and makes method signatures cleaner and more intuitive.
Replace `TypeVar` bound patterns with `Self` type for cleaner method signatures:
```python
T = TypeVar("T", bound="BaseTest")
def from_test(cls: Type[T], **kwargs) -> T:
def from_test(cls: Type[Self], **kwargs) -> Self:
```
**Benefits**: More readable and explicit about intent, slightly more performant (avoids `len()` calculations), and reduces potential off-by-one errors in manual slicing.
Replace manual string slicing with explicit prefix/suffix removal:
```python
if …
```

refactor(all): modernize codebase with python 3.11 features

---

tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py

`test_mcopy_memory_expansion.py` tests assumes that there is not explicit transaction gas limit and that the transaction gas limit is just the same as the block gas limit. The osaka fork introduces an explicit transaction gas limit.
#1828
```console
```

bug(tests): enforce transaction gas limit in Osaka

---

tests/prague/eip2537_bls_12_381_precompiles/conftest.py

This PR removes the automatic `zkevm` marker to `tests/prague/eip2537_bls_12_381_precompiles`.
We talked with @kevaundray, and these tests were an initial experiment for the zkEVM efforts, which later got more formalized in the `zkevm` folder. We propose removing them since BLS12381 precompiles are already more formally covered.
@danceratopz, please take a look, as I'm reverting the part of your PR that **I think** achieves what we want. :smile: 
- [Original PR that added them](https://github.com/ethereum/execution-spec-tests/pull/1514)
- [Later automatic marking](https://github.com/ethereum/execution-spec-tests/pull/1534)

refactor(benchmark): don't mark the BLS12-381 tests for benchmarking

---

tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

Add two extra scenario:
1. JUMP and JUMPI operation
2. If the jump operation jumps to valid/invalid desitnation -> valid: `JUMPDEST`, invalid: `CLZ`
Issue https://github.com/ethereum/execution-spec-tests/issues/1795
```console
```

feat(tests): add jump operation test case for CLZ

---

.github/configs/feature.yaml
eels_resolutions.json
tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py
tests/shanghai/eip3860_initcode/test_initcode.py

- Fixes issues with the CLZ (EIP-7939) transition tests. Previously not catched when running `uv run fill --fork Osaka`. **Note this is correctly added in the devnet 2 release.**
- Fixes the `feature.yaml` fill params from previous PR.
#1774

chore(ci|tests): more updates for fusaka devnet 2 release

---

.vscode/settings.json

Yesterday I wasted CI resources because I forgot to manually remove an unused import even though I had saved the file. With this change ruff with autofix (includes removing unused imports) on save, so this should not happen again. 
This PR includes a second change, the folder `tests/legacy` does not exist anymore so we should instead skip the folders `tests/static` and `tests/unscheduled` 
N/A.
```console
```

tooling(fix): ruff autofix on save + filter static and unscheduled tests

---

tests/benchmark/test_worst_compute.py

This PR adds coverage for `RETURN` and `REVERT`.
Cycles:
```
test_worst_compute.py::test_worst_return_revert[fork_Cancun-blockchain_test_from_state_test-1MiB of zero data-opcode_REVERT]-1  19759096
test_worst_compute.py::test_worst_return_revert[fork_Cancun-blockchain_test_from_state_test-1MiB of zero data-opcode_RETURN]-1  19779138
test_worst_compute.py::test_worst_return_revert[fork_Cancun-blockchain_test_from_state_test-1MiB of non-zero data-opcode_RETURN]-1      24151658
test_worst_compute.py::test_worst_return_revert[fork_Cancun-blockchain_test_from_state_test-1MiB of non-zero data-opcode_REVERT]-1      24167501
test_worst_compute.py::test_worst_return_revert[fork_Cancun-blockchain_test_from_state_test-1KiB of non-zero data-opcode_RETURN]-1      1422016887 …
```

feat(benchmark): add RETURN and REVERT coverage

---

docs/CHANGELOG.md
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/tests/test_fixtures_source_input_types.py

* Adds cache_folder parameter to all FixturesSource.from_* methods
* Updates pytest_configure to pass the user-provided cache folder
* Updates existing tests to work with the new parameter signature
Fixes #1834
```console
```

fix(consume): fix consume cache's --cache-folder flag

---

docs/CHANGELOG.md
tests/prague/eip7702_set_code_tx/test_set_code_txs.py

- Fix fails while filling due to invalid LOG opcode kw arg fails.
- Fix-up changelog: Add missing links to the PR; Remove "Refactoring" subsection. Both Claude hiccups.
@marioevz @spencer-tb we need bump Prague to deployed and fill Prague in CI :cry: 
Small fix-up to:
- #1739
```console
```

fix(tests): fix invalid log opcode keyword 7702 fails

---

tests/benchmark/test_worst_bytecode.py

This PR adds coverage for opcodes `CREATE` and `CREATE2`. This includes both successful executions and collision failures.
Cycles:
```
test_worst_bytecode.py::test_worst_create[fork_Cancun-blockchain_test_from_state_test-max code size with zero data-opcode_CREATE]-1     3323528
test_worst_bytecode.py::test_worst_create[fork_Cancun-blockchain_test_from_state_test-0.75x max code size with zero data-opcode_CREATE]-1       3337862
test_worst_bytecode.py::test_worst_create[fork_Cancun-blockchain_test_from_state_test-max code size with zero data-opcode_CREATE2]-1    3376118
test_worst_bytecode.py::test_worst_create[fork_Cancun-blockchain_test_from_state_test-0.75x max code size with zero data-opcode_CREATE2]-1      3377367
test_worst_bytecode.py::test_worst_create[fork_Cancun-blockchain_test_fro …
```

feat(benchmark): add coverage for CREATE and CREATE2

---

tests/osaka/eip7951_p256verify_precompiles/spec.py

Follow up ACDE#215 meeting, the gas cost of the `P256VERIFY` double down from 3450 to 6900.
Notes from ETH Magician: https://ethereum-magicians.org/t/allcoredevs-execution-acde-215-july-3-2025/24701/4?u=timbeiko
EIP update PR: https://github.com/ethereum/EIPs/pull/9978/files
Execution Spec PR: https://github.com/ethereum/execution-specs/pull/1304
```console
```

refactor(tests): double P256VERIFY gas constant

---

.github/configs/feature.yaml
docs/CHANGELOG.md

This PR proposes adding two extra "low gas" cases for being included in benchmark releases.
The motivation is that for zkEVMs using the benchmarks, it is helpful to have low gas cases to:
- Be able to have CI pipelines that don't take so much time.
- We're validating the assumption that proving times are linearly related to gas costs. If this is the case, it would be acceptable to run experiments with gas cost changes on lower gas and obtain results faster (e.g., 1M or 10M, depending on whether it is a single GPU or multi-GPU prover).
I think 1M and 10M are reasonable. I was tempted to include a 500k but I think we can avoid it for now, and let reality tell us better (e.g., maybe in the future is better to change 1M to 500k instead of adding 500k, etc).
cc @kevaundray

feat(github): add benchmarks releases for 1M and 10M gas limit

---

CLAUDE.md
pytest-framework.ini
src/cli/gentest/tests/test_cli.py
src/cli/tests/test_pytest_fill_command.py
src/conftest.py
src/ethereum_clis/clis/execution_specs.py
src/ethereum_clis/transition_tool.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_filler.py
src/pytest_plugins/filler/tests/test_output_directory.py
tox.ini

Adds a new flag to t8n in order to be able to pass an already-running t8n server to run unit tests.
This allows us to use a single eels resolver server instance in all unit tests and speed up test running considerably.
The unit test marker `run_in_serial` is removed since now all tests can run in parallel without issues.
`uvx --with=tox-uv tox -e pytest` command:
- `pytest -c ./pytest-framework.ini -n auto -m 'not run_in_serial'` - 103.30s (0:01:43)
- `pytest -c ./pytest-framework.ini -m run_in_serial` - 96.13s (0:01:36)
-  Total - 199.43s (0:03:19)
`uvx --with=tox-uv tox -e pytest` command:
- `pytest -c ./pytest-framework.ini -n auto` - 29.46s (0:00:29)
-  Total - 29.46s (0:00:29)
N/A.
```console
```

fix(ci): All slow unit tests, remove `run_in_serial`

---

tests/osaka/eip7939_count_leading_zeros/spec.py
tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

Add CODECOPY / EXTCODECOPY for CLZ opcode
N/A.
Issue https://github.com/ethereum/execution-spec-tests/issues/1795
```console
```

feat(tests): add codecopy and extcodecopy for clz opcode

---

tests/osaka/eip7951_p256verify_precompiles/vectors/secp256r1_test.json

Small filling fix via: #1857 
Fill with this Osaka in `eels_resolutions.json`:
```json
"Osaka": {
"git_url": "https://github.com/spencer-tb/execution-specs.git",
"branch": "forks/osaka",
"commit": "bff77defcfa5be8130cdc6c4ec8200104e22dd8f"
}
```
N/A.
```console
```

chore(tests): update gas field in eip-7951 r1 vectors

---

tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

During the ACDT meeting, we decided to increase the gas cost of CLZ from 3 to 5. This change has been updated in the [PR](https://github.com/ethereum/execution-spec-tests/pull/1879). However, it breaks some existing test cases, which are addressed and fixed in this PR. Additional details are provided below.
PR for EEST: https://github.com/ethereum/execution-spec-tests/pull/1879
PR for EIP: https://github.com/ethereum/EIPs/pull/9987
PR for EELS: https://github.com/ethereum/execution-specs/pull/1314
Fill with this Osaka in `eels_resolutions.json`:
```json
"Osaka": {
"git_url": "https://github.com/spencer-tb/execution-specs.git",
"branch": "forks/osaka",
"commit": "bff77defcfa5be8130cdc6c4ec8200104e22dd8f"
}
```
```console
```

chore(tests): update gas cost configuration for clz

---

pyproject.toml
src/pytest_plugins/filler/static_filler.py
uv.lock

Pydantic recently greatly [optimized their memory efficiency](https://github.com/pydantic/pydantic/issues/9982#issuecomment-2639658045) which can help reduce our memory footprint (especially when filling static tests). Filling static tests used to require around 36 GB of memory on our dev server but with updated pydantic version it now seems to take less than 12 GB to fill all static tests. This PR not only updates pydantic but also all other dependencies (within the ranges specified by our pyproject.toml)
Idk if the result is fully reproducible (any package could release an update any second) but using python 3.12.10 I ran these commands:
```
uv self update
uv sync --all-extras
uv sync --all-extras --upgrade
```
The fixtures have not changed. Steps taken:
Main (before):
* `uv run fill …

chores(tooling): update uv lock

---

uv.lock

#1886 upgraded EEST's `uv.lock` with `uv < 0.7.0`, which generated a `uv.lock` in the format of revision 1. This PR:
- Regenerates the `uv.lock` with uv.lock revision 2 in order to better detect changes when upgrading future packages.
- Updates `certifi` from `v2025.7.9` -> `v2025.7.14`.
See #1904, which will ensure that this particular issue can't happen again.
Follow-up to:
- #1886
See also:
- #1904 
```console
```

chore(deps): restore `uv.lock` revision to v2; upgrade `certifi`

---

pyproject.toml

The kzg setup file needs to be specified in the `*.toml` file. This is important while installing eest as a library.
```console
```

feat(packaging,types): add kzg setup to package-data

---

docs/CHANGELOG.md
src/ethereum_test_forks/forks/forks.py

The blob_base_cost parameter in EIP-7918 was updated as per this [PR](https://github.com/ethereum/EIPs/pull/9979) and needs to be reflected in the tests
```console
```

chore(forks): update blob base cost in forks

---

docs/CHANGELOG.md
docs/writing_tests/test_markers.md
src/cli/pytest_commands/pytest_ini_files/pytest-check-eip-versions.ini
src/cli/pytest_commands/pytest_ini_files/pytest-execute-hive.ini
src/cli/pytest_commands/pytest_ini_files/pytest-execute.ini
src/cli/pytest_commands/pytest_ini_files/pytest-fill.ini
src/pytest_plugins/forks/forks.py
src/pytest_plugins/forks/tests/test_covariant_markers.py
src/pytest_plugins/forks/transaction_fixtures.py
src/pytest_plugins/shared/execute_fill.py
src/pytest_plugins/shared/transaction_fixtures.py
tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
tests/cancun/eip6780_selfdestruct/conftest.py
tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
tests/osaka/eip7934_block_rlp_limit/conftest.py
tests/osaka/eip7934_block_rlp_limit/spec.py
tests/osaka/eip7934_block_rlp_limit/test_max_block_rlp_size.py
tests/osaka/eip7951_p256verify_precompiles/conftest.py
tests/prague/eip7623_increase_calldata_cost/conftest.py
tests/prague/eip7702_set_code_tx/test_calls.py
tests/shanghai/eip3651_warm_coinbase/conftest.py
tests/shanghai/eip3855_push0/conftest.py
tests/shanghai/eip3860_initcode/conftest.py
tests/shanghai/eip4895_withdrawals/conftest.py
tests/unscheduled/eip7692_eof_v1/eip7069_extcall/test_calls.py

- Add test case for RLP block size at limit with all transaction types, including blobs, access lists, and authorizations
- Add test case for RLP block size at limit with logs emitted
Related to #1772 
- This was done via `with_all_typed_transactions` indirect (new feature) marker
```console
```

feat(tests): Additional EIP-7934 test cases

---

docs/CHANGELOG.md
src/cli/eest/cli.py
src/cli/eest/make/cli.py
src/cli/eest/make/commands/env.py
src/cli/eest/make/commands/test.py
src/cli/eofwrap.py
src/cli/gentest/tests/test_cli.py
src/pytest_plugins/consume/simulators/base.py
src/pytest_plugins/consume/simulators/simulator_logic/test_via_engine.py
src/pytest_plugins/consume/simulators/simulator_logic/test_via_rlp.py
src/pytest_plugins/consume/simulators/single_test_client.py
src/pytest_plugins/consume/simulators/test_case_description.py
src/pytest_plugins/consume/tests/test_fixtures_source_input_types.py
src/pytest_plugins/execute/execute.py
src/pytest_plugins/execute/rpc/hive.py
src/pytest_plugins/filler/tests/test_filler.py
src/pytest_plugins/filler/tests/test_output_directory.py
src/pytest_plugins/shared/execute_fill.py

Convert absolute imports to relative imports within the same package
Changes affect:
* CLI components (eest, eofwrap)
* Test files across all packages
* Pytest plugin components (consume, execute, filler)
* Framework utility modules
N/A.
Related to #1844 #1848
```console
```

style(tools): convert absolute to relative imports across codebase

---

tests/benchmark/test_worst_bytecode.py

In #1864 I realized a problem with the EXTCODECOPY test. It copies to memory to offset 85. This is correct if the CREATE2 hash alignment starts at 0. It however starts at byte 11 (the address starts at 12). This means that the memory region `[11,96)` is occupied by the bytes to hash to get the correct address. If we thus EXTCODECOPY to byte 85, we overwrite the bytes there (initcode hash is stored there). This means that all EXTCODECOPYs after the first one target incorrect addressess, i.e. they have empty code.
I checked this file if there are more of these tests but this seem to be the only one. (This could be a problem with other tests also using CREATE2 and using operations which writes to memory. It should not overwrite the to-be-hashed data to retrieve the CREATE2 address created …

fix(tests): fixes EXTCODECOPY bench test

---

.github/configs/feature.yaml

From the zkEVM benchmark perspective, we are close to start running the full benchmark suite across multiple zkVMs. Thinking with @kevaundray around which gas limit to use, we think using the current mainnet gas limit would be ideal.
While proving times should be linear with the gas limit, publishing results with 30M gas makes the interpretation of numbers a bit harder. Also, not only are proving times important, but also "memory usage" inside the zkVMs -- and many zkVMs have tight max memory limits which we might not reach with 30M, but we might with 45M (current gas limit), so we might not catch a crash.
This PR proposes adding 45M to the list and modifying it over time to always represent the current gas limit on mainnet.
cc @marioevz

chore(ci/benchmark): add current mainnet gas limit

---

.github/actions/build-fixtures/action.yaml
.github/configs/feature.yaml

Minor fix to remove deprecated `--solc-version` flag from the fixture-building github action.
N/A.
```console
```

fix(github): Remove `--solc-version` flag from fixture building action

---

pyproject.toml
src/ethereum_clis/ethereum_cli.py
src/pytest_plugins/consume/simulators/rlp/conftest.py
src/pytest_plugins/forks/forks.py

Before:
```
src/ethereum_test_base_types/reference_spec/git_reference_spec.py:10: error: Library stubs not installed for "requests"  [import-untyped]
src/ethereum_clis/ethereum_cli.py:92: error: Incompatible types in assignment (expression has type "Path", variable has type "str | None")  [assignment]
src/pytest_plugins/consume/releases.py:13: error: Library stubs not installed for "requests"  [import-untyped]
src/ethereum_test_base_types/tests/test_reference_spec.py:6: error: Library stubs not installed for "requests"  [import-untyped]
src/ethereum_clis/transition_tool.py:16: error: Library stubs not installed for "requests"  [import-untyped]
src/ethereum_clis/transition_tool.py:17: error: Library stubs not installed for "requests.exceptions"  [import-untyped] …
```

fix(mypy): adds mypy ignore comments and add ignore rule for imports

---

.github/configs/eels_resolutions.json
pyproject.toml
src/pytest_plugins/eels_resolutions.json
uv.lock

Bumps the EELS resolver to an updated commit. Should prevent EELS t8n timeouts when filling benchmark tests at 100M gas.
https://github.com/spencer-tb/ethereum-spec-evm-resolver
N/A.
```console
```

chore: bump eels resolver

---

tests/benchmark/test_worst_bytecode.py
tests/benchmark/test_worst_compute.py
tests/benchmark/test_worst_stateful_opcodes.py

Removes remaining zkevm markers from benchmark tests. 
Additionally removes all the slow markers on the assumption that all benchmark tests are slow. It that marker is intended to highlight benchmark tests that are extra slow I will add them back.
All of these tests have the benchmark marker implicitly added by default.
N/A.
```console
```

chore(tests): remove slow/zkevm markers from benchmark tests

---

src/ethereum_test_types/blob_types.py
src/ethereum_test_types/tests/test_blob_types.py

Introduces a mechanism that guarantees that the unit test that clears the blob cache folder (which is a requirement for it function as from our blob filenames we can not infer which fork they were created for) always runs after all other blob unit tests. This has never been a real problem outside of unit testing itself.
Related issue: #1942 
N/A.
```console
```

fix(unit_tests): fixed blob unit tests when run with xdist

---

src/cli/pytest_commands/pytest_ini_files/pytest-fill.ini
tests/benchmark/conftest.py
tox.ini

Updates EEST to not fill benchmark tests by default.
#1919 
```console
```

chore(benchmark): don't fill benchmark tests by default

---

docs/CHANGELOG.md
src/ethereum_test_specs/base.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/state.py
src/pytest_plugins/execute/execute.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/shared/benchmarking.py
src/pytest_plugins/shared/execute_fill.py
tests/benchmark/test_worst_blocks.py
tests/benchmark/test_worst_bytecode.py
tests/benchmark/test_worst_compute.py
tests/benchmark/test_worst_memory.py
tests/benchmark/test_worst_opcode.py
tests/benchmark/test_worst_stateful_opcodes.py
tox.ini

`blockchain_test` and `state_test` now have a flag called `expected_benchmark_gas_used` which can be used to specify the expected gas used by the last payload (the benchmark payload).
If the value is not specified, the test is expected to use the value specified by `--gas-benchmark-values` entirely.
All benchmark tests now use `gas_benchmark_value`, and also `expected_benchmark_gas_used` if the test is not expected to use the entire gas (e.g. when the tx is not expected to run out-of-gas and instead consume a specific amount of gas).
N/A.
```console
```

feat(specs,tests): Update all benchmark tests to use `gas_benchmark_value`

---

.github/workflows/tox_verify.yaml
src/pytest_plugins/eels_resolutions.json

Use the latest EELS `forks/osaka` for all.
Requires #1884.
```console
```

chore(ci): bump to use latest eels `forks/osaka`

---

src/ethereum_clis/clis/execution_specs.py

Specific exceptions were added to execution_spec `InvalidTransaction` types. This is a complementary update to accommodate for these specific exceptions.
Exception types and details are outlined here:
- https://github.com/ethereum/execution-specs/pull/1266
- https://github.com/ethereum/execution-specs/pull/1286
https://github.com/ethereum/execution-specs/issues/1021

feat(cli): resolve updated execution_spec exceptions

---

src/pytest_plugins/execute/rpc/hive.py
src/pytest_plugins/forks/forks.py
src/pytest_plugins/forks/tests/test_forks.py

Allows you to pass the fork either as uppercase or as lowercase.
Before this PR:
```
uv run fill -v tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add.py::test_valid --fork prague --clean -s
Executing: pytest -c /home/user/Documents/execution-spec-tests/src/cli/pytest_commands/pytest_ini_files/pytest-fill.ini --rootdir . -v 
tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add.py::test_valid --fork prague --clean -s
Error: Unsupported fork provided to --fork: prague 
```
After this PR: great success, no matter whether you choose Prague or prague
Inspired by #1916 
N/A.
```console
```

fix(fill): allow lowercase fork declaration in fill command

---

tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

Add `CALL`/`DELEGATECALL`/`STATICCALL`/`CODECALL` opcode interaction with CLZ
Issue https://github.com/ethereum/execution-spec-tests/issues/1795
```console
```

feat(tests): add call operation test case for CLZ

---

tests/osaka/eip7939_count_leading_zeros/test_count_leading_zeros.py

**Hardening Fusaka for EIP-7939**
Add two additional test cases for stack manipulation related to the CLZ (Count Leading Zeros) opcode:
1. No Stack Overflow
The CLZ operation must never cause a stack overflow, as it does not increase the number of items on the stack.
Test: Push 1022 items onto the stack, then execute CLZ 256 times while storing the result after each call. Ensure that no stack overflow occurs during this process.
2. Consistency Across Equivalent PUSH Operations
For the same numeric value pushed onto the stack, the CLZ opcode should yield the same result, regardless of which PUSH variant (PUSH1 to PUSH32) was used.
Examples:
- Pushing the value 0x01 using any PUSH1–PUSH32 should result in the same CLZ output.
- Pushing the value 0x0A000000 (10 00 00 00 in hex) using any …

feat(tests): extra stack operation test for CLZ opcode

---

tests/benchmark/test_worst_compute.py

Add benchmark test for CLZ opcode.
Issue https://github.com/ethereum/execution-spec-tests/issues/1795
```console
```

feat(benchmark): add clz opcode test case

---

docs/CHANGELOG.md
tests/osaka/eip7934_block_rlp_limit/test_max_block_rlp_size.py

Previously, I was using a random `sender` to fill the "fake" block when estimating the block rlp size. This PR fixes these tests to use the `sender` fixture instead for all transactions, instead of swapping with the real `sender` on the final block.
The issue here is that a signed transaction's signature fields, if they have leading zeros, these will be stripped in the rlp encoding. So we have variability across different senders with different signature fields on the final block rlp.
Not only is it not necessary to use a fake `sender` for the block filling and then swap it, it also leads to issues like these. This is fixed here, as well as always using the block gas limit from the `env`, rather than hard-coding as I originally did during Berlinterop when this test was written (refactor). …

fix(tests): Issues with rlp block limit tests and `--generate-pre-alloc-groups`

---

tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
tests/osaka/eip7934_block_rlp_limit/test_max_block_rlp_size.py
tests/prague/eip6110_deposits/test_modified_contract.py

Fixes the errors defined with https://github.com/ethereum/execution-spec-tests/issues/1955.
With the exception of:
```
test_max_block_rlp_size.py::test_block_rlp_size_at_limit_with_all_typed_transactions[fork_Osaka-typed_transaction_4-blockchain_test_engine_x]
AssertionError: Block RLP size 8388607 does not exactly match limit 8388608, difference: -1 bytes
```
For some reason we generate different fixtures for `type_4_default_transaction` within `transaction_fixtures.py` during phase 1 of `--generate-all-formats`.
**I've added a temporary solution for now.**
#1955
```console
```

chore(tests): fix pre alloc grouping remaining fails

---

tests/frontier/opcodes/test_call.py

Hi again! This is another test very similar to #1952 but this time we are testing that the memory should be expanded during a CALL even in cases where there’s an early revert. It seems obvious but previously we used to expand the memory after the sub-context execution and we were not expanding it in cases in which we reverted early (like a transfer without enough balance). We encountered this on a [sepolia transaction](https://sepolia.etherscan.io/tx/0xa1765d420522a40d59d15f8dee1bf095499be687d6e1a7c978fc87eb85bce948).
I tested this with an old ethrex commit and the test fails, but after the fix in the PR linked down below it passes 😄 
Any suggestions are welcome
On ethrex: https://github.com/lambdaclass/ethrex/pull/3592
```console
uvx --with=tox-uv tox -e …
```

feat(test): add test for memory expansion on early revert in CALL

---

tests/osaka/eip7934_block_rlp_limit/test_max_block_rlp_size.py

Removes temp fix added for type 4 tx in max size block rlp test.
#1989 #1955 
```console
```

chore(tests): remove temp fix for block rlp type 4

---

.github/configs/feature.yaml

Currently, the parameter for the `--gas-benchmark-values` flag start at 1 and end at 120, but for the gas benchmarking infrastructure in Nethermind, they use (30,60,80,100,150) as configuration, so it is updated accordingly.
None
```console
```

chore(benchmark): update gas limit configuration

---

.github/configs/evm-impl.yaml

fix(github): Set x-dist to auto for all evm impl

---

src/cli/pytest_commands/fill.py
src/ethereum_test_specs/static_state/state_static.py

This PR does two things:
- Disables `--generate-all-formats` automatic generation if `--fill-static-tests` is passed to the command: Currently, there's still a ton of [untagged static tests](https://github.com/ethereum/execution-spec-tests/blob/b815fee3a11dedbf30ecec7fc8455785a690e6da/src/ethereum_test_specs/static_state/state_static.py#L185-L190), which means they use hard-coded addresses and therefore have to be put in different groups to disallow collisions, and this results in 71% of tests being placed in different groups, which makes pre-alloc grouping not worth it.
- Adds the `pytest.mark.pre_alloc_group` mark to all untagged static tests, in order to, if we decide to fill static tests with pre-alloc grouping, the fill won't fail and we ensure these tests all have their own …

feat(fill): Disable `--generate-all-formats` for static tests

---

tests/osaka/eip7823_modexp_upper_bounds/test_modexp_upper_bounds.py

Adds basic cases to EIP-7823. Rotating the case where the length is 1025 and 0 for completeness.
1) exp=1025, mod=0, base=0
2) exp=0, mod=1025, base=0
3) exp=0, mod=0, base=1025
N/A.
```console
```

feat(tests): add case for large exp with zero mod/base length

---

tests/byzantium/eip198_modexp_precompile/helpers.py
tests/osaka/eip7883_modexp_gas_increase/conftest.py
tests/osaka/eip7883_modexp_gas_increase/vectors.json

Fixes the `ModExpInput.from_bytes` parser to pad inputs when necessary, but also retain the unpadded input which later becomes the actual input to the precompile in the test.
The `ModExpInput.from_bytes` parser would not pad and in fact modify the lengths passed to the pre-compile.
The `ModExpInput.from_bytes` parser now pads the input before processing and calculating the gas but also retains the original input to then pass it unpadded to the pre-compile.
Only `guido-4-even`, but the gas calculation remained unaffected, the only change was the expected output.
N/A.
```console
```

fix(tests): Fix `ModExpInput.from_bytes`

---

src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/static_filler.py
src/pytest_plugins/filler/tests/test_filling_session.py
src/pytest_plugins/filler/tests/test_format_selector.py
src/pytest_plugins/filler/tests/test_phase_manager.py

A suggestion for #2006 that attempts to better encapsulate filler logic regarding different "filling phases", i.e., pre-alloc-group generation and test filling.
- #2006 
This PR refactors the complex phase management and format selection logic in the filler plugin into clean, testable components. The changes improve code maintainability, eliminate duplication, and provide better separation of concerns without affecting existing functionality.
The original implementation had several issues:
- Complex conditional logic scattered across multiple functions
- Tight coupling between phase management and format selection  
- Difficult-to-test logic buried in pytest hooks
- Code duplication between `filler.py` and `static_filler.py`
- Direct config attribute access throughout the codebase …

refactor(fill): extract phase management into testable components

---

.github/configs/feature.yaml
.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml
docs/CHANGELOG.md
src/cli/pytest_commands/fill.py
src/ethereum_test_fixtures/__init__.py
src/ethereum_test_fixtures/base.py
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_specs/blockchain.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/static_filler.py
src/pytest_plugins/filler/tests/test_filling_session.py
src/pytest_plugins/filler/tests/test_format_selector.py
src/pytest_plugins/filler/tests/test_phase_manager.py

This PR deprecates `fixtures_static.tar.gz` from releases by moving them to their respective `fixtures_stable.tar.gz` or `fixtures_develop.tar.gz` depending on the fork.
Required refactoring the fixtures abstract class and the pytest filler plugin, along with the static tests filler.
N/A.
```console
```

feat(specs,filler,ci): Merge static tests into stable/develop, make `--generate-all-formats` compatible with static tests

---

.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml
src/ethereum_clis/transition_tool.py

The CI runner tag has been updated to allow use of faster vms.
Updated the tag `timeout-minutes` to be in the correct place.
The timeout for t8n server requests has been increased in order to prevent this from making tests fail.
N/A.
```console
```

fix(ci,clis): Change ci runner, fix `timeout-minutes`, Increase t8n timeout

---

docs/CHANGELOG.md
docs/running_tests/running.md
docs/running_tests/test_formats/blockchain_test_sync.md
src/cli/pytest_commands/consume.py
src/cli/pytest_commands/processors.py
src/ethereum_test_fixtures/__init__.py
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_rpc/__init__.py
src/ethereum_test_rpc/rpc.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_specs/state.py
src/pytest_plugins/consume/consume.py
src/pytest_plugins/consume/simulators/base.py
src/pytest_plugins/consume/simulators/simulator_logic/test_via_sync.py
src/pytest_plugins/consume/simulators/single_test_client.py
src/pytest_plugins/consume/simulators/sync/__init__.py
src/pytest_plugins/consume/simulators/sync/conftest.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_verify_sync_marker.py
src/pytest_plugins/shared/execute_fill.py
tests/osaka/eip7934_block_rlp_limit/test_max_block_rlp_size.py

Add a new test type that will send `consume engine` tests to client under test and then have a separate client sync to it. Parametrizes both client under test and sync client using hive client config file.
- Fill e.g. `uv run fill --fork=Osaka -k rlp_limit --clean` (or narrow down to one or two tests)
- Consume e.g. `uv run consume sync -v -s` (`-s` for good logs, `-v` for good test ids)
---
```console
```

feat(consume): Add `consume sync` tests to sync clients after engine tests

---

.github/workflows/fixtures.yaml
.github/workflows/fixtures_feature.yaml

Follow up to #2024. We can reduce again in the future.
N/A.
```console
```

chore(ci): bump to gigachungus

---

src/cli/show_pre_alloc_group_stats.py
src/ethereum_test_fixtures/collector.py
src/ethereum_test_fixtures/pre_alloc_groups.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/tests/test_prealloc_group.py

The fixture collector now has a flushing mechanism to flush to disk and remove from memory once a certain number of test fixtures have been collected (defaults to 1000).
Problem: when using x-dist, all workers had to load all pre-allocation groups at once at the start of the fill, without discrimination, and even when they would never use them throughout the fill.
The `PreAllocGroups` class is improved in this PR with lazy loading so the pre-allocation contents are only loaded when they are actually needed.
This results in around half of memory usage than with previous implementation.
Running:
```bash
uv run fill --clean --until=Osaka --fill-static-tests --ignore=tests/static/state_tests/stQuadraticComplexityTest --output=fixtures-develop.tar.gz -n auto
```
Before: 64G+ and OOM issues. …

feat(fill): Improve mem usage by: fixture collector flush + lazy loading pre-alloc groups

---

docs/CHANGELOG.md
src/cli/pytest_commands/consume.py
src/pytest_plugins/help/tests/test_help.py

* Remove broken `consume hive` command and related code paths
* Update help tests to exclude removed command
I went with sunsetting the cmd because users can already achieve the same result by running both commands separately:
`uv run consume rlp --input ./fixtures`
`uv run consume engine --input ./fixtures`
Fixes #1984
```console
```

chore(consume): remove `consume hive` command

---

tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py

Disables the longest running test in our test set that contains 8000+ blocks and takes around 30 minutes to fill.
Reasoning with the disabling of this test:
- We are basically testing a smart contract in these tests, if there's a failure in these contracts:
- We are never going to catch it with these tests because our tests are not changing
- It's not going to be a consensus failure because if the contract behaves in an unexpected way, all clients will still process the same EVM code
- Contract has been running in mainnet for sufficient time.
N/A.
```console
```

chore(tests): Disable full `HISTORY_SERVE_WINDOW` EIP-2935 Test

---

.github/scripts/fill_prepatched_tests.sh

The coverage workflow's `fill_prepatched_tests.sh` script fails when tests cannot run due to fork compatibility issues. This occurs when:
- Tests require future forks (Prague/Osaka) but the script is limited to `--until=Cancun`
- All collected tests get filtered out at execution time, resulting in "no tests ran"
- Script continues execution despite no fixtures being generated
This occurs in #1929 due to the small change in `tests/prague/eip7702_set_code_tx/test_set_code_txs.py` and via the removal of `"!tests/prague/**"` in `coverage.yaml` from #1970.
#1929 
```console
```

chore(ci): fix fill prepatched coverage script fork compatibility

---

tests/benchmark/test_worst_bytecode.py

Use only relative imports in the tests/ directory.
#1848
```console
```

refactor(tests): use relative imports in tests

---

src/pytest_plugins/consume/consume.py

Quick fix spotted only on the new server when trying to reproduce an error.
```
INTERNALERROR>   File "/home/spencer-tb/execution-spec-tests/src/pytest_plugins/consume/consume.py", line 91, in fetch_and_extract
INTERNALERROR>     tar.extractall(path=self.destination_folder, filter="data")
INTERNALERROR> TypeError: TarFile.extractall() got an unexpected keyword argument 'filter'
```
`filter` is only added in Python ~~3.12~~, 3.11.4 (cc comment from @felix314159), so I removed it in this PR.
N/A.
```console
```

chore(consume): fix consume cache for python 3.11

---

docs/running_tests/consume/exceptions.md

Remove hive command in docs for the disable exception mapper usage as it is incorrect. 
Please see the hive PR I am using instead for this: https://github.com/ethereum/hive/pull/1332
Note the exception mapper should really be mandatory, but we will re-enable once its sorted on the Nimbus-EL side.
N/A.
```console
```

chore(docs): remove erroneous section for exception mapper usage

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

This PR adds an edge case test to the P256VERIFY precompile test suite that probes mathematical boundaries where implementations may fail.
**Key addition:**
1. **Near-field boundary test (`near_field_boundary_p_minus_3`)**: Tests the maximum valid X coordinate (P-3) with 
corresponding edge values for signature components R=(N-2) and S=(N-1)/2. This ensures proper handling of field arithmetic at mathematical boundaries.
**Why these tests matter:**
- **X = P-3**: The largest X coordinate with a valid point on the P256 curve (P-2 has no valid Y due to quadratic non-residue)
- **R = N-2**: Tests near-maximum signature component handling
- **S = (N-1)/2**: Tests the malleability boundary where S equals its complement
- **H = P-1**: Tests maximum hash value and proper modular reduction
These …

feat(tests): add p256 precompile edge case test

---

docs/CHANGELOG.md
tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Add a few more tests for the p256verify precompile, specifically around what happens if a contract calls a precompile on initialization.
#1794 
```console
```

feat(tests): Add contract creation tests for 7951

---

.github/configs/feature.yaml
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
tests/osaka/eip7918_blob_reserve_price/test_blob_reserve_price_with_bpo_transitions.py

Implements a simple calculator for the base fee of the next block given the parent values.
Implements a calculator to get the gas-used of a parent block so that the next block has a specific base fee, given the parent values.
Fixes BPO4 tests in `tests/osaka/eip7918_blob_reserve_price/test_blob_reserve_price_with_bpo_transitions.py`.
Culprit is that, given the base fee and excess blob gas of the genesis, the block 1 excess blob gas value was exceeding the expected value for the test given the that the reserve mechanism was being activated.
Since there's no easy way to calculate the excess blob gas of the genesis given a static base fee, if the fixture detects that the reserve fee is being activated give the current test values, the fixture starts a binary search until it encounter a …

fix(tests,forks): Implement Base-Fee-Per-Gas calculation methods in `Fork`, fix BPO4 tests

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Adds a critical security test case for the P256VERIFY precompile to detect **invalid curve attacks** (CVE-2020-0601 class
vulnerability).
The test validates that implementations properly reject points that satisfy different elliptic curve equations. Specifically,
it tests a point on curve `y² = x³ - 3x + 1 (mod p)` where `b' = 1` instead of the correct P-256 parameter `b = 0x5AC635D8...`.
**Security Impact**: Without this test, vulnerable implementations could accept points on wrong curves, enabling attackers to
leak private keys through invalid curve arithmetic.
**Test Details**:
- Point coordinates: `(x=0x4, y=0x872A856D521EED42D28A60CCC2EAE42E1572F33BE2BF616DC9A762D51C459E2A)`
- This point is mathematically valid but on the WRONG curve
- Test ID: `invalid_curve_attack_b_equals_one` …

test(eip7951): add invalid curve attack test case for P256VERIFY

---

docs/CHANGELOG.md
docs/running_tests/execute/remote.md
src/pytest_plugins/execute/pre_alloc.py
src/pytest_plugins/execute/tests/__init__.py
src/pytest_plugins/execute/tests/test_pre_alloc.py

When running tests on networks that already have specific contracts deployed (such as mainnet or testnets with pre-deployed contracts), you can use the `--address-stubs` flag to specify these contracts instead of deploying new ones.
Address stubs allow you to map contract labels used in tests to actual addresses where those contracts are already deployed on the network. This is particularly useful for:
- Testing against mainnet with existing contracts (e.g., Uniswap, Compound)
- Using pre-deployed contracts on testnets
- Testing on bloat-net, a network containing pre-existing contracts with extensive storage history
- Avoiding redeployment of large contracts to save gas and time
You can provide address stubs in several formats:
**JSON string:**
```bash
uv run execute remote --fork=Prague …
```

feat(execute): Support for contract address stubs

---

docs/CHANGELOG.md
src/cli/pytest_commands/pytest_ini_files/pytest-fill.ini
src/ethereum_test_fixtures/blockchain.py
src/pytest_plugins/filler/filler.py
src/pytest_plugins/filler/witness.py
src/pytest_plugins/help/help.py

1. Adds an optional `executionWitness` field to the blockchain fixture base class.
2. Adds a new pytest plugin that:
- `pytest_addoption()`: add a boolean `--witness` flag.
- `pytest_configure()`: ~Compiles~ checks whether the `witness-filler` tool is in PATH if `--witness` is enabled; hard error if not.
- Provides a fixture `generate_witness` that generates a fixture's execution witness using the `witness-filler` tool.
3.  Calls the `generate_witness` fixture in `BaseTestParametrizer`. If `--witness` is not enabled, there is not change in `fill` behavior.
```
uv run fill tests/istanbul/eip1344_chainid/test_chainid.py --output=fixtures-witness --witness --clean
```
#2031
```console
```

feat(fill): add a plugin for optional execution witness generation

---

tests/frontier/opcodes/test_call.py

Hi! I believe a test like this exists for other opcodes but not for CALL, it is one of those that have a very large offset but size zero and therefore execution shouldn't revert because of the offset. In ethrex we had a bug that was fixed in [this PR](https://github.com/lambdaclass/ethrex/pull/3950). I created this test and tried it out before and after the fix and it detects the bug.
I am making these tests just for the CALL opcode but they apply to all xCALL opcodes, I don't know what the nicest way of making this more generic is. But generally this would be enough because these opcodes tend to have pretty similar logic inside of them.
N/A.
```console
```

feat(tests): add test for large args offset with size zero on CALL opcode

---

src/ethereum_clis/clis/besu.py

fix(clis/besu): blob allowance exception mapper

---

src/ethereum_test_rpc/rpc.py
src/pytest_plugins/execute/eth_config/eth_config.py
src/pytest_plugins/execute/eth_config/execute_eth_config.py

You can run it via `uv run execute eth-config --network=Mainnet --rpc-endpoint=https://<replace>@rpc.nimbus-besu-1.fusaka-devnet-3.ethpandaops.io --clients="besu,erigon,nethermind,nimbusel,reth" --network-config-file=./src/pytest_plugins/execute/eth_config/networks.yml -vv -s`
In the `test_eth_config_majority()` it requests and compares the `eth_config` responses of all provided `--clients`. Certain cl+el combinations might not be available so it picks the first working one for each exec client. The test is only passed if each execution client from the clients flag was successfully queried and all responses are identical. Otherwise an overview of which endpoints provided which response (which with hash) is given, so that client teams can be contacted about misconfiguration.
All other …

src(eth_config): added eth_config simulator prototype

---

tests/berlin/eip2930_access_list/test_tx_intrinsic_gas.py

Fixes an exception expectation on `test_tx_intrinsic_gas.py`.
Depending on the implementation, the client could hit `TransactionException.INTRINSIC_GAS_BELOW_FLOOR_GAS_COST` or `TransactionException.INTRINSIC_GAS_TOO_LOW` because both values, given the conditions, were equal.
N/A.
```console
```

fix(tests): Incorrect expected exception on `test_tx_intrinsic_gas.py`

---

docs/writing_tests/checklist_templates/eip_testing_checklist_template.md
src/pytest_plugins/filler/eip_checklist.py

Prints a new section with warnings about the checklist items if any.
Only warning at the moment is if the same test is marked both as "N/A" and "covered" at the same time.
Embed clickable links to the test that is referenced in the checklist.
Only issue at the moment is that the docs building process prints a ton of new `INFO` lines, and perhaps the reason is that the checklist is generated before the test reference markdown documents:
```
INFO    -  Doc file 'tests/prague/eip7702_set_code_tx/checklist.md' contains an unrecognized relative link
'../../../../tests/prague/eip7702_set_code_tx/test_set_code_txs/test_set_code_to_precompile/', it was left as is. Did you mean
'test_set_code_txs/test_set_code_to_precompile.md'?
INFO    -  Doc file 'tests/prague/eip7702_set_code_tx/checklist.md' …
```

feat(eip_checklist): Print warnings + embed links to test functions

---

tests/osaka/eip7823_modexp_upper_bounds/test_modexp_upper_bounds.py

Add 5 targeted test cases to improve EIP-7823 implementation coverage:
- all_exceed_check_ordering: Tests check ordering when all bounds exceed
- exp_mod_exceed_base_ok: Tests partial bound violations
- bitwise_pattern_base_exceed: Tests Nethermind bitwise optimization
- near_uint64_max_base: Tests revm integer conversion edge case
- zero_exp_mod_exceed: Tests zero exponent with modulus exceeding
N/A.
```console
```

feat(tests): add implementation coverage tests for modexp eip7823 bounds

---

.github/configs/eels_resolutions.json
docs/CHANGELOG.md
src/ethereum_test_specs/blockchain.py
src/ethereum_test_types/block_access_list/__init__.py
src/pytest_plugins/eels_resolutions.json
tests/amsterdam/eip7928_block_level_access_lists/test_block_access_lists_invalid.py

Fixes issues not caught by #2102. We fixed the t8n model to not allow extras but we did not fix the expectation model. We still had invalid tests that we did not catch which were silently still filling. This should resolve any issues with extra fields and should correctly set up the test expectations.
```console
```

fix(tests): Block-Level Access List invalid tests

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify_before_fork.py

Fixes a small issue that only happened during test collection in vscode, which is `tests/osaka/eip7951_p256verify_precompiles/test_p256verify_before_fork::py::test_precompile_before_fork` being a state test on a fork transition.
Issue appeared as:
```bash
nodeid: tests/osaka/eip7951_p256verify_precompiles/test_p256verify_before_fork.py::test_precompile_before_fork[fork_Prague-state_test--P256VERIFY]
kind: ('function', False)
class: Function
name: test_precompile_before_fork[fork_PragueToOsakaAtTime15k-state_test--P256VERIFY]
fspath: /home/marioevz/Development/Eth/execution-spec-tests/tests/osaka/eip7951_p256verify_precompiles/test_p256verify_before_fork.py
location: ('tests/osaka/eip7951_p256verify_precompiles/test_p256verify_before_fork.py', 18, …
```

fix(tests): Collect issue in test_p256verify_before_fork.py

---

tests/osaka/eip7883_modexp_gas_increase/test_modexp_thresholds.py

This PR adds a comprehensive set of implementation coverage (IC) test cases for the EIP-7883 ModExp precompile. These tests specifically target edge cases and implementation variations observed across different Ethereum clients.
- **Boundary Testing**: IC1, IC3, and IC4 test critical boundaries in the gas calculation formula where different implementations might diverge (32-byte boundary for complexity calculation, ceiling division edge cases)
- **Bit Counting Coverage**: IC5 and IC10 ensure all clients correctly count bits in sparse exponents, particularly when significant bits appear in unexpected positions
- **Native Library Edge Cases**: IC6 and IC7 test scenarios where clients might choose different optimization paths (native vs interpreted code), ensuring mathematical correctness is …

feat(tests): add implementation coverage tests for eip7883 modexp gas calculation

---

docs/CHANGELOG.md
src/ethereum_test_types/block_access_list/__init__.py
src/ethereum_test_types/block_access_list/modifiers.py
src/ethereum_test_types/tests/test_block_access_lists.py

To be clear, the current tests are not broken because the spec is implemented correctly. However, we were not enforcing certain validation rules that are required by EIP-7928. These changes introduce an initial up-front check on the entire order of the BAL coming from t8n as defined in EIP-7928:
> Ordering and Determinism
> 
> The following ordering rules MUST apply:
> 
>     - Addresses: lexicographic (bytewise).
>     - Storage keys: lexicographic within each account.
>     - Block access indices: ascending within each change list.
We fully validate all ordering upfront, based on the above rules, for the entire BAL coming from t8n. This is crucial that it meets all the requirements for the EIP implementation.
We define the expectation as a `dict` with `address: BalAccountChanges`. We …

feat(tests): Enforce EIP-7928 ordering rules

---

src/pytest_plugins/consume/simulators/simulator_logic/test_via_engine.py

Title. As requested by Erigon.
N/A.
```console
```

chore(consume): increase fcu retries to 30 (at 1 second each)

---

pyproject.toml
tests/cancun/eip1153_tstore/test_tstorage.py
tests/cancun/eip4788_beacon_root/spec.py
tests/cancun/eip4844_blobs/test_blobhash_opcode.py
tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
tests/prague/eip7702_set_code_tx/test_gas.py
tests/prague/eip7702_set_code_tx/test_set_code_txs.py
tests/prague/eip7702_set_code_tx/test_set_code_txs_2.py
tests/unscheduled/eip7692_eof_v1/eip3540_eof_v1/test_execution_function.py

Rule C420 is [unnecessary-dict-comprehension-for-iterable (C420)](https://docs.astral.sh/ruff/rules/unnecessary-dict-comprehension-for-iterable/#unnecessary-dict-comprehension-for-iterable-c420).
The 18 errors are only visible in newer ruff versions (e.g. `0.9.6` will show 0 errors, but `0.11.8` will show 18 errors). To use the same ruff version that tox will use in CI run 
`.tox/lint/bin/ruff check --no-fix --show-fixes src tests .github/scripts`. 
Ruff was able to autofix everything with 
`.tox/lint/bin/ruff check --fix --show-fixes src tests .github/scripts`, 
I re-ran mypy after that and there are no complaints. Should be safe to merge.
Relevant for #2128 
N/A.
```console
```

chore(tooling): enforce ruff rule c420

---

docs/CHANGELOG.md
src/ethereum_clis/clis/geth.py
src/ethereum_test_exceptions/exceptions/block.py
src/ethereum_test_fixtures/blockchain.py
src/ethereum_test_forks/base_fork.py
src/ethereum_test_forks/forks/forks.py
src/ethereum_test_specs/blockchain.py
src/ethereum_test_types/block_access_list/__init__.py
tests/amsterdam/eip7928_block_level_access_lists/test_block_access_lists_invalid.py

- Glamsterdam is updating to `engine_newPayloadV5` ([source](https://github.com/ethereum/execution-apis/pull/691/files)). We should use this in Amsterdam. This is an update to the `ExecutionPayload` only, no new fields introduced to the `EngineNewPayload` parameters directly.
- This also updates some exceptions to the mapper as I've started to map these to the working geth branch `jwasinger/bal-execution`.
This should fix most issues with `consume engine` tests for Block-Level Access Lists (BALs). The remaining items are aligning on exceptions for the exception mapper which I've started to do in this PR.
- **2 exception improvements**: There are two `TransactionException` nonce-related exceptions I'm getting from geth on invalid BAL fields that should perhaps be changed to be BAL specific …

fix: use `engine_newPayloadV5` for Glamsterdam

---

src/pytest_plugins/execute/pre_alloc.py

When deploy_contract() is called with a stub parameter, it retrieves the existing contract from the chain and adds it to the allocation. However, the method was missing a return statement after handling the stub case, causing it to continue executing and attempt to deploy a new contract with the stub's bytecode.
This led to an assertion error when the retrieved bytecode (Bytes type) didn't match the expected types (Bytecode or Container) for deployment.
The fix adds a return statement after the stub handling block to properly exit the method and return the stub's contract address.
The related issue is the inclusion of stub contracts themseleves in https://github.com/ethereum/execution-spec-tests/pull/2073
```console
```

chore(execute): add missing return statement for stub contract deployment

---

docs/CHANGELOG.md
docs/filling_tests/filling_tests_command_line.md
src/cli/pytest_commands/fill.py
src/cli/pytest_commands/processors.py
src/cli/pytest_commands/watcher.py
whitelist.txt

Adds `--watch` flag that monitors test files for changes and automatically re-runs the fill command when developing tests. Its quite rudimentary but does not use any external library for watching.
A verbose variant of the flag called `--watcherfall` does not clear the terminal between fills.
1. Get all file modification times → dict
2. Run fill command initially
3. Loop:
- Sleep 0.5s
- Get current file modification times → new dict
- If new dict != old dict:
- Clear screen
- Re-run fill command
- Update old dict = new dict
closes #2156 
```console
```

✨ feat(fill): watch mode

---

src/ethereum_clis/clis/reth.py

Updates the Reth exception mapper regex pattern to match the new error message format returned by the Reth client for gas limit exceeded errors.
N/A.
```console
```

chore(cli): update reth gas limit exception mapper

---

src/ethereum_clis/clis/nethermind.py

Latest from hive.
```
E   pytest_plugins.consume.simulators.simulator_logic.test_via_engine.LoggedError: Undefined exception message: expected exception: "TransactionException.NONCE_IS_MAX", returned exception: "NonceTooHigh: Nonce exceeds max nonce" (mapper: "NethermindExceptionMapper")
```
N/A.
```console
```

chore(cli): nethermind max nonce exception mapper

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Add better test inputs for the `p256verify` precompile where at least `r` or `s` is `0 mod N`. There test cases represent invalid inputs but in some category of incorrect implementations have chance to be positively verified.
#2194
```console
```

feat(tests): add test cases for P256 with zero h, r, s

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Synthesize the `p256verify` precompile inputs where `u1 == u2` in two variants: `Q == G` and `Q != G`. In the first variant the computation of `R` involves point doubling.
#2194 
```console
```

feat(tests): add test case for point doubling in P256

---

.vscode/launch.recommended.json

`launch.recommended.json` which is being advised for VS code debugging in Getting Started didn't work, as the `pytest.ini` files have moved. This PR is just a minimal set of updates to make it work for `fill` and also adding support for `consume direct`.
N/A.

chore(tooling): fix `launch.recommended.json` - vs code debugging

---

tests/homestead/identity_precompile/__init__.py
tests/homestead/identity_precompile/test_identity.py

Adds a test for the identity precompile based on this https://github.com/ethereum/go-ethereum/blob/master/docs/postmortems/2021-08-22-split-postmortem.md
Also adds a new variant that can be filled for EOF `EXT*CALL` opcodes .

new(tests): Identity precompile test

---

tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Add a test case for the `p256verify` precompile with the input having public key (Q) as the point-at-infinity. If the implementation misses the check that Q is not at infinity, the signature should verify.
#2194 
```console
```

feat(tests): add test case for P256 with Q at infinity

---

docs/CHANGELOG.md
tests/osaka/eip7951_p256verify_precompiles/test_p256verify.py

Add more tests cases for the `p256verify` precompile where the final computed point `R` is at infinity by passing `Q = -G` and `u1 == u2`.
Similar test cases exist in "wycheproof_extra".
#2194 
```console
```

feat(tests): add more tests for P256 where R is at infinity

---

src/ethereum_test_forks/forks/forks.py
src/pytest_plugins/execute/eth_config/networks.yml

Updates BPO param valuse to match that of those set in the testnet configs:
- Holesky: https://github.com/eth-clients/holesky/blob/main/metadata/genesis.json
- Sepolia: https://github.com/eth-clients/sepolia/blob/main/metadata/genesis.json
- Hoodi: https://github.com/eth-clients/hoodi/blob/main/metadata/genesis.json
https://github.com/ethereum/go-ethereum/pull/32735
```console
```

chore(forks): update bpo hardfork params to match testnet

---

docs/CHANGELOG.md
pyproject.toml
src/pytest_plugins/consume/simulators/simulator_logic/test_via_sync.py
src/pytest_plugins/consume/simulators/sync/conftest.py
uv.lock

This should be a quick merge if we accept the flakiness of client syncing. Here we add `flaky` to all `verify_sync` tests in order to re-run them as most of the time this is flakiness on the side of spinning up the clients and getting them to sync. I think this is inherent where sometimes it works and sometimes it doesn't. Perhaps we can investigate a way to remove this in the future but it's important to discern what is an actual fail and what can be "fixed" by just retrying the sync.
I also simplified the sync check a bit as we had an outdated setup still lingering.
With these changes, ran locally, I got:
```
========== 288 passed, 4 rerun in 1017.33s (0:16:57) ==========
```
```console
```

chore(consume): mark sync tests flaky

---

tests/berlin/eip2930_access_list/test_acl.py

Hi! We were syncing ethrex on mainnet and we found a bug in our code in the process. We found out that we had a gas mismatch in [this transaction](https://etherscan.io/tx/0x274e16a80e3473062ac8cb75d251a9822a443405c0901c58334b5bbf805209a2/advanced). Turns out that it has a very particular access list that has the same address twice in it and we weren't contemplating that scenario. This was fixed in https://github.com/lambdaclass/ethrex/pull/4741
We thought it'd be nice to add a test for this, so here it goes. Suggestions are welcome 😄 
https://github.com/lambdaclass/ethrex/pull/4741
```console
```

feat(tests): test accessing slots in address that appears more than once in access list

---

tests/byzantium/eip198_modexp_precompile/test_modexp.py

Add an modexp precompile test case which fixes missing coverage in evmone.
#2224 
```console
```

feat(tests): add test for modexp with 2**32 exp len

---

README.md
docs/getting_started/installation.md

Cloning the full repository is 8 GB and takes forever cloning only with depth 1 reduces this to 376 M. 
Also fix inconsistency between python versions in README.md and installation.md

docs(fix) update git clone with depth 1

---

src/pytest_plugins/filler/pre_alloc.py
src/pytest_plugins/filler/tests/test_pre_alloc.py
tests/benchmark/test_worst_compute.py

We do not verify the deployed code size limit in fill, this leads to several issue:
- The `PUSH` benchmark test is actually invalid.
- We do not notice the limit in bloatnet benchmark test -> i left a review that is impossible to implement.
This PR enforces the deployed contract size limit check and resolve the failing test.
PR #2090 
Comment: https://github.com/ethereum/execution-spec-tests/pull/2090#issuecomment-3285384772
```console
```

feat(pre_alloc): Add maximum bytecode size limit for contract deployment

---

src/pytest_plugins/consume/simulators/simulator_logic/test_via_sync.py

Consume sync can fail with `TypeError: 'NoneType' object is not subscriptable` when attempting to verify block state roots immediately after the sync completes. The `get_block_by_hash()` call returns `None` because the block isn't yet queryable, even though the forkchoice update returned `VALID`.
Add explicit `None` checks for retrieved blocks in the verification retry loop.
Follow up from: #2252 
```console
```

chore(consume): fix consume sync logger errors

---

.github/configs/eels_resolutions.json
src/pytest_plugins/eels_resolutions.json

Follow up to #2234.
N/A.
```console
```

chore(ci|fill): bump eels for bpo1/2 param changes
